### ISSUE TITLE
个性化推荐训练和测试结果不匹配问题

### ISSUE THREAD

**Issue by 13812453806** [PaddlePaddle/Paddle#10021]
使用个性化推荐参考代码：
http://www.paddlepaddle.org/docs/develop/book/05.recommender_system/index.cn.html
使用默认训练数据集：
URL = 'http://files.grouplens.org/datasets/movielens/ml-1m.zip'
MD5 = 'c4d9eecfca2ab87c1945afe126590906'
遇到二个问题：
1. 每次执行训练后执行预测，输入参数保持不变的情况 prediction 输出每次都不一样，4-4.2之间随机变化，这是什么原因？
2. 保存训练结果：parameters.to_tar(f)， 预测时读取训练参数 parameters.init_from_tar(f) ，输入参数保持不变的情况下， 预测结果和第1步预测结果总差0.1左右，这又是什么原因?

还有一个问题，如果用户信息增加或修改了，或者电影信息增加修改了，整个训练过程需要完整重新执行一次吗？有没增量执行的方法？

**Comment by dzhwinter** [comment]
1. 只是个demo，数据里做过random, https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/dataset/movielens.py#L151

2. 在这个demo里，电影信息增减，可以增量训练，不需要完整重新train。用户id则不能，因为模型里记下id了。recommendation这只是demo，内容和用户增量训练框架本身是支持的，都可以实现

**Comment by 13812453806** [comment]
@dzhwinter 你好，谢谢你的回复
进行增量的增量训练的步骤是什么的？我没找相关API，是不是有修改 layer data 的 type 的方法？ 还是可以从保存的 param tar , pkl 文件中读取训练模型 修改更新 相关配置后再重新训练？能麻烦简单贴几行代码以供参考吗？非常感谢。

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
