### ISSUE TITLE
ltr中ranknet模型infer阶段左右两边网络结果不一致

### ISSUE THREAD

**Issue by xlhlhlx** [PaddlePaddle/Paddle#10404]
## 1、问题描述
参考 https://github.com/PaddlePaddle/models/tree/develop/ltr 模型，构造了一个ranknet模型，也是有左右两个part，两个part的网络是一样的，底层的embedding层和中间的relu层的参数都是共享的，在infer阶段，相同的数据，分别用 output = half_ranknet("right", dict_size, emb_size) 和 output = half_ranknet("left", dict_size, emb_size) 对预测数据进行预测，得到的结果竟然不一样。具体结果sample如下：
left结果：
![left](https://user-images.githubusercontent.com/28750940/39612034-76081a9a-4f8e-11e8-8a77-7e2564920c5f.png)
right结果：
![right](https://user-images.githubusercontent.com/28750940/39612050-9b37ee30-4f8e-11e8-9378-d40a689950ac.png)

## 2、疑问
在两边网络结果一致且参数共享的情况下，不管预测阶段是用left还是right，结果不应该是一摸一样吗？为什么这中间有差异呢？

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
