### ISSUE TITLE
是否可以用PaddlePaddle 实现 Pointer-Generator Network

### ISSUE THREAD

**Issue by limiao06** [PaddlePaddle/Paddle#10851]
我在做一个文本摘要任务，想用paddle.v2实现一个类似[Pointer-Generator Network](http://aclweb.org/anthology/P/P17/P17-1099.pdf) 的网络结构， 过程与attention-based seq2seq模型比较相似，但是区别在于解码时，需要把输入句子每个词的attention score转化为输出的词分布，如下图的蓝色部分所示。 我看了一下tensorflow 里有 tf.scatter_nd 这个函数可以实现这个功能，但是我在paddle的API 文档中没有找到类似的函数，请问下目前怎么用paddlepaddle实现这种功能呢？

![image](https://user-images.githubusercontent.com/12964198/40398387-a1977a0e-5dec-11e8-8df3-e6439b26ebd6.png)

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
