### ISSUE TITLE
beam_search如何只输出一个最佳结果

### ISSUE THREAD

**Issue by lucywsq** [PaddlePaddle/Paddle#10853]
我用的是attention解码，
beam_gen = paddle.layer.beam_search(
name=decoder_group_name,
step=gru_decoder_with_attention,
input=group_inputs,
bos_id=176,
eos_id=177,
beam_size=5,
num_results_per_sample=2)

1. 我设置num_results_per_sample为1的时候崩溃，提示list越界
2.假如我只想输出attention的softmax后的概率值，该调用什么函数

**Comment by pkuyym** [comment]
```
1. 我设置num_results_per_sample为1的时候崩溃，提示list越界
```
如果设置`num_results_per_sample=1`崩溃，可能有bug，这个可以后续取top 1的结果输出，不一定要依赖beam search

```
2. 假如我只想输出attention的softmax后的概率值，该调用什么函数
```
可以看一下这个函数的接口，infer函数里面可以指定`output_layer`
```
def infer(output_layer, parameters, input, feeding=None, field='value'):
```

**Comment by pearlcurly** [comment]
明白，追问一下，如果不用beam_search，只想获取各个标签的概率怎么解决呢？

**Comment by pkuyym** [comment]
```明白，追问一下，如果不用beam_search，只想获取各个标签的概率怎么解决呢?```
这个不是很明白，你的意思是解码过程中获取每一步的概率分布吗？这样的话，不建议使用beam seach layer，这里有一个python端实现的beam search，灵活度很大，你可以参考一下
https://github.com/PaddlePaddle/models/blob/develop/generate_sequence_by_rnn_lm/beam_search.py
速度上肯定和beam search layer有差异，但是灵活度很大

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
