### ISSUE TITLE
CAPI下， GTEST 中多个TEST case中包含paddle_xxx_create 时paddle内存错误出core

### ISSUE THREAD

**Issue by memeda** [PaddlePaddle/Paddle#11217]
# # 问题

CAPI下，用GTEST测试数据填充，突然发现，如果两个TEST里均包含paddle_xxx_create时，第二个就会报错，报错的内容如下：
![image](https://user-images.githubusercontent.com/5585818/41013901-ee4e72be-697a-11e8-9293-ebcb1d9a014d.png)

而且，如果我把这两个TEST CASE中的代码放到一个TEST case中，就不会报错了！ 请问这个是什么原因呢？

## UPDATE

怀疑是不是 paddle_matrix_create 的原因？

我以为这个函数会自己创建空间的，但是似乎没有？

**Comment by dzhwinter** [comment]
请提供一下你的测试代码？

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
