### ISSUE TITLE
Paddle fluid dynamic_gru与主流实现不一致

### ISSUE THREAD

**Issue by seanxh** [PaddlePaddle/Paddle#11214]
最近我在尝试将keras/mxnet的模型导入fluid。发现fluid的gru实现与主流不太一致。

[fluid gru文档](http://www.paddlepaddle.org/docs/develop/api/fluid/en/layers.html#dynamic-gru)
![image](https://user-images.githubusercontent.com/5815297/41011798-188a348c-6971-11e8-88f0-dd75f15bfa65.png)

其中![](http://latex.codecogs.com/gif.latex?h_t=\(1-u_t\)*h_{t-1}+u_t*\\overset{\\sim}{h_t}) 的前后顺序颠倒了。

文档中引用 的那篇Paper引用的A gated recurrent unit (GRU) was proposed by Cho et al. [2014] ，但却给出了错误的公式。

[Cho的论文](https://arxiv.org/pdf/1406.1078.pdf)中是正确的

![image](https://user-images.githubusercontent.com/5815297/41011963-ffcec966-6971-11e8-8338-b22b2b8a9e56.png)

请看下，是否应该修正。现在的实现和其它框架之间很难迁移

**Comment by guoshengCS** [comment]
目前fluid这个实现是为了和之前V2的一致，方便V2训练的模型到Fluid的迁移，而且确实有相关线上模型在从V2迁移使用。这个的修改可能还需要另行讨论，可否先行使用DynamicRNN封装一个。

**Comment by seanxh** [comment]
明白。可以在GRU里增加一个参数，来选择是哪种实现，啊哈

**Comment by lgone2000** [comment]
能否 缺省参数实现需要和论文或者其他框架一致，ocr我们训练时可以指定为非缺省参数

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
