### ISSUE TITLE
关于dataprovider yield数据名称的问题

### ISSUE THREAD

**Issue by HugoLian** [PaddlePaddle/Paddle#1125]
在dataprovider中，如果按顺序yield三个vector, 如：
```yield word_vector, tag_vector, label```
训练没有问题。
有人说最好加个名字，和data_layer的name对应上，于是写成：
```yield {'input_word':word_vector,  'input_tag':tag_vector, 'label':label}```
这样训练的时候初始化参数会抛出错误：
Check failed: PySequence_Check(seq_)

我用的paddle是昨天下载的一件编译版本，难道是版本问题，不支持这种写法么？
#1114 这个是报错的那个ISSUE

**Comment by buptzzl** [comment]
我使用 0.90版本也出现这种问题。而且是加载了一下数据后中途抛出这个错误：
`Paddle release a new version 0.9.0, you can get the install package in http://www.paddlepaddle.org
I0207 10:50:41.679668 34506 Util.cpp:155] commandline: /home/zhouliaoming01/libs/paddle_neibu_bin/local/output/bin/../opt/paddle/bin/paddle_trainer --config=trainer_config.base.py --save_dir=./output --trainer_count=10 --log_period=100 --num_passes=5 --use_gpu=false --show_parameter_stats_period=100 --test_all_data_in_one_period=1-
I0207 10:50:41.679867 34506 Util.cpp:130] Calling runInitFunctions
I0207 10:50:41.680160 34506 Util.cpp:143] Call runInitFunctions done.
[debug] trainer_config.conf
[INFO 2017-02-07 10:50:41,814 networks.py:1466] The input order is [input0, input1, input2, input3, input4, input5, input6, input7, input8, input9, input10, label]
[INFO 2017-02-07 10:50:41,814 networks.py:1472] The output order is [__cost_0__]
I0207 10:50:41.816539 34506 Trainer.cpp:122] ignore sparse_remote_update=true due to  --local=true
I0207 10:50:41.816560 34506 Trainer.cpp:167] trainer mode: SgdSparseCpuTraining
I0207 10:50:41.871948 34506 PyDataProvider2.cpp:257] loading dataprovider dataprovider::process
I0207 10:50:41.873567 34506 PyDataProvider2.cpp:257] loading dataprovider dataprovider::process
I0207 10:50:41.873749 34506 GradientMachine.cpp:134] Initing parameters..
I0207 10:50:41.899520 34506 GradientMachine.cpp:141] Init parameters done.
[info] process() begin. used_slots: ['input0', 'input1', 'input10', 'input2', 'input3', 'input4', 'input5', 'input6', 'input7', 'input8', 'input9', 'label']
[debug] ins keys: ['input2', 'input3', 'input0', 'input6', 'input7', 'input4', 'input5', 'input8', 'input9', 'label', 'input10']
[debug] ins keys: ['input2', 'input3', 'input0', 'input6', 'input7', 'input4', 'input5', 'input8', 'input9', 'label', 'input10']
I0207 10:51:08.878790 34848 ThreadLocal.cpp:37] thread use undeterministic rand seed:34849
F0207 10:51:08.878875 34848 PythonUtil.h:215] Check failed: PySequence_Check(seq_)-
*** Check failure stack trace: ***
    @          0x13b4438  google::LogMessage::Fail()
    @          0x13b4390  google::LogMessage::SendToLog()
    @          0x13b3e25  google::LogMessage::Flush()
    @          0x13b6be6  google::LogMessageFatal::~LogMessageFatal()
    @           0x5ba23e  paddle::SparseNonValueScanner::prepare()
    @           0x5bfda5  paddle::PyDataProvider2::getNextBatchInternal()
    @           0x5a0c12  paddle::DoubleBuffer::asyncLoadBatch()
    @     0x7ff4c2d7e8a0  execute_native_thread_routine
    @     0x7ff4c35fc1c3  start_thread
    @     0x7ff4c24ef12d  __clone
/home/zhouliaoming01/libs/paddle_neibu_bin/local/output/bin/paddle_local: line 109: 34506 已放弃               ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}`

**Comment by livc** [comment]
yield的字段需要seqence类型，可以参考 #2622 。
