### ISSUE TITLE
在保持网络结构完全不变的情况下 是否有比较方便的方法把训练好的模型参数或者变量统一改成指定的有意义的名字?

### ISSUE THREAD

**Issue by lgone2000** [PaddlePaddle/Paddle#11373]
如题

**Comment by Yancey1989** [comment]
暂时没有比较好的方法，不过
> 参数或者变量统一改成指定的有意义的名字?

 这样做的最终需求是什么呢？

**Comment by lgone2000** [comment]
训练时没指定名字，应该是框架自动生成的名字，后续使用模型时 想用指定的名字

**Comment by Yancey1989** [comment]
框架自动生成的名字可以用`.name`直接print出来
```python
fc = fluid.layers.fc(input=x, size=4096, act=None)
print(fc.name)
```

> 后续使用模型时 想用指定的名字

可以举一个具体的case么，或许可以提供更有效的建议。

**Comment by lgone2000** [comment]
比如我想finetune一个resnet50模型，想把不同block参数的learningrate区别设置，有办法做到吗？原来想看是否能把参数的名字重新命名，然后按照过滤出来。

**Comment by lgone2000** [comment]
另外不同层的模型参数共享是否是通过指定相同的参数名实现的呢？ 如何利用paddle的命名来操作变量？

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
