### ISSUE TITLE
CE模型: sequence_tagging_for_ner 执行模型出错

### ISSUE THREAD

**Issue by guochaorong** [PaddlePaddle/Paddle#11615]
http://18.222.34.7:8080/viewLog.html?buildId=881&buildTypeId=Paddle_ContinuousEvaluation&tab=buildLog   这是错误日志

![error](https://user-images.githubusercontent.com/32069604/41693420-c268e062-7537-11e8-98fd-e88dab415c2e.png)

从11102 开始这个错误出现
![222](https://user-images.githubusercontent.com/32069604/41693760-5da66864-7539-11e8-9419-b2ead5b415ee.JPG)

11102 代码
https://github.com/PaddlePaddle/Paddle/pull/11102

复现方法：
登录到CE web
http://18.222.34.7:8080/
点击
![444](https://user-images.githubusercontent.com/32069604/41693849-efe2f012-7539-11e8-9a35-8c5afef7fa99.JPG)

进入后， 点击右上角run右边， 选择 run的pr id
![333](https://user-images.githubusercontent.com/32069604/41693813-b1635a48-7539-11e8-9167-49bbb303e041.JPG)

**Comment by panyx0718** [comment]
@tensor-tang 如果短期内修不好就先revert?

**Comment by tensor-tang** [comment]
我没意见，这个是mkldnn的新feature。

并且我还在定位问题，他并没有改变原有逻辑，只是加了use_mkldnn=false这些attr。

**Comment by tensor-tang** [comment]
@mozga-intel , this should be caused by your commits in #11102

How to reproduce on your local machine:
1. build paddle with `WITH_GPU=ON` and install
2. git clone https://github.com/PaddlePaddle/paddle-ce-latest-kpis.git && cd 
 sequence_tagging_for_ner
3. remove `from continuous_evaluation import *` at train.py
4. then run.xsh

As a hot fix, I would revert this feature at this moment.

**Comment by mozga-intel** [comment]
@tensor-tang Thank you, I will reproduce it as soon as possible.
