### ISSUE TITLE
paddle多卡训练加速比问题

### ISSUE THREAD

**Issue by dyning** [PaddlePaddle/Paddle#11627]
在训练paddle模型时发现，与单卡相比，训练使用4卡的加速比2.18，8卡的加速比3.7，利用率不高，可以利用分类问题复现，不知是什么问题？ @panyx0718

**Comment by zchengquan** [comment]
训练基于全卷机网络的one-stage检测器（类似densebox), 在k40机器上，单卡vs2卡，加速比1.2左右；单卡vs4卡加速比1.9左右；而同等配置下tf 单卡 vs 2卡加速比已经可达到1.93左右。paddle的多卡训练加速比偏慢太多，很影响模型训练。

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
