### ISSUE TITLE
fluid多线程极端情况下抛异常

### ISSUE THREAD

**Issue by wangyonghuiwyh** [PaddlePaddle/Paddle#11715]
多线程时，线程第一次跑时偶发性报下面异常：
 Cannot find feed_var in scope, feed_var_name is feed_2 at [/home/map/git/Paddle/paddle/fluid/operators/feed_op.cc:41]
查了一下， feed_2是我们多线程设置的feed_holder_name, 2是线程号。但是后续跑就ok了，很奇怪，我们线上跑了几周，线上出现过一次，线下也出现过一次。看着像是多线程时copy_program->SetFeedHolderName(feed_holder_name);不是立即生效，而是有一定延迟。所以scope会报。由于是线上在用的，所以麻烦给看看，否则会影响在线稳定性

![image](https://user-images.githubusercontent.com/40590543/41892560-1ee5f598-794b-11e8-8f68-ef4df41d14c0.png)

执行操作：_executor->Run(*copy_program, cur_pmt->_scope, &feed_targets, &fetch_targets, true, feed_holder_name, fetch_holder_name);

**Comment by qingqing01** [comment]
不确定调用在SetFetchHolderName之后调用Flush是否可行:

```
copy_program->Flush();
```

源码：
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/program_desc.h#L54:8


@luotao1 @Superjomn 可否帮忙看下？

**Comment by Superjomn** [comment]
可否描述下，多线程是如何多线程？

参数是否共享？ 如果是一个 executor，多线程调用的话会有问题.

如果是新模型上线，建议用 inference 封装的高层接口 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/contrib/inference/paddle_inference_api.h

多线程例子
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/contrib/inference/test_paddle_inference_api_impl.cc#L151

**Comment by wangyonghuiwyh** [comment]
@Superjomn 我们用的是以前给的示例, executor, scope等都是共享的，参照的是：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/tests/test_multi_thread_helper.h 有什么快速办法能解决这个问题吗？还是说必要升级到你给的高级api

**Comment by Superjomn** [comment]
两种方法，一种是不共享 executor，每个线程单独一个 executor，理论上绝对不会有多线程的问题。

二是用新接口，参考多线程的 demo，里面的参数是共享的，而且做了线程安全的处理。

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
