### ISSUE TITLE
稀疏特征的embedding层的默认值问题

### ISSUE THREAD

**Issue by chaos-dd** [PaddlePaddle/Paddle#11769]
如果模型有多个稀疏特征slot，比如性别、年龄，两个slot，每个slot对应一个embedding，单独feed数据。但是有些样本会确实部分特征slot，但是现在paddle要求每个slot必须feed数据，而且embedding也没法指定默认值。
V2版本API，不知道有没有workaroud的方法
比如这个issue #3002

**Comment by Yancey0623** [comment]
目前v2和Fluid均不支持这个功能，或许后续可以作为embedding的一个新feature加入进来。

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
