### ISSUE TITLE
对于多分类模型训练，PrecisionRecallEvaluator是否可以输出若干label的总准召？

### ISSUE THREAD

**Issue by hytirt** [PaddlePaddle/Paddle#11770]
看了一下v2中PrecisionRecallEvaluator的源码，目前支持整体的marco、mirco以及单个label的准召F1。
如果希望只计算其中某几个label的总准召和F1，有什么解决的办法呢？
此外，是否可以获得每个label的TP、FP、FN值，方便从绝对数量的维度上进行统计？

**Comment by Yancey0623** [comment]
可以在 `EventHandler` 中实现自定义的评估指标，请参考：https://github.com/PaddlePaddle/models/tree/develop/ltr#%E8%AE%AD%E7%BB%83%E8%BF%87%E7%A8%8B%E4%B8%AD%E8%BE%93%E5%87%BA%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%84%E4%BC%B0%E6%8C%87%E6%A0%87

**Comment by hytirt** [comment]
请问在每轮Pass后调用trainer.test时，是否也能实现自定义评估指标呢？我尝试了一下，getLayerOutputs只能得到最后一个batch的结果，而且内存有限，无法一次性读入所有验证集数据。

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
