### ISSUE TITLE
We are planning to add MKL static library

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#12192]
We are planning to link `-lmkl_core -lmkl_gf_lp64 -lmkl_intel_lp64 -lmkl_sequential` in MKL static library, which is the so-called BIG MKL package.

This should be something not expected by MKLDNN, right? 

We can only  link `-lmkl_rt` for MKLDNN, but would not work if we link the sequential lib.

And it seems MKLDNN does not generate static library.

**Comment by emfomenk** [comment]
(Intel MKL-DNN dev here)
First of all the link line above is incorrect: both `libmkl_gf_lp64` and `libmkl_intel_lp64` are interface layers. I think you should drop `gf_lp64` since it makes sense only when GNU Fortran is used. So the right link line would be:
```
-lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl
```

Next. Why doesn't `libmkl_rt` work for you?
It allows using Intel MKL sequentially by setting either environment variable `MKL_THREADING_LAYER=SEQUENTIAL` or by calling corresponding C function `mkl_set_threading_layer()` before first call to Intel MKL. In this case that would also make an effect on Intel MKL-DNN that is linked with MKL-RT.

**Comment by tensor-tang** [comment]
Glad to see you here @emfomenk , thanks for your comments.

Yes, you are right, actually we only need these three `mkl_intel_lp64 mkl_sequential mkl_core`, which is also we used to do. I should be more clear.

As for the case of MKL-RT, we are worried about if we ONLY linked this three libs, does it may lead MKLDNN to work with only 1 thread calling MKL, such as FC. Or something unexpected from MKLDNN side. That's the reason we considering MKL-RT. If you have some ideas or suggestions, please go ahead, we are glad to hear your voice from MKLDNN dev side.

**Comment by emfomenk** [comment]
It is highly recommended to avoid two versions of the library to be loaded within one application. In particular two different Intel MKL. So I would suggest considering 2 options:

1. Intel MKL-DNN is built **w/o** Intel MKL (neither full Intel MKL nor Intel MKL-ML). In this case PaddlePaddle can be built with whatever Intel MKL (RT, 3 explicit libraries, ...) -- there should not be any problems, because of conflicting Intel MKL's. However that might affect Intel MKL-DNN performance wrt inner-product and gemm-based convolution fallback.

2. Somehow align how you build Intel MKL-DNN and PaddlePaddle. For example use `libmkl_rt` everywhere. Then only one Intel MKL would be presented in the application. You would also be able to control whether the threading using the environment variable I showed above. In this case Intel MKL would be consistent for both PaddlePaddle and Intel MKL-DNN -- both would either use threaded or sequential Intel MKL underneath.

**Comment by tensor-tang** [comment]
Thanks @emfomenk , following your suggestions would make my concerns much more clear.

That's a tough option.

> 1. Intel MKL-DNN is built w/o Intel MKL 

a. Then how about the iomp? We should always keep iomp is linked for MKL-DNN right? I thought this would also affect the other convolution implementations, like AVX512 conv.  What if we link paddle with the 3 libs and iomp, but MKL-DNN only with iomp, then does AVX512 conv work fine? does the MKL sequential lib impacts AVX512 conv which called openmp?

b. If we do not use Intel MKL in MKLDNN, *ALL* gemm-based implementations would be impacted, right? And it's not predicable that you would have more gemm-based implementations as back-up, for example igemm for int8 conv. And we can not estimate how many workloads would be impact, since we have some old CPUs. So we may still want build MKL-DNN with MKL.

> 2. Somehow align how you build Intel MKL-DNN and PaddlePaddle. For example use `libmkl_rt` everywhere

a. Sure, we want to align all to avoid conflicts and get best performance. But there seems no static library of MKL_RT, right?  And static is an important reason we want to choice Intel-MKL(not MKLML).

**BTW**, it would be very grateful that MKL-DNN supports static lib.

b. Of course we could use the way you said to control thread, but do they have same performance? The one RT(maybe only support dynamic) and control, compares the one 3 explicit libs.

c. If we use three explicit libs in paddle, and build MKLDNN with same version MKL. This would still make MKL-DNN unpredictable right? Such as , FC run on ONLY one core, or AVX512 conv (which used omp) would also run on ONLY one core?

**Comment by tensor-tang** [comment]
翻译下方便理解：

> Intel MKL-DNN is built w/o Intel MKL, 编译MKLDNN的时候不使用MKL

a. 这种情况下，iomp要怎么处理。编译MKLDNN的时候需要链接iomp，那么如果paddle使用的时候链接3个lib（里面包含sequencelib）和iomp，会影响MKLDNN的使用吗？

b. 如果去掉MKLDNN里面的MKL，所有MKLDNN中使用gemm的地方都会受影响。由于int8的时候好像也有gemm的实现，所以也有影响。

> Somehow align how you build Intel MKL-DNN and PaddlePaddle. For example use libmkl_rt everywhere .

a. MKL_RT好像没有静态的。

b. 使用RT的时候，用控制thread的方式相比直接链接3个lib的方式，速度会有影响吗。

c. 如果用3个lib，然后用同样的版本编译MKLDNN，会导致MKLDNN使用问题吗，比如MKLDNN的FC会一直用单core了？或者甚至别的AVX的实现的时候也没发多线程。
