### ISSUE TITLE
A question about define_py_data_sources2

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#1263]
I noticed a not-well-used usage of `define_py_data_sources2` at [here](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/tests/configs/test_split_datasource.py#L6).  I am wondering what does the list typed `module=["a", "b"]` mean, as I am trying to simplify `define_py_data_sources2`.

**Comment by reyoung** [comment]
`define_py_data_sources2`'s argument could be a simple string or sequence(list|tuple) of string. When train data provider and test data provider shared the same module, the argument could be a simple string, which is data provider's module name. Otherwise, pass a sequence of module name, first of them is train module, second is test module.
