### ISSUE TITLE
Is there any way to use "Python Layer" in fluid 

### ISSUE THREAD

**Issue by xingyuanbu** [PaddlePaddle/Paddle#13255]
In caffe, caffe2 and tensorflow, one can define an operator with python, which named python layer in caffe, and py_func in tensorflow.
Is there any way to use python layer in fluid?

**Comment by chengduoZH** [comment]
Currently fluid doesn't support this feature, but we have a plan to support it.

**Comment by lucywsq** [comment]
Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
