### ISSUE TITLE
CentOS 6.0 Support

### ISSUE THREAD

**Issue by pwllr** [PaddlePaddle/Paddle#1370]
请问PaddlePaddle能不能在center os 6 上安装？？？有没有无sudo权限的安装文档

**Comment by pwllr** [comment]
请问PaddlePaddle能不能在CentOs 6 上安装？？？有没有无sudo权限的安装文档

**Comment by gangliao** [comment]
可以安装

**Comment by reyoung** [comment]
@pwllr Paddle官方目前没有计划维护CentOS的版本。即使维护CentOS版本，也不会维护CentOS 6版本。主要原因是，CentOS官方，已经停止[维护CentOS 6](https://zh.wikipedia.org/wiki/CentOS)系列的系统了。

如果想要在CentOS 6上部署Paddle，可以自己手工编译一下。需要处理的主要问题应该是如何安装依赖。
另外，如果觉得CentOS 6确实很老，并且确实没有管理员权限，可以使用[proot](https://proot-me.github.io/)，在用户目录里面使用ubuntu的rootfs。chroot进去然后安装Paddle。这样就可以和Ubuntu的安装方式一致了。

**Comment by reyoung** [comment]
Closed due to Paddle won't support CentOS 6 by RPM package or documentation because the CentOS 6 is unsupported by CentOS themselves now.

Paddle should work well on any Linux, Mac. 

The biggest problem is to install all dependencies to install Paddle on CentOS 6.

There is a wonderful project named [proot](https://proot-me.github.io/), that make user can do `chroot` not need root privilege. Users can chroot a ubuntu rootfs, and follow the ubuntu compile documentation.

Also, it is recommended to use Docker to resolve all dependency problems.
