### ISSUE TITLE
Multi-node training with All-Reduce for CPU

### ISSUE THREAD

**Issue by hshen14** [PaddlePaddle/Paddle#15054]
Hello,

I found current multi-node training provides the support for PS and NCCL. Especially, NCCL supports all-reduce in GPU. May I know whether there is a plan to support all-reduce for CPU? As we know, MPI-based or MLSL-based solution are alternative ways. Intel provides the mature solution based on MLSL and we can have a discussion and provide the necessary support in that direction. Thanks.

@Yancey1989 @helinwang @Superjomn @panyx0718

**Comment by Yancey0623** [comment]
Thanks, I think the collective mode on CPU is a necessary feature for the distributed training, 
We have a WIP PR in the earlier to supoprt MPI interface : https://github.com/PaddlePaddle/Paddle/pull/11992 , this feture has lower-priority because of the most of the CPU distributed training user-case is async-update, it can get better performance. 

And do you want to contribute the MLSL-based feature into PaddlePaddle, maybe we we can merge that into the [contrib](https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/contrib) ? 😄😄

@jacquesqiao @typhoonzero do you have any idea about that?

**Comment by hshen14** [comment]
Thanks @Yancey1989 for sharing. + multi-node training expert @delock

Probably, we may discuss and propose a high-level design regarding collective/all-reduce mode, since NCCL is there. We may need to make mode higher level instead of device specific. The better one in my mind:
* level 1: PS and All-reduce
* level 2: All-reduce: CPU (MLSL) / GPU (NCCL) 

Welcome any comments.

**Comment by delock** [comment]
PS is generally good for high variance environment and is useful for fault tolerance.   For communication efficiency, allreduce is usually better than PS.   Allreduce does not support Async SGD.  Can I know why Async update give better performance? @Yancey1989
