### ISSUE TITLE
Question for calibrator.sampling_program

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#15724]
https://github.com/PaddlePaddle/Paddle/blob/4c8feae43d226646397f812b945a4b5b07e5a6f9/python/paddle/fluid/contrib/tests/test_calibration.py#L242-L246
Could line244-246 put into `calibrator.sampling_program` to simplify the usage?

**Comment by luotao1** [comment]
@hshen14 Could you help see it?

**Comment by hshen14** [comment]
@luotao1 It is possible to move those code into utility.py. But please let me make more explanation so that you can better understand the background why we add such logic here:
1. We need to specify use_mkldnn attribute true to leverage MKL-DNN kernel. Like CAPI, there is an API to specify in predictor; the similar should happen in Python as well by exporting FLAGS_use_mkldnn=true first and run the python predictor. 
2. Actually, those lines are workaround to pass pre-ci test, and the end users can remove those lines with FLAGS_use_mkldnn=true. E.g., FLAGS_use_mkldnn=true python test_calibration.py

So, my suggestion is following:
1. Add comments and modify README
2. Hide the logic into utility

I would prefer the first option, since it could align the similar thing in CAPI predictor and the end users need to be aware of such flag. What do you think?

**Comment by luotao1** [comment]
> 2\. Actually, those lines are workaround to pass pre-ci test

If these lines are only used to pass ci, how about remove them, and modify the cmake like
https://github.com/PaddlePaddle/Paddle/blob/c794ecf641a575e92e2b55ad56b27c42e8b709f5/python/paddle/fluid/tests/unittests/CMakeLists.txt#L84
to set `FLAGS_use_mkldnn=true` in CI.

**Comment by hshen14** [comment]
> > 2. Actually, those lines are workaround to pass pre-ci test
> 
> If these lines are only used to pass ci, how about remove them, and modify the cmake like
> [Paddle/python/paddle/fluid/tests/unittests/CMakeLists.txt](https://github.com/PaddlePaddle/Paddle/blob/c794ecf641a575e92e2b55ad56b27c42e8b709f5/python/paddle/fluid/tests/unittests/CMakeLists.txt#L84)
> 
> Line 84 in [c794ecf](/PaddlePaddle/Paddle/commit/c794ecf641a575e92e2b55ad56b27c42e8b709f5)
> 
>  py_test_modules(test_warpctc_op MODULES test_warpctc_op ENVS FLAGS_warpctc_dir=${WARPCTC_LIB_DIR} SERIAL) 
> 
> to set `FLAGS_use_mkldnn=true` in CI.

Thanks @luotao1 for your suggestion. Is the change required for v1.3 release? If so, @guomingz can prepare a PR for it. Please note that we also need to update README as well to specify such flag. Is it right?

**Comment by luotao1** [comment]
> Is the change required for v1.3 release

It's better to patch the modify into v1.3. You should create two PRs, one for develop at first, after merge it, cherry-pick the commit into release/1.3.

> Please note that we also need to update README as well to specify such flag

Do you mean update the `4. How to reproduce the results` in README?

**Comment by hshen14** [comment]
> > Is the change required for v1.3 release
> 
> It's better to patch the modify into v1.3. You should create two PRs, one for develop at first, after merge it, cherry-pick the commit into release/1.3.
> 
> > Please note that we also need to update README as well to specify such flag
> 
> Do you mean update the `4. How to reproduce the results` in README?

Yes, add FLAGS_use_mkldnn=true before running python test_calibration.py.

**Comment by luotao1** [comment]
Note that if commit to `release/1.3`, the commit info should contain `test=release/1.3`.
