### ISSUE TITLE
Deadlink in doc

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#15935]
**To Reproduce**
There is a deadlink in the following document:
http://www.paddlepaddle.org/documentation/docs/zh/1.2/advanced_usage/development/contribute_to_paddle/local_dev_guide.html
Search for "使用Docker安装运行", and you will find a 404 page. The correct page (I guess) maybe this one:
https://github.com/PaddlePaddle/FluidDoc/blob/develop/doc/fluid/beginners_guide/install/install_Docker.md

**Comment by shanyi15** [comment]
hi, we have fixed in v1.3, please refer to here: 
http://www.paddlepaddle.org/documentation/docs/zh/1.3/advanced_usage/development/contribute_to_paddle/local_dev_guide.html
The search engine has some bugs now, will fix it, the correct link is:
http://www.paddlepaddle.org/documentation/docs/zh/1.3/beginners_guide/install/install_Docker.html

**Comment by shanyi15** [comment]
any doc problem please submit issue in FluidDoc
https://github.com/PaddlePaddle/FluidDoc

**Comment by houj04** [comment]
Thanks for the reply. BTW, the "官方中文文档" link on the front page of http://www.paddlepaddle.org/ leads me to v1.2 instead of v1.3.

**Comment by shanyi15** [comment]
could you screen shot the specific button? Thanks

**Comment by houj04** [comment]
Here it is.
![default](https://user-images.githubusercontent.com/35131887/53410798-c2d9ad00-39ff-11e9-8a6f-de6cf9ed2191.png)

**Comment by shanyi15** [comment]
got it, thanks very much! cc to @joodo

**Comment by joodo** [comment]
we made some changes on paddlepaddle.org, including remove the deadlink, and now it's more clear to find documentation. Thanks for feedback!
