### ISSUE TITLE
Missing bias for conv2d_transpose_op.cc

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#16019]
According to Paddle 1.3 [documentation]( http://www.paddlepaddle.org/documentation/docs/en/1.3/api/layers.html), conv2d_transpose should include bias. However Bias is not in conv2d_transpose_op.cc. Is it designed this way? But there is "Bias" in conv_op.

We wonder if we should delete the bias part in conv2d_transpose_mkldnn_op.cc as it influences the UT line coverage.

Thanks a lot !

**Comment by luotao1** [comment]
@chengduoZH @qingqing01 How do you think about `delete the bias part in conv2d_transpose_mkldnn_op.cc`?

**Comment by luotao1** [comment]
@lidanqing-intel @jczaja  
Discussed with @qingqing01, though bias is not in `conv_transpose_op.cc`, it is in API
http://paddlepaddle.org/documentation/docs/en/1.3/api/layers.html#conv2d-transpose
, which is implemented by `elementwise_add` op.

But whether to remain or delete `bias` of  `conv2d_transpose_op.cc` depends on your unifined implementation, since bias is not in `conv_op.cc`, but used in `conv_mkldnn_op.cc` as well.

**Comment by lidanqing-vv** [comment]
A PR has been sent #16030. AddAttr("Bias") is added in conv_transorform_op.cc and UT for fuse_bias is done in the test_conv2d_transpose_mkldnn_op.py

**Comment by lidanqing-vv** [comment]
I just want to test my comment date, it seems I have time zone difference
