### ISSUE TITLE
In-Place requirement for MKLDNN op.

### ISSUE THREAD

**Issue by xiaolil1** [PaddlePaddle/Paddle#16916]
We met in-place issue when enable MKLDNN Reshape OP. 
For the case: no-mkldnn op ---> mkldnn op ( Reshape or other in-place supported Ops).

We investigated this issue and found the "data transform" will generate new tensor and change the input tensor of Reshape Op, while the output not, which will break the in-place between input and output.

To solve this issue, we developed two solutions, and submitted two PRs. 
First one is #16914  , there will be overhead when "in-place" occurs.
Second one is #16915  , overhead only happens on "in-place" occurs in "data transform", but will add 5 parameters for "TransformData".
  
We have verified correctness of these two solutions and will send out performance result later.

**Comment by xiaolil1** [comment]
@luotao1 @tensor-tang @hshen14

**Comment by xiaolil1** [comment]
We have validated the performance for ResNet50 and MobileNetV1 with BS=1 and Cores=1.
The results show no performance impact with both of #16914 and #16915 .

**Comment by xiaolil1** [comment]
We prefer the first solution #16914, which will not change "TransformData" API.

**Comment by xiaolil1** [comment]
@luotao1 I have talked with @jianhang-liu about this issue. #16914 is the solution to fix this issue, and #16173 depends on it. Please help to review it, thanks! @tensor-tang @hshen14

**Comment by hshen14** [comment]
@jczaja @tensor-tang @luotao1 The PR (first solution) looks good to me.

**Comment by ghost** [comment]
@xiaolil1 Actually I'm not so confident whether it's a real issue. As you said, we had went though the code and discussed this for more than 1 hour. We both agreed that in place edit was already supported by existing code, i.e. all in-place-var will be [transfered back](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L941) by [forcing original tensor](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L1017) (in parent scope of transfer scope) to share data with transformed tensor (in transfer scope).
And exiting code assume that for a in-place edit OP (e.g. reshape), it should only operate on it's input tensor instead of output tensor.
With above code and assumption, I didn't see any issue to handle in-place edit here. Please point out what's the issue "really" blocking your UT.

**Comment by xiaolil1** [comment]
@jianhang-liu I think maybe you were not understand this issue actually, even I have illustrated it last week twice and answered this question already. I think maybe i didn't explained clearly, so let me do it again here. 
The "in-place-var will be transfered back" you said happened after OP execution.
For example "Reshape" OP, whose function is changing the dims of output tensor as well as input tensor when it's in-place. While after "data transform", input tensor will be changed to the new tenser, but output tensor still be the old one, so dims of input tensor will not be changed as output tensor change, which is needed by in-place. 
After "transfered back", dims of input tensor will transfer back to the output tensor, so not only input tensor dims can't get the dims generated by "Reshape Op", but also output tensor will loss the new dims.

**Comment by xiaolil1** [comment]
BTW, i think "in-place" of A and B should means A and B use the same memory buffer when OP execution, but "transfer back" A to B is more like a work around, which broke the in-place meaning, what do you think? @jianhang-liu

**Comment by ghost** [comment]
@xiaolil1 I believed I understood what's the "issue" you are worry about. Let me explain again.

Firstly, let me clarify two concepts here:
1. [Inputs()](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.h#L166) and [Outputs()](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.h#L167) in each OP are **VariableNameMap** which map "parameter" to "variable name". For example, inputs() of below Reshape OP will have one map: "X" <-> "fc_6.tmp_1"; outputs() will be two maps: "Out"<->"fc_6.tmp_1"; "Xshape" <-> "reshape2_4.tmp_0". Here we can see Reshape OP is a "in-place edit" OP since one of it's inputs "X" and one of it's outputs "Out" map to the same variable name "fc_6.tmp_1".
  ops {
    inputs {
      parameter: "X"
      arguments: "fc_6.tmp_1"
    }
    outputs {
      parameter: "Out"
      arguments: "fc_6.tmp_1"
    }
    outputs {
      parameter: "XShape"
      arguments: "reshape2_4.tmp_0"
    }
    type: "reshape2"

2. [inputs and outputs](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.h#L125) in RuntimeContext are **VariableValueMap** which map "parameter" to a "Variable" in scope(i.e. stack).

**VariableNameMap** is statically defined in OP but **VariableValueMap** is [dynamically setup](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L145) in RuntimeContext.

With same parameter (e.g. "X"), inputs("X) in OP will map to the variable name "fc_6.tmp_1" (i.e. string); but inputs("X") in RuntimeContext will map to the variable "fc_6.tmp_1" (i.e. instance of Variable class).

Now let's go through the call sequences when an OP (e.g. Reshape)  executed:

1. Enter [OperatorWithKernel::RunImpl(scope)](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L905) 
   "scope" is current "stack frame". At this time:

- inputs("X") in RuntimeContext point to Variable "fc_6.tmp_1" in current scope

- outputs("Out") in RuntimeContext point to same Variable "fc_6.tmp_1" in current scope


2. Call [PrepareData(scope, ..., &transfered_inplace_vars, runtime_ctx)](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L920)

- In your case, [NeedTransform()](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L1066) return true so pass through

- Since the input var name "fc_6.tmp_1" also exist in output vars, it (i.e. string "fc_6.tmp_1") will be [saved into transfered_inplace_vars](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L1076) for future transfer back.

- A [new sub scope will be created](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L1099) and a [new variable with same name "fc_6.tmp_1" will be created](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L1102) in this new scope (stack frame). This new scope is "**child**" scope of original scope.

- Change inputs("X") in RuntimeCxt[ pointing to the new variable](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L1103) "fc_6.tmp_1" in new scope (be noticed that there is also an old variable "fc_6.tmp_1" in parent scope).
At this time,
  *  inputs("X") in RuntimeContext point to Variable "fc_6.tmp_1" in **child** scope (i.e. new scope)
  *  outputs("Out") in RuntimeContext point to Variable "fc_6.tmp_1" in **parent** scope (i.e. original scope)

- [ Transform the data](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L1119) (i.e. tensor of variable "fc_6.tmp_1" in parent scope) and[ attach the transformed tensor ](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L1120)to  the varialbe "fc_6.tmp_1" in child scope (i.e. trans_var).

At this time:
  * Variable "fc_6.tmp_1" in **child** scope hold the "transformed" tensor
  *  Variable "fc_6.tmp_1" in **parent** scope hold the "before transform" tensor
3. When [PrepareData() return](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L920)
   * transfered_inplace_vars hold the in-place var name "fc_6.tmp_1"
   * transfer_scope is the new "child" scope which hold one new variable "fc_6.tmp_1"
   * In runtime_ctx, inputs("X") point to variable "fc_6.tmp_1" in "**child**" scope but outputs("Out") point to variable "fc_6.tmp_1" in "**parent**" scope
4. The child scope (i.e. [transfer_scope in code](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L924)) will be used when executing OP (i.e. this "in-place edit" Reshape OP) as "exec_scope"
5. [InferShape() ](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L931)with this child scope
  **Note:** outputs("Out") point to variable "fc_6.tmp_1" in **parent** scope. So when we set it's dimension in InferShape(), inputs("X) is NOT affected
6. [Execute the OP kernel](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L936) with this child scope 
  **Note:** As a "in-place" edit OP, in Compute() of "Reshape" kernel, you should **only modify inputs("X")** (i.e. what "in-place" edit mean). You should **NEVER modify outputs("Out")**.
7. Call [TransferInplaceVarsBack()](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L941)
   * [For each in-place var name](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L1006)(here only "fc_6.tmp_1")
   *    [Find the original varialble](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L1008) "fc_6.tmp_1" in parent scope which is pointed by outputs("Out")
   *    [Find the new variable](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L1013) "fc_6.tmp-1” in child scope which is pointed by inputs("X")
   *   Force the original variable (i.e. pointed by outputs("Out")) to [share the tensor](https://github.com/PaddlePaddle/Paddle/blob/8d0d6185ce3b3c7571b34316152ece5dd361f859/paddle/fluid/framework/operator.cc#L1017) from new variable (i.e. pointed by inputs("X"))
**_!!!! Bingo!_** Magic happen here. outputs("Out") now have both correct shape (set in InferShape) and correct data (shared with inputs("X") which had been computed in Compute())
   
This is the behavior in existing code  and **I didn't see any issue**. Could you point out what's wrong in above steps with your example? Thanks.

**Comment by xiaolil1** [comment]
@jianhang-liu Thanks for your detailed code analysis, it's perfect true for most steps except the step 6, i have different understanding from yours, and this step is also the key step for this issue, let me explain it.

Firstly, I think OP should save it's result to "output" by modifying it, not the "input". While for "in-place" OP, "input" will be passively modified, but the reverse is not a good design for an OP, what do you think?
For [Reshape OP](https://github.com/PaddlePaddle/Paddle/blob/1a4a51db2b8834d893cc011439e9f5367ec4f125/paddle/fluid/operators/reshape_op.cc#L227), it did as i said as well.

Secondly, to let one "in-place" OP modify its "input" as you said, this OP should know whether it is "in-place", that means all OPs (supported "in-place") should add "in-place" flag or other judgement rule to decide which one should be modified, that I think is more like a work around for solving this issue, and will bring much code modification to OPs, not only Reshape OP.

Thirdly, we can use #16914 to solve this issue, and we have verified it. While it will be welcomed if you have better solution to solve this issue.

**Comment by ghost** [comment]
Close without merge. Risk in solution.
