### ISSUE TITLE
remove cases for using "x_data_format" and "y_data_format" in test_elementwise_mul_mkldnn_op

### ISSUE THREAD

**Issue by LeoZhao-BJ** [PaddlePaddle/Paddle#16948]
As one of the following tasks for Issue #16764, raise issue to track changes for removing cases for using "x_data_format" and "y_data_format" in test_elementwise_mul_mkldnn_op.

**Comment by Sand3r-** [comment]
As I've mentioned in #16764 - removal of these attributes will make it impossible to test AVX512 code path, because currently there is no way of setting the data format of input Tensors in python. Hence, the AVX512 case would never get executed.

**Comment by luotao1** [comment]
How about use model level to test these codes, you can refer to `se_resnext50` in 
https://github.com/PaddlePaddle/Paddle/blob/de3b70a101dabd48e0659ddb4df4651b882aeafa/paddle/fluid/inference/api/demo_ci/run.sh#L47

**Comment by LeoZhao-BJ** [comment]
@Sand3r-  Let's sync offline and discuss a better solution to handle this case.

**Comment by Sand3r-** [comment]
After discussing the possible solutions with @LeoZhao-Intel the following solutions for testing the elementwise_mul without the attributes have been proposed:
#### 1. Making it possible to set data format in python tensor.
**Advantages:**
- Simple code
- Code path tested

**Disadvantages:**
- Interfering with python, c-api bindings
- Enabling user to possibly set incorrect data format for their data
- MKL-DNN will soon remove the possibility to freely set, get data formats, so this feature would soon have to be removed
#### 2. Putting a dummy mkldnn convolution layer before elementwise_mul. The convolution would perform a conversion of data from nchw to nchw16c and feed it to eltwise_mul so that it can execute the avx512 branch.
**Advantages:**
- Code path can be tested

**Disadvantages:**
- Hacky solution, hard to understand for those who don't know the internals of conv kernel and MKL-DNN
- Can fail if MKL-DNN format selection will change
#### 3. Implementing the tests for mkldnn elementwise_mul in C++.
**Advanatages:**
- Formats can be easily set through available interface.
- Reorders make the code cleaner and easier to read
- It's easier to detect CPU features (thorugh `platform::MayIUse` or direct xbyak solution), so that nchw16c can be tested on avx512 machines only and nchw8c on avx2 (once it will be implemented).

**Disadvantages:**
- Code for performing reference computations of elementwise multiplication needs to be handcrafted (i. e. goodness of numpy can no longer be benefited from)

Personally I believe that the third option is the safest and cleanest to implemented as of now.

**Comment by LeoZhao-BJ** [comment]
Thanks @Sand3r- for such detailed solutions, I agree with Michal's preference, third solution may be more suitable for this kind of mkldnn features, since we may not want users to know such kind of information in python level, it is better to do in C++ level.

@luotao1 @tensor-tang if you guys are not against Michal's solution, then he will start this work soon.

**Comment by luotao1** [comment]
@Sand3r- @LeoZhao-Intel 
Thanks very much for so detail three solutions!

> Code for performing reference computations of elementwise multiplication needs to be handcrafted 

Discussed with @tensor-tang, to make thing much simple and you can focus on more higher-priority things, we think that you can directly remove cases for using "x_data_format" and "y_data_format" in test_elementwise_mul_mkldnn_op, that is to say, don't need to add C++ tests.

**Comment by LeoZhao-BJ** [comment]
@luotao1 put more clarification here
1. We both agree to remove these 2 attrs usage from current test case, **even from C++ level** 
2. All new approaches do not use these attrs, and these attrs will be removed from op and kernel in the future, we agree that it is not reasonable for adding attrs just for test. 
3. It is still necessary to add test cases to verify mkldnn features in low level, e.g. nchw16c, nchw8c etc.
4. For current stage, we just need to simply remove cases from python.

Few confusion from your comment,  you mean adding tests for mkldnn features in C++ can be deferred due to other high-priority tasks, or it is unnecessary to add? I guess you mean first one.

**Comment by luotao1** [comment]
> you mean adding tests for mkldnn features in C++ can be deferred due to other high-priority tasks, or it is unnecessary to add? I guess you mean first one

Yes, we mean the first one. You can add C++ tests when you are convenient. Besides, hope the C++ tests could be as simple as better. @LeoZhao-Intel @Sand3r-

**Comment by LeoZhao-BJ** [comment]
OK, then we are all aligned. :)
