### ISSUE TITLE
distributed training: should we re-use etcd from k8s?

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#1807]
As mentioned in design doc https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/dist/README.md , we will use etcd v3 for fault resistance and coordination.

Should we re-use the Kubernetes' internal etcd?

Pro:
- It's already there, we don't need to create new pods for etcd.
- They are on every node, it's most reliable.

Con:
- Security reasons, as discussed here: https://www.reddit.com/r/kubernetes/comments/5w3wbc/should_i_reuse_kubernetes_etcd_for_my_own_service/
- etcd version control. Kubernetes switched to etcd v3 from v2 a while ago. There will be a problem if we want to deploy PaddlePaddle to a cluster running an old version of Kubernetes with etcd v2. Or in future Kubernetes may update it's etcd dependency to v4.

Further question:
- If we decided to go with re-using Kubernetes' internal etcd, are there any account namespace feature built into etcd? E.g, can all pods under Job-A can have its isolated namespace?

- If we decided to go with deploying our own etcd, are there any easy to use etcd as a service solution available? Does the service provide built-in account isolated namespace: each PaddlePaddle job needs a separated namespace.

**Comment by helinwang** [comment]
@xiang08 Could you take a look? Your feedback is very appreciated!

**Comment by xiang90** [comment]
No. let's not do this. you can setup a managed etcd very easily on k8s with etcd operator: https://github.com/coreos/etcd-operator

**Comment by typhoonzero** [comment]
Agree with separate these two. 

> Security reasons, as discussed here

There's still security problem that users can use pod to access kubernetes etcd endpoints directly. If we are not using [network policies](https://kubernetes.io/docs/concepts/services-networking/networkpolicies/)

**Comment by Yancey1989** [comment]
Agree with the security reason for the dis: https://www.reddit.com/r/kubernetes/comments/5w3wbc/should_i_reuse_kubernetes_etcd_for_my_own_service/ , 

How about using kubernetes client instead of reading etcd directly such as  [client-go](https://github.com/kubernetes/client-go), the SDK only request apiserver. For the security, we can use [ABAC](https://kubernetes.io/docs/admin/authorization/) or [RBAC](https://kubernetes.io/docs/admin/authorization/rbac/#service-account-permissions) to control some namespace can only request https GET.

And according this design doc: https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/dist/README.md ,it should write some other message can not fetch from kubernetes api, such as a sequence id for every pod.

So if we have some other design abount the sequence ID, kubernetes client is simple way to implement the service discovery of paddlepaddle.

**Comment by helinwang** [comment]
Thanks all! let's setup a managed etcd.
