### ISSUE TITLE
Cluster train task dispatching and task queues reconsideration

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#1833]
According to https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/dist/README.md#task-queue   we need to determine whether a task is finished or timeouted. The "Pending Queue" seems not suitable for this, because trainers may update the task status by `task-id`. A key-value store may be a good choice?

So we may only need two queues: TODO queue and Done queue, and another k-v store.

Below shows the master process pseudo code:

```python
for p in range(num_pass):
    put_all_task(todo_queue)
    while 1:
        finished, timeouts = check_task_stats()
        if finished:
            push(done_queue, finished)
        if timeouts:
            # FIXME: add slow node functions
            append(todo, timeouts)
        if task_all_done():
            break
        sleep(1)
```

If we start a redis instance(container) in the master pod when using kubernetes, and configure redis to use "AOF" to persistent every write(use distributed filesystem, mounted on the pod), we can use redis as both queue and k-v store. When master pod fails, restarts the master will restore redis data from "AOF" file to continue task dispatching.

Thanks for @Yancey1989 discussed with me with these thoughts.

**Comment by helinwang** [comment]
Agree, a kv-store is better for pending queue implementation than using a queue. (But conceptually it's easier to refer it as a "pending queue" than refer it as a "pending kv-store"?
For kv-store, since we are using etcd to save queue state for fault tolerance, can we use etcd for the k-v store of pending queue? Redis may have a friendly API for queue and kv-store than etcd. Since it's not much code, can we stick to ectd to avoid adding dependency?

I would suggest master don't need to manage the lifecycle of trainers (don't kill pods). Straggler management complicated subject, maybe we can defer it for the future when the problem rise up?

**Comment by typhoonzero** [comment]
Close this. We have discussed through and all agreed.
