### ISSUE TITLE
Training on 2 GPUs is slower than on 1 GPU

### ISSUE THREAD

**Issue by hanwentao** [PaddlePaddle/Paddle#1846]
The training of the following code is slower on 2 GPUs than on 1 GPU.  This is a dummy autoencoder.  It lasts about 4 seconds for one iteration for input size 500k (i.e., 500,000 vectors of size 213) on 1 GPU, and lasts about 5 seconds on 2 GPUs.

https://gist.github.com/hanwentao/c7fc71350204b835fd3c4e55bc6b934f

**Comment by hedaoyuan** [comment]
Through trainer_count arguments set up multi-GPU training, is a data parallel training process. In the multi-GPU data parallel training, will increase the additional overhead of synchronization parameters(After each mini-batch is finished, the parameters in multiple GPUs need to be synchronized.). So, if the parameters are large, or the bandwidth between the GPU is very small, will lead to the above phenomenon.
In general, the whole FC model, do not recommend using multi-GPU data parallel training, because the FC model is relatively large. 
In your case, if you feel that the performance of the calculation is insufficient, you can increase the batch_size try. Also, what is the GPU and CUDA version of your system?

**Comment by hanwentao** [comment]
Tesla P100
CUDA 8.0
cuDNN 5.1

I'm trying batch_size

**Comment by heiyexingchen** [comment]
@hanwentao 
Hi,I would like to ask you what method is used to build GPU training environment?

**Comment by hanwentao** [comment]
2 P100 are inserted on a server via PCIe slots.  Did I hit your mark?

**Comment by heiyexingchen** [comment]
@hanwentao
Will you use the docker, nvidia-docker or source compiler, because I also want to use GPU training, but do not know how to do it. In accordance with the online tutorial is always a problem, so I hope you can give me some suggestions

**Comment by hanwentao** [comment]
@heiyexingchen I compiled from the source code, the default develop branch.  You should install CUDA and cuDNN (I tried the versions listed above), and leave other dependencies to PaddlePaddle's cmake system.  It can download most of the dependencies via network.

**Comment by hanwentao** [comment]
@hedaoyuan I increase the batch size from 128 to 4096.  Now 1 GPU and 2 GPUs perform the same ;-(

**Comment by helinwang** [comment]
@hanwentao By same, do you mean the same amount of time per mini-batch (twice amount of data I suppose?) or the same amount of time per the same amount of data?
It makes sense if it's the first case, since the throughput doubled.

**Comment by hanwentao** [comment]
@helinwang I meant latter ;-(
