### ISSUE TITLE
QAT&INT8 performance improvement

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#18893]
Currently we have two new QAT trained models of ResNet50 (from Baidu) at our disposal:
I.	with conv2d and mul’s weigths in FP32 full range (Model1),
II.	with conv2d and mul’s weights in FP32 but (fake) quantized (Model2).
Model2 has the advantage that it can be used directly in inference (fake INT8).
Model1 cannot be used directly, it has to be modified first (either weights have to be fake-quantized resulting in fake INT8 model, or fake quantize/dequantize ops have to be removed resulting in full FP32 inference model).

Our general approach to getting an optimized INT8 model in both cases is as follows:
1.	gather scale values from fake quantize/dequantize operators,
2.	extract FP32 inference model from the QAT model, i.e.
a.	remove fake quantize/dequantize operators,
b.	dequantize conv2d and mul’s weights, if needed,
3.	optimize the FP32 inference model using standard fusing passes (e.g. conv2d+bn, conv2d+relu, …),
4.	quantize the optimized FP32 model using standard INT8v2 quantization passes (cpu_quantize_pass, cpu_quantize_squash_pass).

Initially, we started work with Model1, finished implementing all but the last step. That is, from Model1 we got fully optimized FP32 inference model (we verified that accuracy is preserved at this point) which is ready to be quantized. Only step 4. remained to be implemented and applied.
After switching to Model2, the steps 2.b and step 4. remains to be implemented and applied.

In case the step 2.b for Model2 was too difficult to perform preserving the accuracy, we would recommend continuing work on Model1.

We expect the whole procedure will be working next week (WW31).

**Comment by wojtuss** [comment]
The following table collects TOP1 accuracy values (on SKX) for the two models:

  | Original* | After steps 1-3 | After steps 1-4
-- | -- | -- | --
Model1 | 0.7612 | 0.7612 | -
Model2 | 0.7635 | 0.7638 | 0.7614

As Model1 cannot be used directly, the 'Original' accuracy is measured after removing all fake quantize/dequantize operators.

**Comment by bingyanghuang** [comment]
@luotao1 @wzzju Here is our plan for QAT and the latest status.

**Comment by wojtuss** [comment]
@luotao1 @wzzju
We applied the quantization passes to the FP32 inference model obtained from the Model2 and achieved top1 accuracy of 0.7614 (on SKX). I have updated the table above.
Performance to be measured very soon.
After grooming the code we will submit a PR.

**Comment by wojtuss** [comment]
@luotao1 @wzzju @bingyanghuang 
A preliminary PR is submitted: https://github.com/PaddlePaddle/Paddle/pull/18970

**Comment by Sand3r-** [comment]
Currently, the QAT accuracy measures carried out on CLX report a mismatch between fp32 and int8 top5 accuracy (difference of around 10%). This issue is right now investigated. Top1 Accuracy stays well within the margin error.

**Comment by Sand3r-** [comment]
Update as of 09.08.2018
Investigation of 10% top5 accuracy loss.
* Scale of output of Pooling 2D:
   * It has been detected that the output uses scale provided by the scale collector. That behaviour is incorrect, as output pool2d scale should be equal to input pooling scale.
   * This problem has been addressed and fixed.
   * Unfortunately, it did not decrease the top5 accuracy difference between fp32 and int8
* Checking whether fuse passes decrease the accuracy:
   * In order to investigate whether the fuses (and if so, what fuses) contribute to the accuracy loss, we'll test the accuracy with different pass configurations. As with current system it cannot be done right away, we will need to adjust the graph modification mechanism to correctly dequantize conv outputs (either by approximating conv output scales or by setting `force_fp32_output` parameters in all convolution ops).

@bingyanghuang will continue the work on QAT during the timespan of the next week.

**Comment by bingyanghuang** [comment]
Top 5 accuracy loss root cause is when removing the `fake_quant/dequant` op, wojtek forgot to dequantize `mul` op's weights to FP32 which caused top5 accuracy drop a lot. After fixing it by calculating the `mul` FP32 weights and `mul` remains not quantized in the final int8 model, got the following results (OMP_NUM_THREADS=20):
```2019-08-13 11:34:42,391-INFO: --- Performance summary ---
2019-08-13 11:34:42,391-INFO: FP32: avg fps: 20.54, avg latency: 48.7610 ms
2019-08-13 11:34:42,391-INFO: INT8: avg fps: 673.60, avg latency: 1.4944 ms
2019-08-13 11:34:42,391-INFO: --- Accuracy summary ---
2019-08-13 11:34:42,391-INFO: Accepted top1 accuracy drop threshold: 0.001. (condition: (FP32_top1_acc - IN8_top1_acc) <= threshold)
2019-08-13 11:34:42,391-INFO: FP32: avg top1 accuracy: 0.7657, avg top5 accuracy: 0.9299
2019-08-13 11:34:42,391-INFO: INT8: avg top1 accuracy: 0.7638, avg top5 accuracy: 0.9297
```
Now for top1 and top5, there is still the minor accuracy drop need to fix. Next step:

- Don't remove the `fake_op` before mul op until fc mkl-dnn int8 kernel ready
- Current solution quantize the output after `relu` with **u8** but QAT scales are all calculated by **s8**, will fix this unmatched behavior

**Comment by wojtuss** [comment]
Keeping the mul op fake-quantized did not improve the accuracy. With fake-quantized mul as well as with FP32 mul the accuracy result is still:
```
INT8: avg top1 accuracy: 0.7638, avg top5 accuracy: 0.9297
```

**Comment by wojtuss** [comment]
Keeping all int8 tensors as s8 did not improve the accuracy, it became a little bit worse instead:
```
INT8: avg top1 accuracy: 0.7635, avg top5 accuracy: 0.9298
```

**Comment by wojtuss** [comment]
Skipping quantization of average pooling improved the ResNet50 accuracy a little bit:
```
INT8: avg top1 accuracy: 0.7641, avg top5 accuracy: 0.9299
```
Diff to FP32 is 0.0016.

**Comment by wojtuss** [comment]
After the fix for pooling quantization, these are the accuracy results for VGG16, MobileNetV1 and MobileNetV2. 
VGG16:
```
FP32: avg top1 accuracy: 0.6972, avg top5 accuracy: 0.8948
INT8: avg top1 accuracy: 0.6967, avg top5 accuracy: 0.8947
diff: top1 0.0005, top5 0.0001
```
MobileNetV1:
```
FP32: avg top1 accuracy: 0.7026, avg top5 accuracy: 0.8940
INT8: avg top1 accuracy: 0.7009, avg top5 accuracy: 0.8925
diff: top1 0.0017, top5 0.0015
```
MobileNetV2:
```
FP32: avg top1 accuracy: 0.7081, avg top5 accuracy: 0.8993
INT8: avg top1 accuracy: 0.7071, avg top5 accuracy: 0.8989
diff: top1 0.001, top5 0.0004
```
The code in the PR will be updated very soon.

**Comment by Sand3r-** [comment]
As of #17819 #18970 and upcoming #21074 the performance and accuracy issues have been resolved.
