### ISSUE TITLE
Ernie-large模型MKLDNN库报错

### ISSUE THREAD

**Issue by GaoWei8** [PaddlePaddle/Paddle#20842]
- PaddlePaddle版本：develop
commit id：
![屏幕快照 2019-10-28 16 10 23](https://user-images.githubusercontent.com/53294385/67661993-7c2cc000-f99d-11e9-8c0c-d81c9428e69a.png)

- CPU型号: Intel(R) Xeon(R) Gold 6148 CPU

-  使用Docker镜像：hub.baidubce.com/paddlepaddle/paddle:latest-dev

- 模型信息
[模型：Ernie-large](https://github.com/PaddlePaddle/ERNIE)

- 错误信息：
打开MKLDNN库，报错。
关掉MKLDNN库，错误消失。

- 错误详细信息：
<img width="698" alt="70ecb5ee1c2a3b8ce1edb3798508143e" src="https://user-images.githubusercontent.com/53294385/67647277-ac0f9f80-f96c-11e9-87ff-270357d54c66.png">

 复现步骤：

/benchmark/Inference/c++/ernie/路径下：
mkdir build
cd build
cmake -DUSE_GPU=OFF -DPADDLE_ROOT=XXX ..
make

**Comment by luotao1** [comment]
1. 1.6版本MKLDNN还会出同样问题么？
2. MKL版本会报错么？

**Comment by GaoWei8** [comment]
1. 已用最新develop分支，commit ID已更新
2. MKL版本不会报错。

**Comment by lidanqing-vv** [comment]
@GaoWei8 Hi! I confirmed that it is because elementwise_mul_op.cc did not support 3 -dimension format `ncw`. 
I add this 3-dimension support and drop to naive version. After that, the performance with bs_test_10 can run successfully but slow. Do you have any reference performance? 
As it is slow, we are considering not dropping to naive version but:
1.  use MKL-DNN binary primitive
2.  if that does not work, properly will be jit.

Please if possible provide reference latency ( or performance). Thank you! 

> > I confirmed that it is because elementwise_mul_op.cc did not support 3 -dimension format ncw.
> 
> Is `elementwise_mul_op.cc` or `elementwise_mul_mkldnn_op.cc`?
> 
> > As it is slow, we are considering not dropping to naive version but:
> 
> Maybe you could add this 3-dimension support for mkldnn at first.

Sorry `elementwise_mul_mkldnn_op.cc` did not support 3-dimension format. In the https://github.com/PaddlePaddle/Paddle/pull/20965 I drop to naive version. We are also working on mkldnn support now.

**Comment by GaoWei8** [comment]
@lidanqing-intel 
Hi, In general, we don’t want performance degradation.
We only have the performance with closing mkldnn.
What is the setting getting performance  (1000 ms/sample)? Is mkldnn open and what is the thread number?

**Comment by luotao1** [comment]
> I confirmed that it is because elementwise_mul_op.cc did not support 3 -dimension format ncw.

Is `elementwise_mul_op.cc` or `elementwise_mul_mkldnn_op.cc`?

> As it is slow, we are considering not dropping to naive version but:

Maybe you could add this 3-dimension support for mkldnn at first.

**Comment by lidanqing-intel** [comment]
Sorry  1000 is my own i9 machine. I forgot to switch.on 6148, it is 600 ms/sample
