### ISSUE TITLE
Add lookahead row convolution layer.

### ISSUE THREAD

**Issue by xinghai-sun** [PaddlePaddle/Paddle#2228]
- Add lookahead row convolution layer, for both cpu and gpu version.
- Details please find in [DS2 paper](https://arxiv.org/abs/1512.02595).
- Please add a design-doc [here](https://github.com/xinghai-sun/Paddle/tree/ds2_design_doc/doc/design/speech#row-convolution) first.

**Comment by qingqing01** [comment]
Bidirectional RNN models are challenging to deploy in an online, low-latency setting, because they are built to operate on an entire sample. This row convolution layer is used to build a unidirectional model containing forward-only RNN layers without any loss in accuracy. This layer can use a future context of `T` steps. It is beneficial for deployment system. The details can be referred to the papers.

## Difference with `sequence_conv` in PaddlePaddle.

In the PaddlePaddle, we can use `paddle.layers.context_projection` and `paddle.layers.fc` to do sequence convolution, which is 1D convolution. Figure 2 shows this connection. Assumed that the context length( or the filter size) of convolution kernel is 3, and the hidden size of each time step is `d` for both the input and output feature of this operation. Thus, the weight dimension is `3d x d`. And the weights are shared among all-time step. 
<img width="576" alt="text_conv" src="https://cloud.githubusercontent.com/assets/7845005/26433066/db9a1252-4132-11e7-8528-1de626a4efa5.png">

Different from the sequence convolution, the convolution operation is row oriented for both weight(`W`) and hidden state(`h`). This connection is as shown in Figure 3. The weight dimension is `3 x d`. And the weights are shared among all-time step.

<img width="555" alt="row_conv_op" src="https://cloud.githubusercontent.com/assets/7845005/26433073/f12ef916-4132-11e7-816e-d8c2d190d2e2.png">

## How to deal with boundary.

Assumed that the context length( or the filter size) of convolution kernel is `k`. The paper did not mention that how to do the lookahead convolution for last `k-1` time steps.  I think we can pad `k-1` row zeros at the last time step for the input feature.

**Comment by xinghai-sun** [comment]
Great doc! @qingqing01  Could you please add this part to the [DS2 design doc](https://github.com/PaddlePaddle/Paddle/tree/develop/doc/design/speech) ? Thanks!

**Comment by qingqing01** [comment]
@xinghai-sun ok. I'll do it.
