### ISSUE TITLE
slim.quant.quant_aware TypeError: __init__() got an unexpected keyword argument 'quantizable_op_type'

### ISSUE THREAD

**Issue by githubtianya** [PaddlePaddle/Paddle#22731]
paddlepaddle:1.6.3
paddleslim:0.1.0
cpu
windows
when i do training quantization using official sample code, the error occured.
error:
Traceback (most recent call last):
  File "D:/project/paddleslim/mninst_train.py", line 43, in <module>
    quant_program = slim.quant.quant_aware(train_program, exe.place, for_test=False)
  File "D:\install\python3.7\lib\site-packages\paddleslim\quant\quanter.py", line 146, in quant_aware
    skip_pattern=config['not_quant_pattern'])
TypeError: __init__() got an unexpected keyword argument 'quantizable_op_type'

**Comment by slf12** [comment]
> paddlepaddle:1.6.3
> paddleslim:0.1.0
> cpu
> windows
> when i do training quantization using official sample code, the error occured.
> error:
> Traceback (most recent call last):
> File "D:/project/paddleslim/mninst_train.py", line 43, in
> quant_program = slim.quant.quant_aware(train_program, exe.place, for_test=False)
> File "D:\install\python3.7\lib\site-packages\paddleslim\quant\quanter.py", line 146, in quant_aware
> skip_pattern=config['not_quant_pattern'])
> TypeError: **init**() got an unexpected keyword argument 'quantizable_op_type'

Quantization in PaddleSlim depends on Paddle 1.7, because source code in Paddle related to Quantization has some modifications. We have released Paddle 1.7 https://pypi.org/project/paddlepaddle/1.7.0/#files.

If you want use 1.6.3, source code about quantization : https://github.com/PaddlePaddle/Paddle/blob/v1.6.3/python/paddle/fluid/contrib/slim/quantization/quantization_pass.py#L59.  You can edit passed parameters in quanter.py in paddleslim according to link above.
