### ISSUE TITLE
New models failed in save_qat_models.py

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#23034]
1. New image classification model failed on saving QAT model using save_qat_models.py
2. Improve the README.md and give more detailed description on the process of transforming QAT models to INT8 models

**System information**
-PaddlePaddle version: develop branch or release/1.7
-CPU: Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
-OS Platform: CentOS Linux 7 (Core)
-Python version: python 2.7
-Cmake orders
-C++version.txt
-API information

**To Reproduce**
Steps to reproduce the behavior
`python python/paddle/fluid/contrib/slim/tests/save_qat_model.py --qat_model_path=/home/wojtek/danqing_models/model_post_quant_cpu/resnet/model_resnet_200000_pruned_220000_quant_infer_2_new --int8_model_save_path=$HOME/danqing_models/model_resnet_200000_pruned_220000_quant_infer_2_new_qat_int8 --quantized_ops="conv2d"`

**Results:**
![image](https://user-images.githubusercontent.com/47151829/76747604-b4307600-6779-11ea-8221-b5f9b3d3ff14.png)

**Comment by wojtuss** [comment]
The model used here looks like suitable for the QAT1.0 only. It cannot be used with QAT2.0 (and the `save_qat_model.py` script) because there are important `fake_quantize_dequantize_*` operators missing in it. To see the difference, please compare the two ResNet50 models downloaded during building PaddlePaddle with tests:
QAT1.0: `build/third_party/inference_demo/qat/ResNet50_QAT/model/`
QAT2.0: `build/third_party/inference_demo/qat/ResNet50_qat_perf/ResNet50_qat_perf/float/`

Another thing is that PaddlePaddle should not crash on that. We will fix that very soon.

**Comment by lidanqing-vv** [comment]
I think we need `fake_quantize_dequantize_moving_average_abs_max` before `elementwise_add` and before `pool2d`. I guess `AddQuantDequantPass` is missing in the script transforming normal model to QAT model.
Could you share the script that you use to generate QAT models? @juncaipeng

**Comment by juncaipeng** [comment]
We only quantize conv2d, depthwise_conv2d and mul. Is it necessary to add fake_quantize_dequantize_moving_average_abs_max for elementwise_add and pool2d?

**Comment by wojtuss** [comment]
@juncaipeng , @lidanqing-intel 
In ResNet50, `pool2d` (with max pooling) and `elementwise_add` do not need `fake_quantize_dequantize_*` ops, because `pool2d` does not change the scale and `elementwise_add` is being fused with `conv2d` before quantization.

**Comment by wojtuss** [comment]
The crash was caused by control variables present in the model (probably unintentionally kept in the model when saving QAT model from a training model). The pass `conv_bn_fuse_pass` was crashing when it tried to use the control variables. The PR https://github.com/PaddlePaddle/Paddle/pull/23119 fixes the QAT2.0 procedure for such cases.

**Comment by wojtuss** [comment]
The PR https://github.com/PaddlePaddle/Paddle/pull/23202 fixes missing `fuse_activation` attribute issue for QAT2.0 with older QAT models.

**Comment by wojtuss** [comment]
The PR https://github.com/PaddlePaddle/Paddle/pull/23361 contains an update to the QAT INT8 MKL-DNN documentation.

**Comment by lidanqing-vv** [comment]
@juncaipeng  Can we close this issue?

**Comment by lidanqing-vv** [comment]
We will wait validation team to go through the whole document #23361 , reproduce and achieve expected accuracy, then we will close this issue.

**Comment by lidanqing-vv** [comment]
The new models failure problem is solved.  #23361 document improvement is ongoing, but not related to this issue
