### ISSUE TITLE
PaddleSlim and Paddle inference (Intel cpu) support all common quantized models

### ISSUE THREAD

**Issue by juncaipeng** [PaddlePaddle/Paddle#23346]
We usually use PaddleSlim to quantize a FP32 model to INT8 model, and run the int8 model in inference stage. 

However, there are some problems between PaddleSlim and Paddle inference (Intel cpu):
* Some quantized model  do not provide the needed output scale for Paddle inference (Intel cpu).  In details,  the quantized model only contains the input scale of some ops (conv2d, depthwise_conv2d, mul, elementwise_add, pool2d and so on), but supported quantized ops (conv2d, depthwise_conv2d, mul ) also need the output scale. If a quantized op does not have output scale obtained from input scale in the next op, it will raise an error.
* Paddle inference (Intel cpu) do not support `fake_channel_wise_dequantize_max_abs` op.

Therefore, PaddleSlim will provide the output threshold for some ops, and save it in the op's attributes. 

In inference stage, we can look up all ops and gather the output thresholds, and then transform it to output scale for quantized op.

@lidanqing-intel

**Comment by lidanqing-vv** [comment]
@wojtuss

**Comment by wojtuss** [comment]
@juncaipeng , 
We like the idea of having an output quantization scale in operator's attribute. If all the quantized operators have the output scale in their attributes, it would simplify the scales gathering from the QAT model. Until now, we usually require the `fake_quantize_dequantize` op to be present after the quantized op for the output quantization scale to be collected.
However, not only the quantized operators would require the attribute with the quantization scale. For example, if the sequence `... → input1 → conv2d → output1 → batch_norm → output2 → relu → output3 → ...` is present in the model and `conv2d` is to be quantized, then the quantization scale have to be gathered also for the `output3` tensor because quantization is applied after FP32 optimization passes (after the `conv2d_bn_fuse_pass` and `conv2d_activation_mkldnn_fuse_pass` passes in particular) when `batch_norm` and `relu` ops are fused with `conv2d`.
Nonetheless, this approach would simplify the whole QAT->INT8 transformation.

Regarding the support for `fake_channel_wise_dequantize_max_abs`, we can add it to Paddle. To start working on it we need an already prepared model for testing. Could you please provide us with it?

**Comment by lidanqing-vv** [comment]
Hi, @wojtuss I put the model on the jira task and I sent the link to you on MSTeams.

**Comment by juncaipeng** [comment]
@wojtuss   @lidanqing-intel 
We will collect the output scale for all quantized ops and the fused ops. 
To sum up:
* For quantized ops (conv2d, depthwise_conv2d, mul, matmul) that have weights, fake_quant and fake_dequant ops  provide the input scale. 
* For quantized ops (pool2d, reshape2) that do not have weights,  fake_quant_dequant op provide the input scale.  
* All quantized ops the output scale from the their attribute. However, if  the op (B) after quantized op (A) is also quantized, the input scale of B maybe a little different from the output scale in A's attribute. For this case, we have to test the model accuracy  and decide which scale to use.

**Comment by lidanqing-vv** [comment]
close this because PR merged
