### ISSUE TITLE
Do we need Grpc for master and trainer communicate?

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#2364]
@helinwang metions that master needs to provide callback. As a result, he take Grpc into account for rpc library selecting.
https://github.com/PaddlePaddle/Paddle/pull/2363 
here are my thoughts on master and trainer communicating process.  It is not a whole design doc, just the part of communication.
In my mind, the trainer, master, pserver role can be written in go, and use go native rpc for communacting. The computation in paddle framework can be done in the optimizer library, which is written in c++. The topology defines part can be any glue language such as python, perl and so on.

**Comment by helinwang** [comment]
This is a very good issue, we need more discussion in this area:

- what RPC to use.
- Does Jupiter notebook Python directly talk to the master, or Python talk to Go and GO talks the master.
- Do we need the callback? Or maybe we can just use Tensorboard?

I think it's a very good idea to bring this up. Maybe we can think about it while put most of the focus on our current work. Because this is still quite far (perhaps the last item we need to do for v1, and no other item is blocked by this one).

**Comment by helinwang** [comment]
We are using go's net/rpc due to the simplicity.
