### ISSUE TITLE
[DNNL] Extend elementwise_add kernel to support broadcasting

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#23927]
PaddlePaddle elementwise_add op supports broadcasting of input. DNNL binary primitive also supports
broadcasting. This task is to enable broadcasting of DNNL elementwise_add kernel

**Comment by lidanqing-vv** [comment]
This issue is an extention to PR #23477, now PR #23477 support only when X and Y has same shape inplace . But we can also support broadcast elementwise_add. 
All issues labeled with `interestingidea` are the functions we can do. But because Baidu may have different business request and priority, not sure when we will put this issue in high priority.

**Comment by jczaja** [comment]
merged
