### ISSUE TITLE
[Paddle-TRT] FP16 with cublasGemmStridedBatchedEx

### ISSUE THREAD

**Issue by zlsh80826** [PaddlePaddle/Paddle#24964]
-PaddlePaddle version: develop
-GPU: including CUDA/CUDNN version
-OS Platform Ubuntu 16.04

**Describe the feature and the current behavior/state.**
The implementation in [blas_impl.cu.h](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/math/blas_impl.cu.h#L430) doesn't use the ``cublasGemmStridedBatchedEx`` when the data type is fp16, even the ``CUDA_VERSION`` is greater than 9010. ``cublasGemmStridedBatchedEx`` has more capability like selecting the algorithm ([reference](https://docs.nvidia.com/cuda/cublas/index.html#cublas-GemmStridedBatchedEx)), it also performs better performance. We should use it when available, i.e., ``CUDA_VERSION >= 9010``.

So the code should be like this:
```
#if CUDA_VERSION >= 9010
  cublasGemmAlgo_t algo = CUBLAS_GEMM_DFALT;
  bool use_tensor_op_math = context_.tensor_core_available();
  if (FLAGS_enable_cublas_tensor_op_math && use_tensor_op_math) {
    algo = CUBLAS_GEMM_DFALT_TENSOR_OP;
  }
  VLOG(5) << "use_tensor_op_math: "
          << (use_tensor_op_math ? "True" : "False");

  auto fp = std::is_same<T, float>::value ? CUDA_R_32F : CUDA_R_16F;

  context_.TensorCoreCublasCallIfAvailable([&](cublasHandle_t handle) {
    PADDLE_ENFORCE_CUDA_SUCCESS(platform::dynload::cublasGemmStridedBatchedEx(
        handle, cuTransB, cuTransA, N, M, K, &alpha, B, fp, ldb,
        strideB, A, fp, lda, strideA, &beta, C, fp, ldc,
        strideC, batchCount, fp, algo));
  });
#else   // CUDA_VERSION < 9010
  context_.CublasCall([&](cublasHandle_t handle) {
    CUBlas<T>::GEMM_STRIDED_BATCH(handle, cuTransB, cuTransA, N, M, K, &alpha,
                                  B, ldb, strideB, A, lda, strideA, &beta, C,
                                  ldc, strideC, batchCount);
  });
#endif  // CUDA_VERSION >= 9010

```

**Comment by heavengate** [comment]
多谢您的反馈，我们评估并修改一下这个~

**Comment by jeng1220** [comment]
@heavengate, @AIpioneer , @lanxianghit and @NHZlX 
This is NVIDIA and @zlsh80826 is a NVIDIA engineer too. We are helping to improve ERNIE and BERT inference performance.

We are working on performance tuning for `algo` parameter. In our experiment, selecting a appropriate `algo` for small GEMM shape(i.e. MNK) instead of `CUBLAS_GEMM_DFALT` or `CUBLAS_GEMM_DFALT_TENSOR_OP` can achieve 6X ~ 12X speedup on CUDA core, and 1.4X ~ 3X speedup on Tensor Core in ERINE and BERT benchmark on Tesla T4 GPU. That is a huge performance gain.

Thus, we need to fix `cublasGemmStridedBatchedEx` usage first, then we can submit the patch regarding performance tuning.

**Comment by jeng1220** [comment]
Also, we found that the default value of flag `FLAGS_enable_cublas_tensor_op_math` is `False`. I think most of users are not aware that they have to set it manually to enable Tensor Core. Now the Tensor Core is a very common hardware in GPU. In order to fully utilize GPU and more convenient to user, I suggest to set default value to `True`
