### ISSUE TITLE
Remove CUDA code from dim.h

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#2510]
It seems that `caffe2::TensorShape` and other tensor shape constraints are not supposed to be used in CUDA kernels. Does this mean that we can remove the CUDA code generation macros from dim.h?

**Comment by Canpio** [comment]
`dim` serve not only as tensor shape but also as element index. In the second case, It may be used in our hand-written CUDA kernels.
Actually, it costs few to implement CUDA supporting in `dim`, only a few macros and function prefixes. So I tend to keep them for now. If they are turned out to be unnecessary in the future, removing them will also be an easy task.
