### ISSUE TITLE
Trainer save model in distributed training.

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#2512]

**Comment by helinwang** [comment]
Hi @jacquesqiao , please refer to this design doc for more information: [checkpointing ](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/cluster_train/checkpointing.md)

Please note that this design doc is about checkpointing, but this issue is about save model.

The main differences are:
1. checkpointing save additional states, such as optimizer state.
1. checkpointing don't involve merge checkpoint files from different Pservers into a same file. But save model need to merge them into a same file. Since merging is involved, some kind of synchronization is needed.

We can discuss the synchronization ideas, here is my initial idea: maybe Pserver #0 can be the one who performs the merge process. And Pserver #0 will watch etcd notification, to know that saving model finished on other Pservers.

Feel free to split this issue to different smaller issues, so that the size of each PR can be small.

**Comment by helinwang** [comment]
Also please see this discussion for reference: https://github.com/PaddlePaddle/Paddle/pull/1620#discussion_r110808150

**Comment by dzhwinter** [comment]
get it, thanks for the clear explanation! @helinwang

**Comment by Yancey1989** [comment]
Following this discuss #2638 , It seems that we declining to save model on the trainer, so maybe we can close this issue?

**Comment by helinwang** [comment]
> Following this discuss #2638 , It seems that we declining to save model on the trainer, so maybe we can close this issue?

@Yancey1989 Thanks! I have changed the title to `Trainer save model in distributed training.`.
