### ISSUE TITLE
How to do the unit test with etcd as backend server

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#2543]
Most of the codes of https://github.com/PaddlePaddle/Paddle/projects/18 are related with etcd server.But how to do the unit test with these codes? Maybe we can start up a etcd server when we execute `make test`, but it's too hackly... Does anyone have a good idea?

**Comment by typhoonzero** [comment]
Testing distributed systems is difficult, here's etcd's method: Testing “distributed” is difficult. 

In our situation, we need to define a bunch of distributed test cases like: when multiple pservers start all at the same time to register themselves on etcd, and ensure that the won't use the same node due to transaction problems. And running this test for only one time may not trigger the background bugs hidden inside. Running 100 times may not too. I've listed some test cases for distributed pserver:

1. start number of pservers exactly of defined in `/ps_desired`, try to start them at the same time, then check the etcd nodes under `/ps` are of correct number of `/ps_desired`
1. start number of pservers more than which is defined in `/ps_desired` and check nodes under `/ps` not exceeding `/ps_desired`
1. check node registerd under `/ps` are accessable.
