### ISSUE TITLE
MNIST examples in DyGraph mode

### ISSUE THREAD

**Issue by arlesniak** [PaddlePaddle/Paddle#25510]
When analyzing DyGraph mode we found 2 examples of the same model for MNIST:
PP repo [test_imperative_mnist.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_imperative_mnist.py)
Models repo [mnist/train.py](https://github.com/PaddlePaddle/models/blob/develop/dygraph/mnist/train.py)
We have a couple of questions about the difference between the examples:

1. Is 'imperative' a special use of DyGraph in PaddlePaddle vocabulary?
2. Is [test_imperative_mnist.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_imperative_mnist.py) still used by the Baidu for the purpose of testing DyGraph ? Is it a valid example?
3. What are the customers' use case scenarios for **TracedLayer.trace** use in production when training in DyGraph mode? 
4. It looks like **TracedLayer** is not used in [mnist/train.py](https://github.com/PaddlePaddle/models/blob/develop/dygraph/mnist/train.py). Is it needed in production models?

**Comment by phlrain** [comment]
1. 是的，动态图和静态图最根本得差别是，动态图的op能够立即执行，对应英文单词 imperative program，动态图是由于能够立即执行的特点，才能够描述动态的计算图，后续我们会使用imperative 作为动态图的名称。（但是为了方便，可能还会叫动态图）
2. test_imperative_mnist.py 是一个单测，是为了防止一些新的pr，引起动态图的错误；不建议作为一个示例使用，建议使用 [mnist/train.py](https://github.com/PaddlePaddle/models/blob/develop/dygraph/mnist/train.py).
3. TracedLayer.trace 是当用户有模型部署上线的需求的时候，才需要使用，这个接口是将动态图转成静态图，然后利用静态图的方式进行部署上线
4.   [mnist/train.py](https://github.com/PaddlePaddle/models/blob/develop/dygraph/mnist/train.py) 这个里面只是包含了训练的部分，目前models的模型都没有包含这个TracedLayer；TracedLayer这个模块目前有一些局限性，不能支持依赖数据的控制流的转换，我们在开发新的模块，后面会主推这个新模块

**Comment by lidanqing-vv** [comment]
Translation
1. Yes, the essential difference between dynamic graphs and static graphs is that the op of dynamic graphs can be executed immediately, corresponding to the English word imperative program. Dynamic graphs are called dygraph because of the characteristics of immediate execution. We will use imperative as the name of the dynamic graph. (But for convenience, it may still be called a dynamic graph)
2. test_imperative_mnist.py is a UT, to prevent some new PR from causing errors in the dynamic graph; it is not recommended to be used as a demo, for demo, we recommended to use mnist/train.py.
3. TracedLayer.trace is only needed when the user has the need to deploy the model online. This interface is to convert the dynamic graph into a static graph, and then use the static graph to deploy and go online.
4. mnist/train.py only contains the training part. At present, none of the models of the models include this TracedLayer; the module of TracedLayer currently has some limitations and cannot support the conversion of data-dependent control flow. We are developing new modules and will push new module later

**Comment by arlesniak** [comment]
Thank you for the information
