### ISSUE TITLE
SDK不同版本链接错误

### ISSUE THREAD

**Issue by shenshuijing** [PaddlePaddle/Paddle#2640]
线下自己写了一个sparse的predictor， 用SparseNonValuePredictor， 则以下两个依赖编译链接都是可以的
并且预测结果一致
CONFIGS('idl/paddle/sdk@sdk_1-0-3-0_PD_BL', Libraries('./lib/libpaddle_predictor_noavx.a'))
或者
CONFIGS('idl/paddle/sdk@sdk_1-0-4-765_PD_BL', Libraries('./lib/libpaddle_predictor_noavx.a'))

但是如果用MultipleTypesPredictor， 则用
CONFIGS('idl/paddle/sdk@sdk_1-0-3-0_PD_BL', Libraries('./lib/libpaddle_predictor_noavx.a'))这个是正常的，但是当用依赖
CONFIGS('idl/paddle/sdk@sdk_1-0-4-765_PD_BL', Libraries('./lib/libpaddle_predictor_noavx.a'))
时， 报一下链接错误
![image](https://user-images.githubusercontent.com/24400858/27619352-489fa0ac-5bf4-11e7-97a1-e76050788ab7.png)

**Comment by reyoung** [comment]
The previous predict SDK has been deprecated.

Also, in the previous predict SDK, different version should use the different header file, because the ABI between version is not same.
When use `CONFIGS('idl/paddle/sdk@sdk_1-0-4-765_PD_BL', Libraries('./lib/libpaddle_predictor_noavx.a'))` you should use `1-0-4`'s binary, not `./lib/libpaddle_predictor_noavx.a'`.
