### ISSUE TITLE
Some questions about trainer errors.

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#2682]
1. Should a trainer exit when it meets errors? For example, read data error?And
2. Will The whole job exit when a specific task exit abnormally continuously many times which is large than our limit? When this happens, it means that these errors can't be fixed by starting new trainers. And
3. Do we need a  `TaskFail` interface for trainer report it's error task before exit? A trainer reports task's error state by only `timeout` now, and it's very slow. And
4. We should change the [life cycle of a single task](https://github.com/helinwang/Paddle/blob/009001eb915bc408faba6627ac2a0c9cea15b27d/doc/design/dist/README.md#task-queue) picture to add `failed task queue` and so on.

**Comment by jacquesqiao** [comment]
>2. Will The whole job exit when a specific task exit abnormally continuously many times which is large than our limit? When this happens, it means that these errors can't be fixed by starting new trainers.

"If a task timeout. the master process will move it back to the todo queue. The timeout count will increase by one. If the timeout count is above a threshold, the task is likely to cause a trainer to crash, so it will be discarded."  this is in the design doc now.

> 3. Do we need a TaskFail interface for trainer report it's error task before exit? A trainer reports task's error state by only timeout now, and it's very slow

I think we need one to report the status

> 4. We should change the life cycle of a single task picture to add failed task queue and so on.

Is this fixed by the "timeout record in and discarded mechanism" now？

**Comment by dzhwinter** [comment]
> Do we need a TaskFail interface for trainer report it's error task before exit? A trainer reports task's error state by only timeout now, and it's very slow. 
Agreed. I think we need one, like some data format error, illegal hyperparameter.  Such task like that should failed as soon as possible, which should not go though the `timeout count and discarded mechanism`.

**Comment by Yancey1989** [comment]
Thanks for @gongweibao for these good questions!
> 1. Should a trainer exit when it meets errors? And

I think the trainer will exit only when the FATAL error, such as an invalid configuration,  or the connection times exceeding the max retry times, such as retry to connect master or pserver, because of there may happen some error about infrastructure, like network card error no host, and restart a new trainer on the other node will recover the training.

**Comment by gongweibao** [comment]
@jacquesqiao 
> "If a task timeout. the master process will move it back to the todo queue. The timeout count will increase by one. If the timeout count is above a threshold, the task is likely to cause a trainer to crash, so it will be discarded." this is in the design doc now.

Thanks for your reminder! Maybe the job needs to exit when the number of discard tasks larger than our limit?

**Comment by gongweibao** [comment]
@Yancey1989 It's better:
> I think the trainer will exit only when the FATAL error

**Comment by helinwang** [comment]
I agree with @Yancey1989 :
> I think the trainer will exit only when the FATAL error, such as an invalid configuration, or the connection times exceeding the max retry times, such as retry to connect master or pserver, because of there may happen some error about infrastructure, like network card error no host, and restart a new trainer on the other node will recover the training.

About `failed task queue`, it's a queue master uses to save failed tasks. A task may fail due to many reasons: data problem causing trainer to crash, trainer killed by k8s, ...
I think we should let the train decide when to kill himself, not the master decide when to kill trainer.

At last, I think we need to use `recover()` to "catch" all panics and do graceful shutdown for trainer, master and pserver. @typhoonzero
