### ISSUE TITLE
CPU transpose slow than numpy on some machines

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#27877]
**System information**

- PaddlePaddle version: `pip install paddlepaddle==2.0.0a0 -i https://pypi.tuna.tsinghua.edu.cn/simple`

**To Reproduce**
Steps to reproduce the behavior: `python single_op_paddle_vs_np.py` 
[single_op_paddle_vs_np.py.zip](https://github.com/PaddlePaddle/Paddle/files/5368745/single_op_paddle_vs_np.py.zip)

- `use_paddle = True`: run Paddle
- `use_paddle = False`: run numpy

**Describe your current behavior**
- On machine 6148: Paddle runs faster than numpy
  - numpy
<img width="440" alt="图片" src="https://user-images.githubusercontent.com/6836917/95811411-d1481a00-0d45-11eb-85f3-35b2855d7aee.png">
  
  - paddle
<img width="474" alt="图片" src="https://user-images.githubusercontent.com/6836917/95811430-ddcc7280-0d45-11eb-9b06-c7232e9d4667.png">

- But on machine Intel(R) Core(TM) i7-4770R CPU @ 3.20GHz: Paddle runs 10X slower than numpy
![图片](https://user-images.githubusercontent.com/6836917/95811585-2c7a0c80-0d46-11eb-999d-a7b9bac80ef5.png)

```
processor       : 7
vendor_id       : GenuineIntel
cpu family      : 6
model           : 70
model name      : Intel(R) Core(TM) i7-4770R CPU @ 3.20GHz
stepping        : 1
microcode       : 0x1c
cpu MHz         : 798.200
cache size      : 6144 KB
physical id     : 0
siblings        : 8
core id         : 3
cpu cores       : 4
apicid          : 7
initial apicid  : 7
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips        : 6385.01
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:
```

Could you help give some explanation of this issue? Is it related with CPU? 
If you want to ssh i7-4770R, please let me know.

**Comment by luotao1** [comment]
@jczaja @lidanqing-intel It's some code of Quantum computing Application.

**Comment by jczaja** [comment]
@luotao1 Looks like CPU related issue. Perhaps transpose for this particular platform (AVX2 instruction set) is not optimized. It would be very helpful to get oneDNN execution log from 6148 and i7-4770R. e.g.
If you could run DNNL_VERBOSE=1 python <rest of arguments>  . That would be very helpful in other to trace underperforming element.

**Comment by luotao1** [comment]
> It would be very helpful to get oneDNN execution log from 6148 and i7-4770R. e.g.
If you could run DNNL_VERBOSE=1 python .

Since we don't use `FLAGS_use_mkldnn=1` to run the script, they don't run with mkldnn operators. Do you need `MKL_VERBOSE=1`?

**Comment by lidanqing-vv** [comment]
This situation could also be reproduced in AVX2 machine, compared with 6148 machine

**Comment by lidanqing-vv** [comment]
@luotao1  We reproduce slow performance on avx2 machine, but not so big diff.
```
using Numpy:
avg exec time: 1.1687255859375, min: 0.8330726623535156, max: 1.9801416397094727
using Paddle:
avg exec time: 2.0422954082489015, min: 0.8276886940002441, max: 2.674208164215088
```
What os-system this machine has ?

**Comment by luotao1** [comment]
@lidanqing-intel I have sent the machine by email.

**Comment by arogowie-intel** [comment]
@luotao1 It seems that when using Paddle from PyPI (as in description)  no oneDNN kernels are used. Even when trying to force it with `FLAGS_use_mkldnn=True` flag. However when I build Paddle from sources and then try to run this script with following command: `FLAGS_use_mkldnn=True DNNL_VERBOSE=1 python single_op_paddle_vs_npy.py` I get such error:
```
----------------------
Error Message Summary:
----------------------
NotFoundError: Operator transpose2 does not have kernel for data_type[double]:data_layout[MKLDNNLAYOUT]:place[CPUPlace]:library_type[MKLDNN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /home/Adam/playground/pdpd/Paddle/paddle/fluid/imperative/prepared_operator.cc:118)
  [operator < transpose2 > error]
```
This is because oneDNN does not support `double` data type which is probably used for Paddle complex data type.

I'm not sure whether we can do anything about the package which is build without oneDNN (the one intalled with `pip` command)

**Comment by luotao1** [comment]
Which pypi package do you use? `pip install paddlepaddle==2.0.0a0`?
We have mkldnn in this pypi package.

**Comment by arogowie-intel** [comment]
I'm using the `2.0.0a0` version as pointed in issue description. The tag `2.0.0a0` doesn't yet have support for `FLAGS_use_mkldnn=True` in dygraph mode, as you may see [here](https://github.com/PaddlePaddle/Paddle/blob/v2.0.0-alpha0/paddle/fluid/imperative/tracer.cc#L45-L68).  This causes that no oneDNN kernel is called for any used operator, since they will not have _use\_mkldnn_ attirbute set to true. 

Please try use at least [2.0.0b tag](https://github.com/PaddlePaddle/Paddle/blob/v2.0.0-beta0/paddle/fluid/imperative/tracer.cc#L52-L54). So the lack of support for this flag in the 2.0.0a package version explains why I didn't get any additional output and that on Paddle build from latest develop i get it. 

So I believe that this slowness is a characteristic of native transpose op implementation. Keep in mind that even with latest develop version of Paddle this code will not run with oneDNN kernel since, as I said, oneDNN doesn't yet support `double` data type.

**Comment by luotao1** [comment]
> So I believe that this slowness is a characteristic of native transpose op implementation

Indeed We want to know why native transpose op implementation slower than numpy only on i7-machine? Could you give some explanation on it? The reason is that our business customers could choose and buy their machine, they want to know which kind of machine is OK.

**Comment by arogowie-intel** [comment]
I've carried out multiple tests mesauring execution times on following platforms.
Values are in seconds from 100 iterations:

| machine                    | library | avg exec time | min exec time | max exec time |
| :----                      | :---    | :---:         | :---:         | :---:         |
| Xeon(R) Gold 6148          | NumPy   | 3.16223       |  1.62517      | 6.20450       |
| Xeon(R) Gold 6148          | Paddle  | 2.90462       |  1.53687      | 6.36371       |
| Xeon(R) CPU E5-2650 v4     | NumPy   | 1.43998       |  0.81063      | 2.94021       |
| Xeon(R) CPU E5-2650 v4     | Paddle  | 2.04934       |  0.81405      | 5.19751       |
| Intel(R) Core(TM) i5-7300U | NumPy   | 4.51132       |  2.69911      | 8.46966       |
| Intel(R) Core(TM) i5-7300U | Paddle  | 3.89334       |  2.77528      | 7.74943       |

Moreover I did detailed profiling on 6148 and E5-2650 v4 machines where I build Paddle from
source adding profiling instructions to see how much of the overall time does the transpose op
kernel takes. And it turned out that on the SKX platform it takes: 86% and on BDW it is 99%.
The native kernel is written using Eigen's shuffle operation on Eigen's Tensor object. So
it seems that Eigen is not best optimized for single-thread execution on BDW (AVX2) platform.
Probably NumPy's implementation which should use some BLAS library is better optimized.

The another observation for SKX platform is that the allocation of memory for output tensor
inside the transpose kernel takes significant portion (32%) of kernel execution time.

**Comment by luotao1** [comment]
Got it, thanks for your explanation!
