### ISSUE TITLE
[BF16]  BF16 UT have memory increase and related script incompatibility with python3

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#29070]
@luotao1  Hi, this is bfloat16 resnet50 inference benchmark steps

**Comment by luotao1** [comment]
Do you need to compare with the int8 result on 6271? And how do you write the BF16 release note?

**Comment by lidanqing-vv** [comment]
No, only need to compare with float32 I think. Because bf16 does not have scales etc. Only comparing with float32 make sense.
About BF16 release note, I will discuss with my colleagues. BF16 will mainly focus on performance since accuracy should be very similar.

**Comment by lidanqing-vv** [comment]
[BF16_test_reproduction_2.txt](https://github.com/PaddlePaddle/Paddle/files/5628895/BF16_test_reproduction_2.txt)
Hi, @luotao1  @OliverLPH  this is BF16 inference benchmark for 4 models: resnet50, mobilenetv1, mobilenetv2, googlenet. Please verify it on Bfloat16 machine. Thank you very much

**Comment by OliverLPH** [comment]
@lidanqing-intel @luotao1 
I have finished and verified the tests. 
here is my results, 
[测试数据.xlsx](https://github.com/PaddlePaddle/Paddle/files/5650309/default.xlsx)

Howerver, there are two issues need to concern
1. `paddle/fluid/inference/tests/api/full_ILSVRC2012_val_preprocess.py` can only convert data to binary with python2, python3 will crash due to some reason
![image](https://user-images.githubusercontent.com/14963836/101306960-3c632800-3881-11eb-905a-7176fd443453.png)

2. unittests `paddle/fluid/inference/tests/api/test_analyzer_bfloat16_image_classification` has memory increasing may because [tester_helper.h](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/tests/api/tester_helper.h#L540) insert data to output vector constantly. So I haven't record cpu memory here for comparison.

**Comment by lidanqing-vv** [comment]
@OliverLPH Ok we will fix the python3 incompatibility issue.
@wozna Is memory increasing normal for this test, do you have any idea?

**Comment by luotao1** [comment]
> Is memory increasing normal for this test, do you have any idea?

This is a small bug of unit-test, you can refer to https://github.com/PaddlePaddle/Paddle/pull/18372/files#diff-de4300fc1192c77b78427084b631dbb9eaada1539b2783416babff2cd0c60f51R119
```
std::vector<std::vector<PaddleTensor>>().swap(input_slots_all);
```
I use `swap` to clear input vector.

**Comment by wozna** [comment]
@OliverLPH @luotao1 @lidanqing-intel  I checked this memory usage with this test and I don't see any memory increasing. 
The memory rises at the beginning to a constant value and at the end of the test is released. 
In the beginning, in `paddle /fluid/inference/tests/api/test_analyzer_bfloat16_image_classification`  , https://github.com/PaddlePaddle/Paddle/blob/b9e926b8e5470058a3161188481af681469a8bf3/paddle/fluid/inference/tests/api/analyzer_bfloat16_image_classification_tester.cc#L40 we load the input, which takes the most memory.
Then in one for fp32 and one for bf16  `tester_helper.h` we increase the output vector to the size of the iteration number and then we refer to this vector by index, so we do not change the size of the vector after that.  https://github.com/PaddlePaddle/Paddle/blob/b9e926b8e5470058a3161188481af681469a8bf3/paddle/fluid/inference/tests/api/tester_helper.h#L527   .
Obviously, the memory wear here increases as the numbers of samples increase, because we want to check accuracy from all samples. 
Please correct me if I don't understand something.

Of course, we can do optimization to calculate the accuracy just after the float computation and then use the same output vector for calculations in the bfloat16 test.

**Comment by OliverLPH** [comment]
@wozna I think you are right, the memory increase here will reach constant at the end of test. 
At beginning, I used `pmap -x` to observe memory status of `test_analyzer_bfloat16_image_classification` process, , so it may not accurate. 
And I tried to do simple repeat prediction test, there is no memory increase now. So this issue can be ignored.
Thanks for your investigation
