### ISSUE TITLE
cuda and cudnn version affect inference speed significantly

### ISSUE THREAD

**Issue by xxxpsyduck** [PaddlePaddle/Paddle#30181]
I already reported this [issue](https://github.com/PaddlePaddle/PaddleOCR/issues/1664) in PaddleOCR repo. I don't expect to stick with a fixed version of cuda and cudnn to get the best inference speed but I also wonder this is a normal behavior or not. Or maybe paddle 2.0rc1 is not yet optimized for cuda 11 and cudnn 8?

**Comment by cryoco** [comment]
Thanks for your feedback. We are also aware of this performance regression. We contacted NVIDIA and it's been confirmed that the performance regression in cudnn 8.0.4 and 8.0.5 is a known issue. It will possibly be fixed in the next version, cudnn 8.1. As for lower versions of cudnn 8.0(e.g. 8.0.3), we are still doing some performance tests, and will update the results.

**Comment by xxxpsyduck** [comment]
@cryoco Thanks so much for your reply. I will leave the issue open until further updates.
