### ISSUE TITLE
KeyError when using recurrent_group

### ISSUE THREAD

**Issue by gibiansky** [PaddlePaddle/Paddle#3061]
I have the following code:

```python
size = 100

boot = paddle.layer.fc(
  size=size,
  act=paddle.activation.Tanh(),
  bias_attr=False,
  input=static_input)

def gru_with_static_input(current_input, static_input):
     mem = paddle.layer.memory(name='memory', size=size, boot_layer=boot)
     gru_inputs = paddle.layer.fc(
         act=paddle.activation.Linear(),
         size=size * 3, bias_attr=False,
         input=[static_input, current_input])
     gru_step = paddle.layer.gru_step(
         name='gru_decoder',
         input=gru_inputs,
         output_mem=mem,
         size=size)
     return gru_step

fwd = paddle.layer.recurrent_group(input=inputs, step=gru_with_static_input, name="fwd")
```

I get the following error which I don't understand:

```text
  File "paddlepaddle.py", line 117, in lstm
    fwd = paddle.layer.recurrent_group(input=inputs, step=make_gru_step(size, static), name="fwd")
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/layers.py", line 3643, in recurrent_group
    RecurrentLayerGroupEnd(name=name)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 391, in RecurrentLayerGroupEnd
    layer = g_layer_map[pair.layer_name]
KeyError: u'memory@fwd'
```

This is using the docker image `paddlepaddle/book:latest-gpu`.

What is going on? How do I fix this? I took the code from the machine translation notebook and modified it.

**Comment by gibiansky** [comment]
Looking at `config_parser.py`, `memory+delay1@fwd` is in `g_layer_map`, but not `memory@fwd`... Still not sure what's going on here.

**Comment by lcy-seso** [comment]
The error is caused by this line:
```python
mem = paddle.layer.memory(name='memory', size=size, boot_layer=boot)
```
it should be changed into this:
```python
mem = paddle.layer.memory(name='gru_decoder', size=size, boot_layer=boot)
```
---
Some explanations about memory in PaddlePaddle:
1. I think `memory` in PaddlePaddle is very like reference parameters C++. Itself is not a real layer, but points to a layer and retrieve the output of last time of this layer.
2. Every layer in PaddlePaddle has a unique name if the user does not name a layer explicitly, it will be named automatically.
3. In the above code, the `fc` layer does not have an explicit name, but you have to give a name to `paddle.layer.gru_step`.  This is because the name specified by the `name` parameter is not the name for `paddle.layer.memory` but the name the `memory` layer pointed to.
4. In the code below, the real name of `paddle.layer.memory` is in the returned value `mem`, it is `memory+delay1@fwd`.
    ```python
    mem = paddle.layer.memory(name='gru_decoder', size=size, boot_layer=boot)
    ```
---
* in the original error  information: `KeyError: u'memory@fwd'`. `u'memory@fwd'` is the name of the layer `paddle.layer.memory` pointed to, but this layer does not be defined, so paddle raise a `KeyError`.
* I think, this problem is caused the document is not very clear in Paddle ...

**Comment by pkuyym** [comment]
Close it due to inactive. Please feel free to reopen if necessary.
