### ISSUE TITLE
使用dropout在eval模式下出错的问题

### ISSUE THREAD

**Issue by yangkerrr** [PaddlePaddle/Paddle#31092]
出错部分代码：
class _routing(nn.Layer):

    def __init__(self, in_channels, num_experts, dropout_rate):
        super(_routing, self).__init__()
        
        self.dropout = nn.Dropout(p=dropout_rate)
        self.fc = nn.Linear(in_channels, num_experts)

    def forward(self, x):
        x = paddle.flatten(x).clone()
        x = self.dropout(x)
        x = self.fc(x)
        return F.sigmoid(x)
可以正常训练，但验证时报错
报错信息：
Traceback (most recent call last):
  File "train.py", line 145, in <module>
    main(args)
  File "train.py", line 140, in main
    losses=losses)
  File "/home/aistudio/work/PaddleSeg/paddleseg/core/train.py", line 183, in train
    model, val_dataset, num_workers=num_workers)
  File "/home/aistudio/work/PaddleSeg/paddleseg/core/val.py", line 110, in evaluate
    crop_size=crop_size)
  File "/home/aistudio/work/PaddleSeg/paddleseg/core/infer.py", line 169, in inference
    logits = model(im)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/PaddleSeg/paddleseg/models/unet.py", line 63, in forward
    x, short_cuts = self.encode(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/PaddleSeg/paddleseg/models/unet.py", line 95, in forward
    x = self.double_conv(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/container.py", line 86, in forward
    input = layer(input)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/PaddleSeg/paddleseg/models/layers/layer_libs.py", line 47, in forward
    x = self._conv(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/PaddleSeg/paddleseg/models/layers/CondConv.py", line 77, in forward
    routing_weights = self._routing_fn(pooled_inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/PaddleSeg/paddleseg/models/layers/CondConv.py", line 19, in forward
    x = self.dropout(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/common.py", line 689, in forward
    name=self.name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/common.py", line 924, in dropout
    if seed is not None else 0, 'dropout_implementation', mode)
ValueError: (InvalidArgument) Input dimension number(num_col_dims) must be between 0 and 1, but received number is 1.
  [Hint: Expected (num_col_dims > 0 && num_col_dims < rank) == true, but received (num_col_dims > 0 && num_col_dims < rank):0 != true:1.] (at /paddle/paddle/fluid/framework/eigen.h:94)
  [operator < dropout > error]
terminate called without an active exception

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1613917048 (unix time) try "date -d @1613917048" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e8000028cc) received by PID 10444 (TID 0x7f9180ffd700) from PID 10444 ***]

**Comment by ysh329** [comment]
这个是训练OK，但是预测出问题嘛，你使用的是什么Paddle的版本，CPU还是GPU环境，GPU的话CUDA版本是多少

**Comment by yangkerrr** [comment]
> 这个是训练OK，但是预测出问题嘛，你使用的是什么Paddle的版本，CPU还是GPU环境，GPU的话CUDA版本是多少

Paddle2.0，GPU环境，CUDA11.0（AIStudio内环境）

**Comment by sellinaxmj** [comment]
同遇到这样的问题。在centos系统，查说numpy版本太高不匹配，从1.18.4降到1.17.3还是会报这个错误。求助各位大佬，谢谢～
安装列表：
conda list
# packages in environment at /home/hh/anaconda3/envs/ocr_p:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
addict                    2.2.1                    pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
blas                      1.0                         mkl  
boto3                     1.16.62                  pypi_0    pypi
botocore                  1.19.62                  pypi_0    pypi
bottle                    0.12.19                  pypi_0    pypi
ca-certificates           2021.1.19            h06a4308_0  
certifi                   2020.12.5        py38h06a4308_0  
chardet                   4.0.0                    pypi_0    pypi
common                    0.1.2                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
data                      0.4                      pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
dual                      0.0.10                   pypi_0    pypi
dynamo3                   0.4.10                   pypi_0    pypi
flywheel                  0.5.4                    pypi_0    pypi
funcsigs                  1.0.2                    pypi_0    pypi
gast                      0.3.3                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
intel-openmp              2020.2                      254  
jmespath                  0.10.0                   pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
lmdb                      1.0.0                    pypi_0    pypi
matplotlib                3.3.4                    pypi_0    pypi
mkl                       2020.2                      256  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.2.0            py38h23d657b_0  
mkl_random                1.1.1            py38h0573a6f_0  
ncurses                   6.2                  he6710b0_1  
networkx                  2.5                      pypi_0    pypi
numpy                     1.17.3                   pypi_0    pypi
opencv-python             4.2.0.34                 pypi_0    pypi
openssl                   1.1.1i               h27cfd23_0  
paddle                    1.0.2                    pypi_0    pypi
paddlepaddle              2.0.0                    pypi_0    pypi
peewee                    3.14.0                   pypi_0    pypi
pillow                    6.2.2                    pypi_0    pypi
pip                       20.3.3           py38h06a4308_0  
protobuf                  3.14.0                   pypi_0    pypi
prox                      0.0.17                   pypi_0    pypi
pyclipper                 1.1.0.post3              pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pysocks                   1.7.1                    pypi_0    pypi
python                    3.8.5                h7579374_1  
python-dateutil           2.8.1                    pypi_0    pypi
python-geoip-python3      1.3                      pypi_0    pypi
python-levenshtein        0.12.2                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
readline                  8.1                  h27cfd23_0  
requests                  2.25.1                   pypi_0    pypi
s3transfer                0.3.4                    pypi_0    pypi
scikit-image              0.18.1                   pypi_0    pypi
scipy                     1.5.2            py38h0b6359f_0  
setuptools                52.0.0           py38h06a4308_0  
shapely                   1.7.0                    pypi_0    pypi
six                       1.15.0           py38h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
termcolor                 1.1.0                    pypi_0    pypi
tifffile                  2021.1.14                pypi_0    pypi
tight                     0.1.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
torch                     1.7.1                    pypi_0    pypi
torchvision               0.8.2                    pypi_0    pypi
tqdm                      4.46.0                   pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.3                   pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3 
错误信息如下：
$ python3 tools/infer/predict_det.py --det_algorithm="EAST" --image_dir="./doc/imgs_en/img_10.jpg" --det_model_dir="./inference/det_east/"
E0223 11:25:19.415256  2592 analysis_config.cc:78] Please compile with gpu to EnableGpu()
OMP: Error #15: Initializing libiomp5.so, but found libiomp5.so already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::GemmConvKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::GemmConvKernel<paddle::platform::CPUDeviceContext, double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::operators::GemmConvKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
7   void paddle::operators::math::Blas<paddle::platform::CPUDeviceContext>::MatMul<float>(paddle::framework::Tensor const&, bool, paddle::framework::Tensor const&, bool, float, paddle::framework::Tensor*, float) const
8   cblas_sgemm
9   sgemm
10  mkl_blas_sgemm
11  mkl_serv_get_num_stripes
12  omp_get_num_procs
13  paddle::framework::SignalHandle(char const*, int)
14  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1614050719 (unix time) try "date -d @1614050719" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800000a20) received by PID 2592 (TID 0x7f5b084a7740) from PID 2592 ***]

已放弃(吐核)

**Comment by ysh329** [comment]
@sellinaxmj 新建issue，就不是一个问题好吧

**Comment by ysh329** [comment]
> > 这个是训练OK，但是预测出问题嘛，你使用的是什么Paddle的版本，CPU还是GPU环境，GPU的话CUDA版本是多少
> 
> Paddle2.0，GPU环境，CUDA11.0（AIStudio内环境）

收到，我问下API相关负责人

**Comment by huangjun12** [comment]
> 出错部分代码：
> class _routing(nn.Layer):
> 
> ```
> def __init__(self, in_channels, num_experts, dropout_rate):
>     super(_routing, self).__init__()
>     
>     self.dropout = nn.Dropout(p=dropout_rate)
>     self.fc = nn.Linear(in_channels, num_experts)
> 
> def forward(self, x):
>     x = paddle.flatten(x).clone()
>     x = self.dropout(x)
>     x = self.fc(x)
>     return F.sigmoid(x)
> ```
> 
> 可以正常训练，但验证时报错
> 报错信息：
> Traceback (most recent call last):
> File "train.py", line 145, in
> main(args)
> File "train.py", line 140, in main
> losses=losses)
> File "/home/aistudio/work/PaddleSeg/paddleseg/core/train.py", line 183, in train
> model, val_dataset, num_workers=num_workers)
> File "/home/aistudio/work/PaddleSeg/paddleseg/core/val.py", line 110, in evaluate
> crop_size=crop_size)
> File "/home/aistudio/work/PaddleSeg/paddleseg/core/infer.py", line 169, in inference
> logits = model(im)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in **call**
> outputs = self.forward(*inputs, **kwargs)
> File "/home/aistudio/work/PaddleSeg/paddleseg/models/unet.py", line 63, in forward
> x, short_cuts = self.encode(x)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in **call**
> outputs = self.forward(*inputs, **kwargs)
> File "/home/aistudio/work/PaddleSeg/paddleseg/models/unet.py", line 95, in forward
> x = self.double_conv(x)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in **call**
> outputs = self.forward(*inputs, **kwargs)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/container.py", line 86, in forward
> input = layer(input)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in **call**
> outputs = self.forward(*inputs, **kwargs)
> File "/home/aistudio/work/PaddleSeg/paddleseg/models/layers/layer_libs.py", line 47, in forward
> x = self._conv(x)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in **call**
> outputs = self.forward(*inputs, **kwargs)
> File "/home/aistudio/work/PaddleSeg/paddleseg/models/layers/CondConv.py", line 77, in forward
> routing_weights = self._routing_fn(pooled_inputs)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in **call**
> outputs = self.forward(*inputs, **kwargs)
> File "/home/aistudio/work/PaddleSeg/paddleseg/models/layers/CondConv.py", line 19, in forward
> x = self.dropout(x)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in **call**
> outputs = self.forward(*inputs, **kwargs)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/common.py", line 689, in forward
> name=self.name)
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/common.py", line 924, in dropout
> if seed is not None else 0, 'dropout_implementation', mode)
> ValueError: (InvalidArgument) Input dimension number(num_col_dims) must be between 0 and 1, but received number is 1.
> [Hint: Expected (num_col_dims > 0 && num_col_dims < rank) == true, but received (num_col_dims > 0 && num_col_dims < rank):0 != true:1.] (at /paddle/paddle/fluid/framework/eigen.h:94)
> [operator < dropout > error]
> terminate called without an active exception
> 
> ## C++ Traceback (most recent call last):
> 0 paddle::framework::SignalHandle(char const*, int)
> 1 paddle::platform::GetCurrentTraceBackStringabi:cxx11
> 
> ## Error Message Summary:
> FatalError: `Process abort signal` is detected by the operating system.
> [TimeInfo: *** Aborted at 1613917048 (unix time) try "date -d @1613917048" if you are using GNU date ***]
> [SignalInfo: *** SIGABRT (@0x3e8000028cc) received by PID 10444 (TID 0x7f9180ffd700) from PID 10444 ***]

看起来时数据问题，检查一下train和eval时dropout的输入数据维度一样嘛

**Comment by baiwei-yndx** [comment]
建议看一下reader.yml  评估模块drop_empty: ture（同样问题，我原来为drop_empty: false改为ture即可）
