### ISSUE TITLE
Installation path and build_doc problems of Mkldnn

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#3162]
Though #3096 is closed, there are two commits should be merged at first.
- The installation path of Mkldnn is in `/home/user/opt/paddle/thirdparty` currently. We should move it `paddle/thirdparty`, where all other thirdparty libraries located. https://github.com/PaddlePaddle/Paddle/commit/e9e6a81310adb864a599988a29b2b2f113ab2620
- `build_doc` in travis-ci will be failed if `-DWITH_MKLDNN=True -DWITH_MKLML=True`. We should set it false when generating document. https://github.com/PaddlePaddle/Paddle/commit/4dd31e8b7b425b907df86bff76875e1ead9c1efa

@tensor-tang will implement it. Thx!

**Comment by tensor-tang** [comment]
Sure, will update soon.

But, one point to be clarify:
Because `MKLDNN` and `MKLML` `*.so` move to` build/third_party`, then build doc will fail as it will remove all `*.so` before build doc.
Then , we will need to disable `MKLDNN` and `MKLML` when build doc.

This should lead to another issue to figure out how to integrate those so files into paddle whl.
We should follow it later.

**Comment by luotao1** [comment]
> This should lead to another issue to figure out how to integrate those so files into paddle whl.
We should follow it later.

The issue is #3213
