### ISSUE TITLE
OSError: (External) Cudnn error, CUDNN_STATUS_NOT_INITIALIZED (at /paddle/paddle/fluid/platform/device_context.h:370)

### ISSUE THREAD

**Issue by LinXin04** [PaddlePaddle/Paddle#34557]
GPU训练出错

cuda: 10.1
cudnn:7.6
python3.6

python -m pip install paddlepaddle-gpu==2.1.0.post101 -f https://paddlepaddle.org.cn/whl/mkl/stable.html

**Comment by LinXin04** [comment]
@DannyIsFunny 麻烦大佬帮忙看看～

**Comment by DannyIsFunny** [comment]
Objective
This issue may be caused by incorrect GPU driver (insufficient driver version). The old GPU driver should be removed as the new version GPU driver needs to be installed.

Steps
To reinstall GPU driver:
1. Download the required GPU driver via the below link:
    https://www.nvidia.com/Download/index.aspx
2. Remove the old version GPU driver:
    apt purge nvidia*
3. Restart the host.
4. Install the download GPU driver.
5. Reboot.

**Comment by DannyIsFunny** [comment]
或者可以检查一下：环境的cuda driver版本和cudnn版本是否匹配

**Comment by LinXin04** [comment]
运行别的tensorflow代码GPU是可以的，paddle，paddlepaddle-gpu也可以安装成功。但是运行paddleOCR的时候还是有初始化问题，不知道怎么定位
import torch
print(torch.__version__)
print(torch.version.cuda)
print(torch.backends.cudnn.version())

1.4.0
10.1
7603

**Comment by DannyIsFunny** [comment]
![78060b6c202babb9935163cf9b9c0869](https://user-images.githubusercontent.com/45189361/128109958-b12600e4-9ee5-4b29-8604-2d7dc451904c.png)
你好可以参照这个表比对一下CUDA和driver版本是否匹配
