### ISSUE TITLE
quantized segmentation model raises relu error

### ISSUE THREAD

**Issue by juncaipeng** [PaddlePaddle/Paddle#34574]
Download the demo(url:https://pan.baidu.com/s/1NW7L4-fggH-nnJE9SNu63g  passwd:kf1l) and refer to the readme.

Error as follows:
```
NotFoundError: Operator (relu) does not have kernel for data_type[int8_t]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN].
```

**Comment by wozna** [comment]
@juncaipeng I just started investigating this problem. This model has an inplace operation with elementwise_add and relu. It turned out that the quantization process is not immune to this, hence this error. Therefore I will start working to find the best solution for this.

**Comment by wozna** [comment]
@juncaipeng  I found the problem, it turned out we had an error in elementwise_add quantization because we set the `force_fp32_output` attribute if the output scale was not found. Unfortunately, this operator does not have this attribute or this functionality. I fixed it in PR https://github.com/PaddlePaddle/Paddle/pull/34820

**Comment by juncaipeng** [comment]
Thank you, I will test the PR.

**Comment by lidanqing-vv** [comment]
@juncaipeng 你有时间测了吗？
