### ISSUE TITLE
关于paddle预测样本原始ID信息输出的问题

### ISSUE THREAD

**Issue by HugoLian** [PaddlePaddle/Paddle#3466]
paddle的输出方法，如果需要保留测试数据的id，目前好像只有通过integer_value( )作为slot来输入，然后输出。但是我们的id有一部分超过了integer的范围，另一些ID是字符型ID。
如果是单机跑结果，可以最后同时遍历一下测试文件和paddle结果文件，勉强把id和paddle测试结果对应上，已然很不方便，现在业务场景数据量比较大，希望放到集群上处理，但是这样就没有办法吧各种ID保留下来了，请问可以开发类似 string_value( ) 的输入类型，或者有什么办法可以解决这个问题么？

**Comment by wanghaoshuang** [comment]
@HugoLian 方便贴一下你的需求样例代码么？我们评估下是不是要实现string_value. 谢谢。

**Comment by HugoLian** [comment]
@wanghaoshuang ID重新编码基本可以解决这个问题，但是现在各业务线涉及的ID应该绝大多数都超过了integer的限制。
比如百度的用户uid，
比如我的产品线百度知道 以及各条子产品线的 qid, rid, 或者加密后的大整数id信息，百度cookie，cuid16进制的ID信息，目前我们涉及业务一线的绝大多数真实id信息都不能够直接处理，其他产品线真是信息应该也有类似的情况。
如果通过重新编码来处理会特别麻烦，可能一条结果对应的uid, qid, rid三套ID都要映射。（如推荐模型产出结果为uid 对应的qid下rid）

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
