### ISSUE TITLE
Test paddle/paddle/memory

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#3482]
@emailweixu mentioned in https://github.com/PaddlePaddle/Paddle/issues/3437#issuecomment-322268577 implies that there might be GPU memory leakage.  How can we ensure no such problem?

**Comment by gangliao** [comment]
Currently, our new memory management is occupied exclusively by one process. 

https://github.com/PaddlePaddle/Paddle/blob/9eaef75397926819294edda04dbed34aa069f5f4/paddle/platform/gpu_info.cc#L19

When we execute unit tests in parallel, one of the processes will occupy 95% GPU memory, when another process allocates GPU memory, if the former process has yet released, then others might get a `nullptr` from `paddle::memory::Alloc`. That's the reason why parallel unit test jobs frequently failed.

There are two optional stratagems to suppress this issue:

1. optional 1. set `fraction_of_gpu_memory_to_use` in `cc_test`, `nv_test` of `generic.cmake`, but how to make python receive `gflags` in `py_test`.

2. optional 2.  Add system environment using`std::getenv` so that we can `export FRACTION_GPU_MEMORY_TO_USE=0.2` 

@wangkuiyi @emailweixu
