### ISSUE TITLE
Python binding returns shared_ptr<Object>

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#3487]
In our Python bind, we create a C++ object and return a `shared_ptr` to the object.  For example, [here](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/pybind.cc#L230):

```cpp
py::class_<operators::NetOp, std::shared_ptr<operators::NetOp>> net(m, "Net");
```

It seems that calling Python `new Net()` returns a `shared_ptr<operator::NetOp>` -- however, when will the reference count become 0 and the C++ instance get freed?

**Comment by wangkuiyi** [comment]
If we don't reset the reference count in shared_ptr to free the object at all, we don't need to use shared_ptr, instead, we can just return a newed C++ object.  If we do create another Python function to release the object, we don't need shared_ptr either, because the Python function would free the object, no need for shared_ptr.

**Comment by reyoung** [comment]
In pybind11's documentation, shared_ptr can be handled correctly by pybind11. http://pybind11.readthedocs.io/en/stable/advanced/smart_ptrs.html#std-shared-ptr

Return a shared_ptr, because an operator can hold not only by Python side but also in NetOp or StepNet of RNN in C++ side.

The memory should be handled correctly. Python and C++ should maintain one reference count to indicate whether that object should be destroyed or not.
