### ISSUE TITLE
Shall we need to retain `make install` to install PaddlePaddle

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#3524]

**Comment by luotao1** [comment]
After `make -j 12`, the last several lines is 
```
creating build/bdist.linux-x86_64/wheel/paddlepaddle-0.10.0.data/scripts
copying build/scripts-2.7/paddle -> build/bdist.linux-x86_64/wheel/paddlepaddle-0.10.0.data/scripts
copying build/scripts-2.7/paddle_usage -> build/bdist.linux-x86_64/wheel/paddlepaddle-0.10.0.data/scripts
copying build/scripts-2.7/paddle_trainer -> build/bdist.linux-x86_64/wheel/paddlepaddle-0.10.0.data/scripts
copying build/scripts-2.7/paddle_merge_model -> build/bdist.linux-x86_64/wheel/paddlepaddle-0.10.0.data/scripts
copying build/scripts-2.7/paddle_pserver_main -> build/bdist.linux-x86_64/wheel/paddlepaddle-0.10.0.data/scripts
changing mode of build/bdist.linux-x86_64/wheel/paddlepaddle-0.10.0.data/scripts/paddle to 775
changing mode of build/bdist.linux-x86_64/wheel/paddlepaddle-0.10.0.data/scripts/paddle_usage to 775
changing mode of build/bdist.linux-x86_64/wheel/paddlepaddle-0.10.0.data/scripts/paddle_trainer to 775
changing mode of build/bdist.linux-x86_64/wheel/paddlepaddle-0.10.0.data/scripts/paddle_merge_model to 775
changing mode of build/bdist.linux-x86_64/wheel/paddlepaddle-0.10.0.data/scripts/paddle_pserver_main to 775
creating build/bdist.linux-x86_64/wheel/paddlepaddle-0.10.0.dist-info/WHEEL
[100%] Built target paddle_python
```
If we remove `make install`, how do we `pip install *.whl`. I can't find the location of whl.

By the way, `creating build/bdist.linux-x86_64/wheel/paddlepaddle-0.10.0.dist-info/WHEEL`  seems very slow now, it costs nearly 90 second on my server.

**Comment by Yancey1989** [comment]
Thanks @luotao1 , could you find a whl package under `build/python/dist/`?

**Comment by luotao1** [comment]
Yes, I can find `build/python/dist/paddlepaddle-0.10.0-cp27-cp27mu-linux_x86_64.whl`

**Comment by Yancey1989** [comment]
Yep, we can `pip install build/python/dist/paddlepaddle-0.10.0-cp27-cp27mu-linux_x86_64.whl` and this will install paddlepaddle on your OS.

**Comment by luotao1** [comment]
Yes, but we should print related location information for users.

**Comment by Xreki** [comment]
> Yes, but we should print related location information for users.

Maybe a notice of how to install the `.whl` is also need.

I think `make install` should be retained. Reasons as follows:
- When users want to build a `c-api` library of Paddle with `cmake DWITH_C_API=ON -DWITH_PYTHON=OFF -DCMAKE_PREFIX_INSTALL=xxx ..`, we need to use `make install` to copy the generated libraries to the path specified by `CMAKE_PREFIX_INSTALL`, or they may feel puzzling where to find the libraries.

Furthermore,  I think maybe all the depended `third_party` libraries should be copied to `CMAKE_PREFIX_INSTALL`, because they may need to link these libraries when linking `c-api` library of Paddle. It is another topic.
