### ISSUE TITLE
grad-op should use add-to and zero all grad before backward

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#3689]

**Comment by qingqing01** [comment]
I want to confirm this conclusion. I discussed this problem with @reyoung and @hedaoyuan a few days ago, the conclusion is to use equal operation for gradient computation.

**Comment by dzhwinter** [comment]
As in the design doc [backward](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/backward.md) shows, 
> Share variable between operators or same input variable used in multiple operators leads to a overwrite gradient variable problem.

there are two options. 

1. All grad operator use add-to operator. And the gradient parameter should be clear to zero before every epoch begin. 

2. Backward framework detects the gradient overwrite variable, then replace the overwrite links with a `Generic Add` operator.

need to notice that option 1 save memory in backward graph construction stage, option 2 save memory logic happens after backward construction done.  refer to [note_memory](https://mxnet.incubator.apache.org/architecture/note_memory.html)

**Comment by dzhwinter** [comment]
the first option will reduce memory consumption. But there are some rocks in our road.

1. if we use `+=` operation, we need to clear the memory in every mini-batch before we use them. 
2.we need to support "gradient to gradient". the gradient of `f(f(x))'`, Because we don't know whether one operator will be used as a gradient operator, we need to modify all the `=` operation to `+=`.  
As a conclusion of 1, 2. We need to clear every memory to 0 in every mini-batch. Then we get the third question, is the cost affordable? 

The benefit of memory consumption we can gain through the Op inplace and memory counter solution.  see the detail in [memory model](https://mxnet.incubator.apache.org/architecture/note_memory.html)
