### ISSUE TITLE
Boost library dependency issue for distributed

### ISSUE THREAD

**Issue by zlsh80826** [PaddlePaddle/Paddle#37016]
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
          -> develop branch (1653f99fe29e8e2dc7a6276b46c6e9d26091ee4c)
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
         -> AMD Ryzen 9 3900X/Intel(R) Xeon(R) CPU E5-2698 v4
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
         -> V100
    4）系统环境：请说明系统类型、版本（如Mac OS 10.14）、Python版本
        -> 官方 docker image

- 複現步驟
   1 ) 新增 Dockerfile.test 描述檔
   ```
  FROM paddlepaddle/paddle:latest-dev-cuda11.2-cudnn8-gcc82
  
  RUN cd /opt && git clone https://github.com/PaddlePaddle/Paddle.git
  WORKDIR /opt/Paddle
  
  RUN mkdir build && cd build \
  && cmake .. \
         -DPY_VERSION=3.7 \
         -DWITH_GPU=ON \
         -DWITH_NCCL=ON -DWITH_TESTING=ON -DWITH_DISTRIBUTE=ON \
         -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DWITH_MKL=OFF \
  && make -j`nproc`
   ```
   2 ) ``docker build -f Dockerfile.test -t boost_issue .`` 開始編譯
   3 ) 機率性發生錯誤, 當編譯 fleet_executor.cc 時, boost 還沒準備好時即會出現此錯誤。需要在 fleet_executor.cc 加上 boost 的 dependency
   
![image](https://user-images.githubusercontent.com/14275056/140611108-03929be8-471f-4b30-8d1c-e02fb7d1d126.png)

**Comment by youth123** [comment]
您好，谢谢您的意见，此问题反映了产品性能需进一步优化，我们会尽快排期，感谢您提出的宝贵意见，谢谢。

**Comment by youth123** [comment]
您好，我们这边没有复现出这个问题，怀疑可能是镜像里面没有设置代理，导致boost的包下载有问题。

**Comment by cameronrutherford** [comment]
Hello. We were able to replicate the same issue installing with `-j 16` as the argument to make, building tagged version `1.8.5`. It seems as though building in parallel causes some targets to be built before boost is able to be installed/configured.

After the targets fail to be built, boost is successfully configured and installed. Running `make` again after boost is installed results in the failing target being built successfully, so this is a minor inconvenience.

I echo the suggestion by @zlsh80826 to add boost as a dependency to the necessary targets in order to have boost built + installed beforehand.

In order to reproduce I think the key is to build with a significant number of parallel workers.

**Comment by zlsh80826** [comment]
It seems the bug has been fixed on the latest develope branch.
