### ISSUE TITLE
Make attribute support for std::vector<std::pair<int, int>>

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/Paddle#3877]
Pad op need a attribute named paddings which is `std::vector<std::pair<int, int>>`. 
 So [OperatorBase::AddAttr<T>(...)](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/operator.h#L204) should support for  `std::vector<std::pair<int, int>>`.

**Comment by reyoung** [comment]
@wanghaoshuang @Canpio @qingqing01 

I do not think this type of attribute is necessary since we could use four attributes in this solution, `pad_left`, `pad_right`, `pad_top`, `pad_bottom`. Moreover, if we add type, a list of int pairs, what about float pairs? string pairs? int tuples?

If we adding `list<pair<int, int>>`, it is a trending to make that attribute more and more complex. I don't think it is a good choice.

**Comment by wanghaoshuang** [comment]
@reyoung  `pad_left`, `pad_right`, `pad_top`, `pad_bottom` just suits 2-D tensor. Yes, we can use `vector<int>` instead of `vector<pair<int, int>>`. Which need developer writting python code to transfer `list<tuple>` to `vector<int>` and cpp code to transfer `vector<int>` to vector<pair<int, int>>.
