### ISSUE TITLE
Current gradient checking logic is too brutal

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#4134]
Current implementation accumulates error easily. Because that when computing numerical gradient for each input element, it just sums all difference of perturbed outputs ((pos - neg)/delta/2) to one value. For more accurate estimating, we should build a jacobian matrix for X (input) whose dimension is M*N. M is the size of X and N is the size of Y (output). I have implemented a naive version to clarify this solution, the implementation is far less than optimal. We can discuss here to speed it up and make all cases considered.

**Comment by emailweixu** [comment]
Using double can help

**Comment by lcy-seso** [comment]
I have also encountered some problems may be caused by computation accuracy.

Left of the picutre is softmax output comupted by C++, right of the picture is softmax output computed by numpy. 

![image](https://user-images.githubusercontent.com/5842774/30508366-eed936a6-9ac7-11e7-8860-83c402dfbef4.png)

They are a little differences.  If we sum delta of each dimensions and when layer size is set a large value. It tends to break the check. Currently, layer size in gradient check are always small, because a large layer size is easy to break the gradient check. This is a relative issue :https://github.com/PaddlePaddle/Paddle/issues/4111

**Comment by lcy-seso** [comment]
I am working on implementing `softmax_with_cross_entropy` op, I found when layer size is set from 10 to 40, it is easy to break the gradient check.

```text
Traceback (most recent call last):
  File "test_softmax_with_cross_entropy_op.py", line 38, in test_check_grad
    self.check_grad(["Logits"], "Loss")
  File "/home/caoying/paddle_codes/paddle_github/python/paddle/v2/framework/tests/op_test.py", line 271, in check_grad
    "Gradient Check On %s" % str(cpu_place))
  File "/home/caoying/paddle_codes/paddle_github/python/paddle/v2/framework/tests/op_test.py", line 230, in __assert_is_close
    self.assertLessEqual(max_diff, max_relative_error, err_msg())
AssertionError: Gradient Check On CPUPlace Variable Logits@GRAD max gradient diff 0.038023 over limit 0.005000, the first error element is 1
```

**Comment by lcy-seso** [comment]
related issues: https://github.com/PaddlePaddle/Paddle/issues/4053 https://github.com/PaddlePaddle/Paddle/issues/4118

**Comment by NHZlX** [comment]
I also met the same problem when the layer size gets large enough.

**Comment by lcy-seso** [comment]
related issue https://github.com/PaddlePaddle/Paddle/issues/4283

**Comment by emailweixu** [comment]
Will anyone work on using double for gradient check?

**Comment by pkuyym** [comment]
Sorry for that, I just refined the python part of gradient checker and will push the double thing ASAP.
