### ISSUE TITLE
The need for zero-dimensional tensors.

### ISSUE THREAD

**Issue by AndPuQing** [PaddlePaddle/Paddle#42757]
### 需求描述 Feature Description

I am now trying add Paddle in deepxde(https://github.com/lululxvi/deepxde) as backend. For some reason, we need to distinguish between zero-dimensional tensors and 1D tensors, as follows：

```python
import torch

a = torch.tensor(3)
print(a.ndim) # 0
b = torch.tensor([3])
print(b.ndim) # 1

import paddle
a=paddle.to_tensor([3])
print(a.ndim) # 1
b=paddle.to_tensor(3)
print(b.ndim) # 1
```

**Comment by jzhang533** [comment]
@iclementine is investigating on this.

**Comment by iclementine** [comment]
Currently, paddle has **limited** and **inconsistent** support for zero-dimensional tensors due to a previous design to fake a zero-dimensional tensor with a 1d tensor with shape `[1]`. After that, a lot of APIs has been hacked to deal with zero-dimensional tensors, which is **incorrect** mathematically. 

For example, indexing an 1d tensor with an integer returns a 1d tensor with shape `[1]` instead of a 0d tensor. Reduction on a tensor at all dimensions returns a 1d tensor with shape `[1]` instead of a 0d tensor.

It's a known issue and we are planning on fixing it. But fixing this requires a throughout scanning of all APIs, which might requires some time.

**Comment by AndPuQing** [comment]
Right now I'm using a 1D tensor to simulate a zero-dimensional tensor which is indeed problematic, so expect the problem to be solved. Thank you for your reply

**Comment by zhwesky2010** [comment]
@AndPuQing Hello, is there other API except `to_tensor`? We are considering supporting 0D, but Many APIs need to be modified. If you encounter any problem with the API of 0D, you can report this API to us, and we will support it firstly.

**Comment by zhwesky2010** [comment]
@AndPuQing 你好，飞桨将于2.5版本全面支持0维Tensor，上述反馈的0D问题也将同时解决。

欢迎试用并安装develop 版本的paddle whl包，将体验最新的0维特性：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html
安装命令：
`pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html`

---
Hello, Paddle will fully support the 0-dimensional Tensor in version 2.5, and the 0D issue will also be resolved at the same time.
Welcome to try and install the develop version of the paddle whl package, and you will experience the latest 0-dimensional features: https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux -pip.html
Install Command:
`pip install paddlepaddle-gpu==0.0.0.post112 -f  https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html `
