### ISSUE TITLE
Remove mkldnn related attributes in native ops and set them in passes.

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#43232]
### 需求描述 Feature Description

Remove mkldnn related attributes in native op and add and set them in passes.

**Comment by lidanqing-vv** [comment]
@Silv3S Please link later PRs with this issue.
First proposition PR has been merged: https://github.com/PaddlePaddle/Paddle/pull/42852
Second PR waiting for review: https://github.com/PaddlePaddle/Paddle/pull/43160

**Comment by lidanqing-intel** [comment]
@Silv3S Hi, please related to this issue when you have new PR that removing attributes. Thanks!

**Comment by lidanqing-vv** [comment]
### 1. Baidu has concern with this solution forward and backward compatibility.
Please test follows:

Chinese
1. 旧版本save的，新版本能不能正确执行：a)是能否load起来, b)结果是否正确
2. 新版本save的，旧版本的能不能正确执行：a)是能否load起来, b)结果是否正确

English
1. models saved using old version
   - Could the new code load the old version model ?
   - Is the acc and perf results correct ?
2. models saved using new version
   - Could the old code load the new code saved model ?
   - Is the acc and perf results correct ?
   
Baidu has the concern because in Baidu other business apartments upgrade paddle very slowly so they would like to have two directions compatibility

### 2. If your solution could not pass above compatiblity tests, Baidu propose following solution
目前对于conv，matmul， elementwise系列，有一些部分attribute都是给mkl-dnn的kernel准备的
1） 新增一个mkldnn_xx_op，把对应的attribute放大这个op中
2） pass升级，原来pass里面直接set对应op的attribute，需要先将op名称改下，再set
3） 兼容性方面，需要converter来保证兼容性，以conv为例，旧的模型load起来，如果发现attribute比转移到了mkldnn-conv中，需要把op名称改了； 保存的时候，如果是给新版本用，先不要特殊处理，如果给旧版本用，需要加一个convert，将mkldnn-conv改成conv

### 3. If the current solution could pass the compatibility that's best, if not we can discuss if  Baidu's proposal is light enough.

**Comment by Silv3S** [comment]
I ran multiple tests to check if any error occurs. Luckily all the tests worked.

1. Models saved using old version.
Yes, these models can run new version of code, with deleted attributes. If there was any issue, it should be caught by `PR-CI-Model-benchmark` or `PR-CI_Coverage` in which `test_analyzer_[model-name]` are checking accuracy. Also performance didn't drop, after current 2 PR's (checked via internal validation).

2. Models saved using new version
This case is much harder to test, because I don't have any automated tools. I saved two models by calling `SaveOptimModel()` in `test_analyzer_[model_name]`. First model was created with old code (attributes in base ops). Second model was created with new code (deleted attributes). Then I added test which runs both models and checks differences, similar to `CompareOptimAndOrig()` in _analyzer_image_classification_tester.cc_.
This test was ran twice: with old code and new code. Models were loaded and accuracy results are correct. I can't measure performance in this case, because these tests were ran manually.

Tested attributes/models
- Model: **Resnet50,** attribute: "fuse_residual_connection"
- Model: **VIT-OCR**, attributes: "fused_reshape_Out", "fused_transpose_Out"

Please tell me if this compatibility check is sufficient, and if you have some automated tools to check compatibility I'd be grateful to get feedback.

I will reference this issue in all future PRs related to removing attributes, so in worst case scenario we could quickly revert it.

**Comment by lidanqing-vv** [comment]
@phlrain Hi, hongyu, 

As @Silv3S tested and commented above
The two models: old model and new model (with attributes deleted), ran twice: with old code and new code. Models were loaded and accuracy results are correct. 

It looks deleting attributes in native ops will not cause old code crash. What is your opinion? can the refactoring continue? Second PR also requires Baidu's approvals https://github.com/PaddlePaddle/Paddle/pull/43160https://github.com/PaddlePaddle/Paddle/pull/43160

**Comment by lidanqing-intel** [comment]
@phlrain Hi, hongyu, 
As @Silv3S tested and said above
The two models: old model and new model (with attributes deleted), ran twice: with old code and new code. Models were loaded and accuracy results are correct. 

It looks deleting attributes in native ops will not cause old code crash. What is your opinion? can the refactoring continue? Second PR also requires Baidu's approvals https://github.com/PaddlePaddle/Paddle/pull/43160https://github.com/PaddlePaddle/Paddle/pull/43160

**Comment by yaomichael** [comment]
@lidanqing-intel I think we can close this ticket. Can you do it?
@HongyuLi2018 @jiangjiajun @chenwhql

**Comment by lidanqing-vv** [comment]
Hi, yes I can close this issue
