### ISSUE TITLE
arm编译失败

### ISSUE THREAD

**Issue by cole-dda** [PaddlePaddle/Paddle#43741]
### bug描述 Describe the Bug

在ubuntu 20:04，aarch64上编译，release/2.3，gcc9.4.0 出现如下错误：

Paddle/paddle/fluid/platform/profiler.cc:615:19: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
  615 |   return std::move(thr_events);
      |          ~~~~~~~~~^~~~~~~~~~~~

使用develop终于编译成功了，但是拿到华为的arm服务器上运行，出现：

python/lib/python3.8/site-packages/paddle/fluid/core_noavx.so: ELF load command alignment not page-aligned

如何解决？
编译的服务器为：ubuntu20.04，aarch64
运行的服务器为：centos7.9，aarch64
而且在该服务器中的docker使用ubuntu测试，也是同样的错误

**Comment by qili93** [comment]
hi @cole-dda 建议编译环境和运行环境的 pagesize 要保持一致，或者可以的话最好直接在运行环境里面编译。

`ELF load command alignment not page-aligned` 这个错误是由于编译环境和运行环境下的 pagesize 不一致。

建议可以参考这个 https://github.com/numpy/numpy/issues/16677 ， 里面提到 `This issue was noticed on RHEL8/AArch64 which uses 64 KiB page size. Fedora/AArch64 and Ubuntu/AArch64 use 4 KiB page size.`。 

和你的环境类似，你的编译环境是 ubuntu20.04，aarch64 page size 是4KB， 你的运行环境是 centos7.9，aarch64 对应的 pagesize 是 64KB。
