### ISSUE TITLE
Picodet INT8 is slower than FP32 when inference with MKLDNN

### ISSUE THREAD

**Issue by yeliang2258** [PaddlePaddle/Paddle#44075]
### bug描述 Describe the Bug

Picodet INT8 is slower than FP32 when inference with MKLDNN.

CPU：Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz
thread num：8
FP32：3.09 s
INT8：3.13 s

My model and script :
[picobug.tar.gz](https://github.com/PaddlePaddle/Paddle/files/9039580/picobug.tar.gz)

**Comment by wozna** [comment]
Hi @yeliang2258 I working on improving performance for INT8 model. But as I mentioned before it is very difficult case where we have very small filters in convolution that is why avx512_vnni int8 will not give as so much speed up. So the performance is worse because this is an INT8 conversion overhead. 
We still have few ideas to implement as: 
- fuse conv+depthwise_conv  this will speed up fp32 and int8, 
- checking why elementise_mul does not quantize in one place, 
- fuse elementwise_add + scale

**Comment by yeliang2258** [comment]
Hi @wozna,
In recent tests, it was found that the accuracy of this model is almost 0. Although the speed may not be improved, the accuracy problem still needs to be solved.
The test script is here: https://github.com/PaddlePaddle/PaddleTest/tree/develop/inference/python_api_test/test_int8_model
First run:
```
sh prepare.sh
```
Then:
```
python test_ppyoloe_infer.py --model_path=models/picodet_s_416_coco_npu_quant --reader_config=configs/picodet_reader.yml --precision=int8
```

**Comment by wozna** [comment]
@yeliang2258 this accuracy bug is related to new this new quantization method with `quantize_linear` and `dequantize_linear` isn't it?

**Comment by yeliang2258** [comment]
@wozna No, the accuracy of the quantized model in the old format is also not correct.

**Comment by wozna** [comment]
This PR should fix this issue https://github.com/PaddlePaddle/Paddle/pull/46378. The problem was that even if we have uint8 output we used int8 data type which was associated with a loss of accuracy.
