### ISSUE TITLE
OSError: (External) CUDA error(3), initialization error. 

### ISSUE THREAD

**Issue by Jeremy-lf** [PaddlePaddle/Paddle#44074]
### bug描述 Describe the Bug

![image](https://user-images.githubusercontent.com/45171399/177157739-d7f0c328-5967-49ba-9948-490da8663e5b.png)

OSError: (External) CUDA error(3), initialization error. 
  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:66)

Paddle版本是2.3， PaddleDetection也是2.3，安装好环境第一次跑还是正常的，第二天又跑就成这样了，在PaddleCloud上运行的

**Comment by From00** [comment]
你好，初步判断这是运行的机器环境的问题，与Paddle代码无关。建议可以直接咨询PaddleCloud相关人员，或者告知你是通过什么渠道在使用PaddleCloud的对外服务，我们协助联系对应人员来解决你的问题。

**Comment by cuiff1234** [comment]
我在运行分类、检测和分割任务时偶发的也会爆此错误，是因为paddle=2.3.0第365行左右多写了部分代码和paddle=2.2.0的代码不一样，导致不兼容应该
OSError: (External) CUDA error(3), initialization error. 
  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:243)
  [operator < gaussian_random > error]
