### ISSUE TITLE
SoftmaxWithCrossEntropyOp have conflict when merge

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#4416]

**Comment by emailweixu** [comment]
How can this happen? Shouldn't the merge be blocked by CI because it cannot compile.

**Comment by lcy-seso** [comment]
duplicated with this issue https://github.com/PaddlePaddle/Paddle/issues/4410 . This problem is caused by this merging this PR https://github.com/PaddlePaddle/Paddle/pull/4144 .

I guess because CI system builds the project based on codes in the PR.

https://github.com/PaddlePaddle/Paddle/pull/4144 based on the developing branch before merging this https://github.com/PaddlePaddle/Paddle/pull/3946. And codes in https://github.com/PaddlePaddle/Paddle/pull/4144 does not conflict with  https://github.com/PaddlePaddle/Paddle/pull/3946, so there are no conflicts that will block the merging. Both PR can successfully compile.
