### ISSUE TITLE
FatalError: `Termination signal` is detected by the operating system

### ISSUE THREAD

**Issue by Birdylx** [PaddlePaddle/Paddle#46870]
### bug描述 Describe the Bug

采用多进程时，paddle抛出异常，但是程序可以正常运行，这个异常虽然不会影响程序结果，但是为什么会出现这样的情况呢？

最小复现代码：

```python
import multiprocessing
from tqdm import tqdm
import paddle

class custom_dataset(paddle.io.Dataset):
    def __init__(self):
        super().__init__()
    
    def func(self):
        workers = min(8, multiprocessing.cpu_count())
        data = [i for i in range(5)]
        with multiprocessing.Pool(workers) as p:
            res = list(tqdm(p.imap(f, data), total=len(data)))
        print(res)

def f(x):
    return x*x

if __name__ == '__main__':
    dataset = custom_dataset()
    dataset.func()
```

报错信息：
```
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1665408425 (unix time) try "date -d @1665408425" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x138f) received by PID 5021 (TID 0x7f8e236ed700) from PID 5007 ***]
```

**Comment by heavengate** [comment]
你这个应该跟Dataset没有关系，这个继承Dataset类并没有实现Dataset类的方法，只是实现了一个func，然后调用func，继承任何类这样写都能跑，应该是跟paddle无关的

**Comment by Birdylx** [comment]
@heavengate ，是paddle全局注册的原因，multiprocess预期内的行为被paddle捕获https://github.com/PaddlePaddle/Paddle/issues/36281

**Comment by zhao-sy** [comment]
抛出这个错误之后程序可以继续运行吗

**Comment by lll123github** [comment]
同问，似乎异常被python接收之后程序终止了？（.../PaddleSpeech/examples/aishell3/tts3）

**Comment by nikithakriz** [comment]
I had similar issue while using paddleocr along with multiprocessing


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1710392015 (unix time) try "date -d @1710392015" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e90000cedc) received by PID 53174 (TID 0x7ea416a6db80) from PID 52956 ***]



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::~AnalysisPredictor()
1   paddle::AnalysisPredictor::~AnalysisPredictor()
2   std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()
3   paddle::framework::OpDesc::~OpDesc()
4   std::_Hashtable<std::string, std::pair<std::string const, paddle::variant<paddle::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string > >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, std::vector<double, std::allocator<double> >, paddle::framework::VarDesc*, std::vector<paddle::framework::VarDesc*, std::allocator<paddle::framework::VarDesc*> >, double, paddle::experimental::ScalarBase<paddle::Tensor>, std::vector<paddle::experimental::ScalarBase<paddle::Tensor>, std::allocator<paddle::experimental::ScalarBase<paddle::Tensor> > >, pir::Block*, std::vector<pir::Value, std::allocator<pir::Value> > > >, std::allocator<std::pair<std::string const, paddle::variant<paddle::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string > >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, std::vector<double, std::allocator<double> >, paddle::framework::VarDesc*, std::vector<paddle::framework::VarDesc*, std::allocator<paddle::framework::VarDesc*> >, double, paddle::experimental::ScalarBase<paddle::Tensor>, std::vector<paddle::experimental::ScalarBase<paddle::Tensor>, std::allocator<paddle::experimental::ScalarBase<paddle::Tensor> > >, pir::Block*, std::vector<pir::Value, std::allocator<pir::Value> > > > >, std::__detail::_Select1st, std::equal_to<std::string >, std::hash<std::string >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::~_Hashtable()
5   std::vector<std::string, std::allocator<std::string > >::~vector()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1710392015 (unix time) try "date -d @1710392015" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e90000cedc) received by PID 53176 (TID 0x72ef72873b80) from PID 52956 ***]

**Comment by aashishpokharel** [comment]
> I had similar issue while using paddleocr along with multiprocessing
> 
> ## C++ Traceback (most recent call last):
> No stack trace in paddle, may be caused by external reasons.
> 
> ## Error Message Summary:
> FatalError: `Termination signal` is detected by the operating system. [TimeInfo: *** Aborted at 1710392015 (unix time) try "date -d @1710392015" if you are using GNU date ***] [SignalInfo: *** SIGTERM (@0x3e90000cedc) received by PID 53174 (TID 0x7ea416a6db80) from PID 52956 ***]
> 
> ## C++ Traceback (most recent call last):
> 0 paddle::AnalysisPredictor::~AnalysisPredictor() 1 paddle::AnalysisPredictor::~AnalysisPredictor() 2 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() 3 paddle::framework::OpDesc::~OpDesc() 4 std::_Hashtable<std::string, std::pair<std::string const, paddle::variant<paddle::blank, int, float, std::string, std::vector<int, std::allocator >, std::vector<float, std::allocator >, std::vector<std::string, std::allocator<std::string > >, bool, std::vector<bool, std::allocator >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocatorpaddle::framework::BlockDesc* >, std::vector<long, std::allocator >, std::vector<double, std::allocator >, paddle::framework::VarDesc*, std::vector<paddle::framework::VarDesc*, std::allocatorpaddle::framework::VarDesc* >, double, paddle::experimental::ScalarBasepaddle::Tensor, std::vector<paddle::experimental::ScalarBasepaddle::Tensor, std::allocator<paddle::experimental::ScalarBasepaddle::Tensor > >, pir::Block*, std::vector<pir::Value, std::allocatorpir::Value > > >, std::allocator<std::pair<std::string const, paddle::variant<paddle::blank, int, float, std::string, std::vector<int, std::allocator >, std::vector<float, std::allocator >, std::vector<std::string, std::allocator<std::string > >, bool, std::vector<bool, std::allocator >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocatorpaddle::framework::BlockDesc* >, std::vector<long, std::allocator >, std::vector<double, std::allocator >, paddle::framework::VarDesc*, std::vector<paddle::framework::VarDesc*, std::allocatorpaddle::framework::VarDesc* >, double, paddle::experimental::ScalarBasepaddle::Tensor, std::vector<paddle::experimental::ScalarBasepaddle::Tensor, std::allocator<paddle::experimental::ScalarBasepaddle::Tensor > >, pir::Block*, std::vector<pir::Value, std::allocatorpir::Value > > > >, std::__detail::_Select1st, std::equal_to<std::string >, std::hash<std::string >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::~_Hashtable() 5 std::vector<std::string, std::allocator<std::string > >::~vector()
> 
> ## Error Message Summary:
> FatalError: `Termination signal` is detected by the operating system. [TimeInfo: *** Aborted at 1710392015 (unix time) try "date -d @1710392015" if you are using GNU date ***] [SignalInfo: *** SIGTERM (@0x3e90000cedc) received by PID 53176 (TID 0x72ef72873b80) from PID 52956 ***]

has this been solved?

**Comment by chelseaztq** [comment]
同样的问题，我有个fastapi的服务，上传解析pdf，因为paddle本身的解析pdf到图片这一步速度有点慢，我的pdf很大很大，
我就开启了

def process_page(self, args):
        file_path, page_num, matrix_scale = args
        with fitz.open(file_path) as pdf:
            page = pdf[page_num]
            mat = fitz.Matrix(matrix_scale, matrix_scale)
            pm = page.get_pixmap(matrix=mat, alpha=False)

            # 如果宽度或高度超过2000像素，则不再放大图片
            if pm.width > 2000 or pm.height > 2000:
                pm = page.get_pixmap(matrix=fitz.Matrix(1, 1), alpha=False)

            # 直接转换为numpy数组
            img = np.frombuffer(pm.samples, dtype=np.uint8).reshape(pm.height, pm.width, 3)
            return img

    def load_file(self, file_path, start_page=0, end_page=None):
        with fitz.open(file_path) as pdf:
            if end_page is None:
                end_page = pdf.page_count

            tasks = [(file_path, pg, 2) for pg in range(start_page, end_page)]

        pool_num = 4 if end_page >= 8 else 1
        with Pool(pool_num) as pool:
            imgs = list(tqdm(pool.imap(self.process_page, tasks), total=len(tasks)))

        return imgs
        
        
      多进程去处理，然后报了 Termination signal 这个错误，结果后面ocr还是正常进行了
      
      
[37m10/31 03:39:20   INFO 38 --- [ThreadPoolExecutor-0_0] ocr_server Logger : [0/1] /RagProject/src/services/ocr/input/202410/SCP_1851830641063997440.pdf[0m

  0%|          | 0/20 [00:00<?, ?it/s]
  5%|▌         | 1/20 [00:00<00:05,  3.38it/s]
 10%|█         | 2/20 [00:00<00:03,  5.24it/s]
 25%|██▌       | 5/20 [00:00<00:01, 12.72it/s]
 35%|███▌      | 7/20 [00:00<00:00, 14.82it/s]
 45%|████▌     | 9/20 [00:00<00:00, 14.11it/s]
 60%|██████    | 12/20 [00:00<00:00, 16.91it/s]
 70%|███████   | 14/20 [00:01<00:00, 17.53it/s]
 80%|████████  | 16/20 [00:01<00:00, 17.58it/s]
 90%|█████████ | 18/20 [00:01<00:00, 16.45it/s]
100%|██████████| 20/20 [00:01<00:00, 14.87it/s]


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1730345962 (unix time) try "date -d @1730345962" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x26) received by PID 256 (TID 0x7fe035ffb700) from PID 38 ***]



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1730345962 (unix time) try "date -d @1730345962" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x26) received by PID 250 (TID 0x7fe035ffb700) from PID 38 ***]



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1730345962 (unix time) try "date -d @1730345962" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x26) received by PID 252 (TID 0x7fe035ffb700) from PID 38 ***]



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1730345962 (unix time) try "date -d @1730345962" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x26) received by PID 254 (TID 0x7fe035ffb700) from PID 38 ***]


  0%|          | 0/20 [00:00<?, ?it/s][2024/10/31 03:39:23] ppocr DEBUG: dt_boxes num : 16, elapsed : 0.32988834381103516
[2024/10/31 03:39:23] ppocr DEBUG: rec_res num  : 16, elapsed : 0.1378486156463623

  5%|▌         | 1/20 [00:00<00:12,  1.49it/s][2024/10/31 03:39:24] ppocr DEBUG: dt_boxes num : 7, elapsed : 0.25750041007995605
[2024/10/31 03:39:24] ppocr DEBUG: rec_res num  : 7, elapsed : 0.08520793914794922

 10%|█         | 2/20 [00:01<00:10,  1.75it/s][2024/10/31 03:39:24] ppocr DEBUG: dt_boxes num : 30, elapsed : 0.33980703353881836
[2024/10/31 03:39:24] ppocr DEBUG: rec_res num  : 30, elapsed : 0.1983323097229004

 15%|█▌        | 3/20 [00:01<00:10,  1.57it/s][2024/10/31 03:39:25] ppocr DEBUG: dt_boxes num : 27, elapsed : 0.31505346298217773
[2024/10/31 03:39:25] ppocr DEBUG: rec_res num  : 27, elapsed : 0.31624722480773926

 20%|██        | 4/20 [00:02<00:11,  1.39it/s][2024/10/31 03:39:26] ppocr DEBUG: dt_boxes num : 65, elapsed : 0.3484964370727539
[2024/10/31 03:39:26] ppocr DEBUG: rec_res num  : 65, elapsed : 0.4560055732727051
[2024/10/31 03:39:27] ppocr DEBUG: dt_boxes num : 33, elapse : 0.2669711112976074
[2024/10/31 03:39:27] ppocr DEBUG: rec_res num  : 33, elapse : 0.16526007652282715
[2024/10/31 03:39:27] ppocr DEBUG: dt_boxes num : 13, elapse : 0.21416306495666504
[2024/10/31 03:39:27] ppocr DEBUG: rec_res num  : 13, elapse : 0.11771178245544434

 25%|██▌       | 5/20 [00:05<00:19,  1.32s/it][2024/10/31 03:39:28] ppocr DEBUG: dt_boxes num : 53, elapsed : 0.3158142566680908
[2024/10/31 03:39:28] ppocr DEBUG: rec_res num  : 53, elapsed : 0.3660154342651367

 30%|███       | 6/20 [00:06<00:16,  1.18s/it][2024/10/31 03:39:29] ppocr DEBUG: dt_boxes num : 30, elapsed : 0.2972269058227539
[2024/10/31 03:39:29] ppocr DEBUG: rec_res num  : 30, elapsed : 0.3390498161315918

 35%|███▌      | 7/20 [00:06<00:13,  1.07s/it][2024/10/31 03:39:30] ppocr DEBUG: dt_boxes num : 32, elapsed : 0.2926619052886963
[2024/10/31 03:39:30] ppocr DEBUG: rec_res num  : 32, elapsed : 0.4064459800720215

 40%|████      | 8/20 [00:07<00:12,  1.02s/it][2024/10/31 03:39:31] ppocr DEBUG: dt_boxes num : 31, elapsed : 0.34432029724121094
[2024/10/31 03:39:31] ppocr DEBUG: rec_res num  : 31, elapsed : 0.41395092010498047

 45%|████▌     | 9/20 [00:08<00:11,  1.02s/it][2024/10/31 03:39:32] ppocr DEBUG: dt_boxes num : 31, elapsed : 0.299304723739624
[2024/10/31 03:39:32] ppocr DEBUG: rec_res num  : 31, elapsed : 0.40767645835876465

 50%|█████     | 10/20 [00:09<00:09,  1.00it/s][2024/10/31 03:39:33] ppocr DEBUG: dt_boxes num : 32, elapsed : 0.33977341651916504
[2024/10/31 03:39:33] ppocr DEBUG: rec_res num  : 32, elapsed : 0.3717994689941406

 55%|█████▌    | 11/20 [00:10<00:08,  1.02it/s][2024/10/31 03:39:34] ppocr DEBUG: dt_boxes num : 130, elapsed : 0.3709588050842285
[2024/10/31 03:39:35] ppocr DEBUG: rec_res num  : 130, elapsed : 0.8776435852050781
[2024/10/31 03:39:35] ppocr DEBUG: dt_boxes num : 115, elapse : 0.1828477382659912
[2024/10/31 03:39:36] ppocr DEBUG: rec_res num  : 115, elapse : 0.64316725730896

 60%|██████    | 12/20 [00:14<00:14,  1.78s/it][2024/10/31 03:39:37] ppocr DEBUG: dt_boxes num : 33, elapsed : 0.3218662738800049
[2024/10/31 03:39:38] ppocr DEBUG: rec_res num  : 33, elapsed : 0.3480720520019531

 65%|██████▌   | 13/20 [00:15<00:10,  1.52s/it][2024/10/31 03:39:38] ppocr DEBUG: dt_boxes num : 33, elapsed : 0.29133105278015137
[2024/10/31 03:39:39] ppocr DEBUG: rec_res num  : 33, elapsed : 0.3972787857055664

 70%|███████   | 14/20 [00:16<00:08,  1.34s/it][2024/10/31 03:39:39] ppocr DEBUG: dt_boxes num : 33, elapsed : 0.28573060035705566
[2024/10/31 03:39:39] ppocr DEBUG: rec_res num  : 33, elapsed : 0.37291383743286133

 75%|███████▌  | 15/20 [00:17<00:06,  1.21s/it][2024/10/31 03:39:40] ppocr DEBUG: dt_boxes num : 100, elapsed : 0.33661937713623047
[2024/10/31 03:39:41] ppocr DEBUG: rec_res num  : 100, elapsed : 0.6417088508605957
[2024/10/31 03:39:41] ppocr DEBUG: dt_boxes num : 88, elapse : 0.13771295547485352
[2024/10/31 03:39:42] ppocr DEBUG: rec_res num  : 88, elapse : 0.44237327575683594

 80%|████████  | 16/20 [00:19<00:06,  1.63s/it][2024/10/31 03:39:43] ppocr DEBUG: dt_boxes num : 52, elapsed : 0.3299088478088379
[2024/10/31 03:39:43] ppocr DEBUG: rec_res num  : 52, elapsed : 0.4852447509765625
[2024/10/31 03:39:43] ppocr DEBUG: dt_boxes num : 30, elapse : 0.14751148223876953
[2024/10/31 03:39:44] ppocr DEBUG: rec_res num  : 30, elapse : 0.1941547393798828

 85%|████████▌ | 17/20 [00:21<00:04,  1.64s/it][2024/10/31 03:39:44] ppocr DEBUG: dt_boxes num : 73, elapsed : 0.2949976921081543
[2024/10/31 03:39:45] ppocr DEBUG: rec_res num  : 73, elapsed : 0.46645045280456543
[2024/10/31 03:39:45] ppocr DEBUG: dt_boxes num : 25, elapse : 0.3742687702178955
[2024/10/31 03:39:45] ppocr DEBUG: rec_res num  : 25, elapse : 0.12129712104797363
[2024/10/31 03:39:46] ppocr DEBUG: dt_boxes num : 25, elapse : 0.35524940490722656
[2024/10/31 03:39:46] ppocr DEBUG: rec_res num  : 25, elapse : 0.1271367073059082

 90%|█████████ | 18/20 [00:23<00:03,  1.91s/it][2024/10/31 03:39:47] ppocr DEBUG: dt_boxes num : 4, elapsed : 0.2327885627746582
[2024/10/31 03:39:47] ppocr DEBUG: rec_res num  : 4, elapsed : 0.06231045722961426

 95%|█████████▌| 19/20 [00:24<00:01,  1.47s/it][2024/10/31 03:39:47] ppocr DEBUG: dt_boxes num : 13, elapsed : 0.23354244232177734
[2024/10/31 03:39:47] ppocr DEBUG: rec_res num  : 13, elapsed : 0.08709454536437988

100%|██████████| 20/20 [00:24<00:00,  1.17s/it]
100%|██████████| 20/20 [00:24<00:00,  1.24s/it]
[37m10/31 03:39:47   INFO 38 --- [ThreadPoolExecutor-0_0] ocr_server Logger : finish OCR parse,start concat result[0m

**Comment by tmzncty** [comment]
同样的问题，我也是多进程paddle然后输出完成全部结果后报错。
Paddle Version: 3.0.0-rc1
CUDA Device: gpu:0
Running verify PaddlePaddle program ... 
I0212 11:59:56.452140 3425519 pir_interpreter.cc:1508] New Executor is Running ...
W0212 11:59:56.458463 3425519 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 12.6, Runtime API Version: 11.8
W0212 11:59:56.459182 3425519 gpu_resources.cc:164] device: 0, cuDNN Version: 8.6.
I0212 11:59:56.666364 3425519 pir_interpreter.cc:1531] pir interpreter is running by multi-thread mode ...
PaddlePaddle works well on 1 GPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::detailv3::sherwood_v3_table<std::pair<std::string, paddle::flat_hash_map<phi::KernelKey, phi::Kernel, phi::KernelKey::Hash, std::equal_to<phi::KernelKey>, std::allocator<std::pair<phi::KernelKey, phi::Kernel> > > >, std::string, std::hash<std::string >, paddle::detailv3::KeyOrValueHasher<std::string, std::pair<std::string, paddle::flat_hash_map<phi::KernelKey, phi::Kernel, phi::KernelKey::Hash, std::equal_to<phi::KernelKey>, std::allocator<std::pair<phi::KernelKey, phi::Kernel> > > >, std::hash<std::string > >, std::equal_to<std::string >, paddle::detailv3::KeyOrValueEquality<std::string, std::pair<std::string, paddle::flat_hash_map<phi::KernelKey, phi::Kernel, phi::KernelKey::Hash, std::equal_to<phi::KernelKey>, std::allocator<std::pair<phi::KernelKey, phi::Kernel> > > >, std::equal_to<std::string > >, std::allocator<std::pair<std::string, paddle::flat_hash_map<phi::KernelKey, phi::Kernel, phi::KernelKey::Hash, std::equal_to<phi::KernelKey>, std::allocator<std::pair<phi::KernelKey, phi::Kernel> > > > >, std::allocator<paddle::detailv3::sherwood_v3_entry<std::pair<std::string, paddle::flat_hash_map<phi::KernelKey, phi::Kernel, phi::KernelKey::Hash, std::equal_to<phi::KernelKey>, std::allocator<std::pair<phi::KernelKey, phi::Kernel> > > > > > >::clear()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1739332617 (unix time) try "date -d @1739332617" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e80033f660) received by PID 3405599 (TID 0x7fbb7308f740) from PID 3405408 ***]



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::detailv3::sherwood_v3_table<std::pair<std::string, paddle::flat_hash_map<phi::KernelKey, phi::Kernel, phi::KernelKey::Hash, std::equal_to<phi::KernelKey>, std::allocator<std::pair<phi::KernelKey, phi::Kernel> > > >, std::string, std::hash<std::string >, paddle::detailv3::KeyOrValueHasher<std::string, std::pair<std::string, paddle::flat_hash_map<phi::KernelKey, phi::Kernel, phi::KernelKey::Hash, std::equal_to<phi::KernelKey>, std::allocator<std::pair<phi::KernelKey, phi::Kernel> > > >, std::hash<std::string > >, std::equal_to<std::string >, paddle::detailv3::KeyOrValueEquality<std::string, std::pair<std::string, paddle::flat_hash_map<phi::KernelKey, phi::Kernel, phi::KernelKey::Hash, std::equal_to<phi::KernelKey>, std::allocator<std::pair<phi::KernelKey, phi::Kernel> > > >, std::equal_to<std::string > >, std::allocator<std::pair<std::string, paddle::flat_hash_map<phi::KernelKey, phi::Kernel, phi::KernelKey::Hash, std::equal_to<phi::KernelKey>, std::allocator<std::pair<phi::KernelKey, phi::Kernel> > > > >, std::allocator<paddle::detailv3::sherwood_v3_entry<std::pair<std::string, paddle::flat_hash_map<phi::KernelKey, phi::Kernel, phi::KernelKey::Hash, std::equal_to<phi::KernelKey>, std::allocator<std::pair<phi::KernelKey, phi::Kernel> > > > > > >::clear()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1739332617 (unix time) try "date -d @1739332617" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e80033f660) received by PID 3405899 (TID 0x7fec9fe2a740) from PID 3405408 ***]



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::detailv3::sherwood_v3_table<std::pair<std::string, paddle::flat_hash_map<phi::KernelKey, phi::Kernel, phi::KernelKey::Hash, std::equal_to<phi::KernelKey>, std::allocator<std::pair<phi::KernelKey, phi::Kernel> > > >, std::string, std::hash<std::string >, paddle::detailv3::KeyOrValueHasher<std::string, std::pair<std::string, paddle::flat_hash_map<phi::KernelKey, phi::Kernel, phi::KernelKey::Hash, std::equal_to<phi::KernelKey>, std::allocator<std::pair<phi::KernelKey, phi::Kernel> > > >, std::hash<std::string > >, std::equal_to<std::string >, paddle::detailv3::KeyOrValueEquality<std::string, std::pair<std::string, paddle::flat_hash_map<phi::KernelKey, phi::Kernel, phi::KernelKey::Hash, std::equal_to<phi::KernelKey>, std::allocator<std::pair<phi::KernelKey, phi::Kernel> > > >, std::equal_to<std::string > >, std::allocator<std::pair<std::string, paddle::flat_hash_map<phi::KernelKey, phi::Kernel, phi::KernelKey::Hash, std::equal_to<phi::KernelKey>, std::allocator<std::pair<phi::KernelKey, phi::Kernel> > > > >, std::allocator<paddle::detailv3::sherwood_v3_entry<std::pair<std::string, paddle::flat_hash_map<phi::KernelKey, phi::Kernel, phi::KernelKey::Hash, std::equal_to<phi::KernelKey>, std::allocator<std::pair<phi::KernelKey, phi::Kernel> > > > > > >::clear()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1739332617 (unix time) try "date -d @1739332617" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e80033f660) received by PID 3405836 (TID 0x7f516ec35740) from PID 3405408 ***]
