### ISSUE TITLE
Learning rate scheduler

### ISSUE THREAD

**Issue by abhinavarora** [PaddlePaddle/Paddle#4705]
see paddle/./parameter/LearningRateScheduler.h

**Comment by qingqing01** [comment]
@abhinavarora 

I'm not sure whether the learning rate scheduler will be implemented by opeartor, since they are scalar calculation for learning rate based on epoc number ( or mini-batch number, or the processed instances number) and some other scalar arguments.  Maybe we can make a survey how to do learning rate scheduler.

**Comment by abhinavarora** [comment]
@qingqing01 I had a discussion yesterday with @reyoung  and @jacquesqiao regarding this. We believed that one single step of the learning rate scheduler can be a graph operator that will take the global epoch number as an input. These operators can be added to the graph by a Python API that we will have to define. I will do a survey on this implementation and then prepare a design doc. Once I have the design doc ready, I will send it to all of you for a review.
