### ISSUE TITLE
Semantic Role Labeling in new C++ core

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#4760]
To meet our release goal, here we list the minimum requirements for each component.

### Op requirements
- [x] Feed Op, Fetch Op
- [x] embedding (look up op)   @qingqing01 (dense table)
- [x] crf op  @lcy-seso doing
- [x] viterbi decoding op @lcy-seso doing
- [x] lstm op @qingqing01 doing
- [x] momentum, sgd op
- [x] regularization op @abhinavarora doing

**Comment by lcy-seso** [comment]
Maybe we still need the feature that some operators run on GPU device **while the CRF runs on CPU device** because it takes time to write GPU codes for the CRF operator. The first version of the CRF operator only runs on CPU device.

If we decide not to support the above feature in the first release, the SRL demo has to force all the operators running on CPU device. Maybe it is acceptable for the first release. I am not sure.
