### ISSUE TITLE
支持python3.11问题

### ISSUE THREAD

**Issue by wangyexiang** [PaddlePaddle/Paddle#48200]
### 请提出你的问题 Please ask your question

请问一下，什么时候才能在python3.11上跑代码呢？

**Comment by gongel** [comment]
你好，感谢你的反馈，3.11已在支持中。请等待我们的发布，感谢。

**Comment by PythonTryHard** [comment]
> 你好，感谢你的反馈，3.11已在支持中。请等待我们的发布，感谢。

With what you've said, when can we expect pre-built wheels for Python 3.11? Version 2.4.1 has been released 7hrs ago (as of writing) and the pre-built stops at Python 3.10.

**Comment by monkeycc** [comment]
请问一下，什么时候才能在python3.11上跑代码呢？

**Comment by haobibo** [comment]
@gongel Pytorch and TF now supports 3.11 and have wheels on pypi, how's it going for paddle after 3 months?

**Comment by gongel** [comment]
Version 2.6 will support python 3.11.

**Comment by haobibo** [comment]
@gongel  When is version 2.6 expected to be released (or RC)?

**Comment by gongel** [comment]
2.6 RC

**Comment by haobibo** [comment]
> 2.6 RC

At what time is 2.6 RC is expected to be publicly available?

**Comment by glenn-jocher** [comment]
@gongel +1 for Python 3.11 pip package support. We can't run Python 3.11 CI for Ultralytics [YOLOv8](https://github.com/ultralytics/ultralytics) because `paddlepaddle` fails to install:

https://github.com/ultralytics/ultralytics/actions/runs/5490845075/jobs/10006774133?pr=3589
<img width="1659" alt="Screenshot 2023-07-08 at 00 02 43" src="https://github.com/PaddlePaddle/Paddle/assets/26833433/e2a048a5-7d45-44d0-b6b2-08f3799b25d9">

**Comment by gongel** [comment]
Hello all，Py 3.11  paddlepaddle develop wheel  is coming～

[https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html](https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html)

**Comment by Davidy22** [comment]
If there's anything I can do to help aid the release of a version supporting 3.11, I can pitch in to help clear blockers. I have personal interest in this being available for 3.11 and am willing to help expedite the process.
