### ISSUE TITLE
Image clasification performance drop

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#48633]
### 问题描述 Please describe your issue

Commit https://github.com/PaddlePaddle/Paddle/commit/c923e6c9b1e69cd5cbd0aa76a3982358538c7c4d seems to be responsible for the performance drop in image recognition applications.
This is especially visible in the case of application operation:
paddle_paddle/build/paddle/fluid/inference/tests/api/test_analyzer_int8_image_classification
and
paddle_paddle/paddle/fluid/inference/tests/api/test_analyzer_quant_image_classification

Measurements were made on machines with different architectures:
SKX, CLX, CPX and SPR. The decrease in performance is observed on all of them.

Measurements were made for one thread and batch=1

The tables with results presented below show that the efficiency values ​​before the indicated commit are clearly higher
#### results:
![SKX]
![image](https://user-images.githubusercontent.com/10847947/205061420-5ada2187-1afe-4bac-ab00-2bb7271f51e0.png)

![CLX]
![image](https://user-images.githubusercontent.com/10847947/205061486-1d30a69d-7128-4c12-ac0d-9987b4c7e6b7.png)

![CPX]
![image](https://user-images.githubusercontent.com/10847947/205061667-a899e46a-3e2f-4f77-9902-2829a32b406b.png)

![SPR]
![image](https://user-images.githubusercontent.com/10847947/205062057-e4c235e3-7471-492a-b92e-adba5fb55c40.png)

**Comment by cxxly** [comment]
@YuanRisheng

**Comment by YuanRisheng** [comment]
This performace issue and the other one(https://github.com/PaddlePaddle/Paddle/issues/48636) is the same reason. It is because the unreasonable design for getting ExtraAttr in OneDNN kernels. We will think about new design after all OneDNN kernels migrate to PHI. Thank you.

**Comment by chenwhql** [comment]
This PR leads to a decline in the performance of the image clasification model because the Conv op has been changed, and the root cause of this change is that mkldnn did not develop the corresponding fusion operator when it needed to implement conv-related fusion functions, but adopted A "shortcut" that directly adds the function that needs to be fuse to the basic conv op, and adds some non-standard input parameters to the conv. In order to ensure the cross-device consistency and standardization of the operator signature, c923e6c stores redundant input and attributes into OneDNNContext and takes them out for use in the kernel, and this process will introduce some preparation and value-taking overhead, which leads to this problem.

But the fundamental problem still lies in the fact that mkldnn needs to increase the fusion operator in a reasonable way instead of patching the fusion function to the basic operator. We split the conv operator in https://github.com/PaddlePaddle/Paddle/pull/47579, but this is not the last non-compliant operator of mkldnn. I hope you can also standardize operators like this and split them into basic operators and fusion operators.

**Comment by chenwhql** [comment]
And https://github.com/PaddlePaddle/Paddle/pull/47579 is able to resolve the performance degradation introduced by https://github.com/PaddlePaddle/Paddle/commit/c923e6c9b1e69cd5cbd0aa76a3982358538c7c4d, because there is no need to prepare additional input parameters for conv, here will directly call fuse_conv

**Comment by pmajchrzak** [comment]
For information: @jczaja

**Comment by yaomichael** [comment]
> But the fundamental problem still lies in the fact that mkldnn needs to increase the fusion operator in a reasonable way instead of patching the fusion function to the basic operator. We split the conv operator in #47579, but this is not the last non-compliant operator of mkldnn. I hope you can also standardize operators like this and split them into basic operators and fusion operators.

@chenwhql do you mean we need to identify other PHI operators needing to split, or, do you already have a list of these operators to split? I hope not all operators need to split. :)
