### ISSUE TITLE
reader support reading data from native HDFS without downloading the data to local disk

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#5011]
Distributed training jobs are likely to use training data from some distributed storage services like AWS S3 or Hadoop HDFS. And, HDFS is widely used for companies. A simple way is to download a sub set of the files to local disk, and then write a `reader` to read from local file list, which is not very efficient.

So we need to read data directly from HDFS instead. To do this, we need to implement a base reader or decorator that can use a Hadoop client to pipe data:

```python
ps = subprocess.Popen(('hadoop', 'fs', '-cat', your_file_path_or_glob), stdout=subprocess.PIPE)
# read data from ps and do user parse functions
ps.wait()
```

**Comment by helinwang** [comment]
Agree this is very necessary.

If this is targeted for the code after refactor (otherwise probably would be deprecated, since in the [distributed training design doc](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/refactor/distributed_architecture.md#distributed-training-architecture), there will be a single Python instance max, i.e., only one node max will run Python), then I suggest implementing it as a C++ OP.

Another option could be mounting HDFS locally (by Kubernetes or by admin if not using Kubernetes).
