### ISSUE TITLE
Models should not be saved by parameters.to_tar() in paddle.v2.model

### ISSUE THREAD

**Issue by pengli09** [PaddlePaddle/Paddle#5032]
`parameters.to_tar()` is used in [python/paddle/v2/model.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/model.py#L68) to save models. However, extra operations are needed if certain settings are used, e.g., model average is on. Therefore, [python/paddle/v2/trainer.py:SGD.save_parameter_to_tar()](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/trainer.py#L117) should be used instead. Otherwise, these settings will not take effect.

**Comment by helinwang** [comment]
Thanks for finding the problem and providing the detailed description! I will fix it when got time (probably after a 10/31 deadline). Please feel free to send a PR in the meantime if you got time, I will be happy to review it.

**Comment by helinwang** [comment]
@pengli09 thanks for the finding! SGD trainer is just one kind of trainer, there might be different kinds of trainers. It seems that the model saving probably should be done by trainer, not `model.save_model`. Since `model.save_model` is not actually used anywhere, how do you think about removing the method?

**Comment by pengli09** [comment]
I think removing it is fine.
