### ISSUE TITLE
windows使用paddle报错: RuntimeError: (PreconditionNotMet) The third-party dynamic library

### ISSUE THREAD

**Issue by jdyjjj** [PaddlePaddle/Paddle#50588]
### bug描述 Describe the Bug

![image](https://user-images.githubusercontent.com/73057174/219389909-cbb617ca-02c1-4791-aa35-84f1b0fa0755.png)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at ..\paddle\phi\backends\dynload\dynamic_loader.cc:305)
code is followed:
![image](https://user-images.githubusercontent.com/73057174/219391498-04aa8503-a17e-4bd7-9dd0-173373837be3.png)

 

### 其他补充信息 Additional Supplementary Information

运行os：windows10
paddlepaddle-gpu        2.4.0
CUDA：11.6
torch： 1.12.1+cu116

**Comment by LiuChiachi** [comment]
看报错信息是你的cuda环境和安装的paddle的不匹配的原因

**Comment by jdyjjj** [comment]
感谢，换了版本之后确实解决问题了

**Comment by kognyouze123** [comment]
> 请问换的哪个版本
我现在也是同样报错

**Comment by kognyouze123** [comment]
> 感谢，换了版本之后确实解决问题了

请问换的哪个版本
我现在也是同样报错
运行os：windows10
paddlepaddle-gpu 2.4.2
CUDA：11.6 cudnn 8.4

**Comment by zoldaten** [comment]
i have the same issue with paddlepaddle-gpu==2.6.1

fixed with cuda 11.7 installed and cudnn 8.9.7.

rename and move zlibwapi.dll:
I was able to find a copy of the missing zlib DLL in the NVIDIA Nsight directory:
C:\Program Files\NVIDIA Corporation\Nsight Systems 2022.4.2\host-windows-x64\zlib.dll
I copied and renamed it to:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\zlibwapi.dll
*see https://stackoverflow.com/questions/72356588/could-not-locate-zlibwapi-dll-please-make-sure-it-is-in-your-library-path

more related links:
https://docs.nvidia.com/deeplearning/cudnn/latest/installation/windows.html
https://developer.nvidia.com/rdp/cudnn-archive
