### ISSUE TITLE
is paddle.infer()  thread safe 

### ISSUE THREAD

**Issue by liyuanhangsc** [PaddlePaddle/Paddle#5072]
can we call paddle.infer() in a multi-thread environment and get the right predict value?

**Comment by rulai-huajunzeng** [comment]
I have this question too. Actually I did some tests on v0.11.0 and found out the inference is NOT thread safe. This was a long existing problem since 0.9.0. Hope there is a fix for that.

**Comment by rulai-huajunzeng** [comment]
@emailweixu Currently we are greatly affected by this issue. Although there is workaround to use multi-process instead of multi-thread, multi-process has its own problem, and in some cases it's not an acceptable solution. 

Another point to make is, although the existence of GIL prevent the multi-threading of pure python code, it doesn't prevent the multi-threading of I/O operations and numeric operations, and so multi-threading is still a good solution in many cases.

**Comment by emailweixu** [comment]
Are you using paddle.v2.infer? If so, you can use paddle.v2.Inference directly. You can create several Inference object in the beginning. Then you can use different Inference object in different thread. However, there is a limitation of the current inference API in python. The parameters are duplicated across different Inference object. If you have a very big model, this may consume too much memory.

To get maximal efficiency, you can use C-API for inference, which is documented here https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/examples/model_inference/README.md

**Comment by rulai-huajunzeng** [comment]
Thanks a lot! This looks like a good workaround. I will try that and see if it works. Please also let me know if there is a plan to share parameters between Inference objects using v2 API.

**Comment by bdbaigc** [comment]
came across same problem

following function in  /usr/local/lib/python3.7/dist-packages/paddle_serving_app/local_predict.py  is not thread safe
def predict(self, feed=None, fetch=None, batch=False, log_id=0):

can someone tell me how to fix this

**Comment by bdbaigc** [comment]
> 

set concurrency 1  in config.yml and problem not appear gain. seems paddle-serving predict function is not thread-safe
