### ISSUE TITLE
Several operators failed when change backward unit tests framework

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#5101]
After PR #5027, several op tests are failed. They are:
* test_cross_entropy_op
* test_softmax_with_cross_entropy_op
* test_gru_unit_op

**Comment by QiJune** [comment]
Since we divide the running of the neural network into compile-time and run-time, we must set correct variable type and shape in compile-time. And the run-time, the ProgramDesc is passed to Executor. The LoDTensor/SelectedRows in Variable will be created in before Executor Running. At run-time infershape and compute, we will only get LoDTensor/SelectedRows, and not create them.
NetOp will be removed soon.
Follow unit tests need to be rewritten:
- test_cond_py
- test_recurrent_py
- test_dynamic_recurrent_py
