### ISSUE TITLE
单机多卡训练时，遇到了"receive shutdown event and so quit from MasterDaemon run loop" 这个问题，且没有其他报错信息。

### ISSUE THREAD

**Issue by xieyu0214** [PaddlePaddle/Paddle#51229]
### 请提出你的问题 Please ask your question

单机多卡训练时，遇到了"receive shutdown event and so quit from MasterDaemon run loop" 这个问题，即训练过程中突然终止，且没有其他报错信息。

分布式训练方式：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/model_convert/update_cn.html#danjiduokaqidong
中的`python -m paddle.distributed.launch train.py`方式

服务器：Centos7.6
paddlenlp==2.5.1
paddlepaddle-gpu==2.4.2.post117

@yt605155624

**Comment by 1649759610** [comment]
有没有关注过内存的使用情况呢，是不是内存溢出了？

**Comment by xieyu0214** [comment]
> 有没有关注过内存的使用情况呢，是不是内存溢出了？

应该不是的，同样的数据和参数，单卡可以训练，多卡就突然终止

**Comment by asif-ca** [comment]
@RileyShe Did you find the issue and fix it? I am facing the same issue

I am even unable to resume training on single gpu as well, the weird thing is that its not even giving any error and process terminates automatically after running the command

**Comment by xuxiansheng2018** [comment]
如何解决？

**Comment by asif-ca** [comment]
My issue was that I initially trained the model for 50 epochs. After testing, I wanted to resume training the model for an additional 10 epochs. I set the `epoch_num` parameter in the configuration file to 10, which was incorrect because the model checks the previously trained epochs and continues from there. Consequently, the loop was terminated prematurely.

 In my case, I corrected the value to 60 (50 previous epochs and the 10 epochs I wanted to resume for ), and the issue was resolved and training resumed from the 51th epoch.
