### ISSUE TITLE
能否发布Python 3.11的预编译包到仓库？

### ISSUE THREAD

**Issue by songwanqian** [PaddlePaddle/Paddle#52607]
### 需求描述 Feature Description

Python 3.11有较大的性能提升，能否将paddle兼容3.11以使整体项目可以升级到3.11提升性能？
Pytorch和Tensorflow都已支持Python 3.11

**Comment by LielinJiang** [comment]
感谢建议，已经在计划中了。预计2.6版本发布 3.11的预编译包

**Comment by glenn-jocher** [comment]
+1 for Python 3.11 pip package support. We can't run Python 3.11 CI for Ultralytics [YOLOv8](https://github.com/ultralytics/ultralytics) because `paddlepaddle` fails to install:

https://github.com/ultralytics/ultralytics/actions/runs/5490845075/jobs/10006774133?pr=3589
<img width="1659" alt="Screenshot 2023-07-08 at 00 02 43" src="https://github.com/PaddlePaddle/Paddle/assets/26833433/e2a048a5-7d45-44d0-b6b2-08f3799b25d9">
