### ISSUE TITLE
math functors needed

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#5364]
when I implement the Evaluator Python API, I need to compose some fundamental operators to compute `auc`, `precision`, so I find there is some low-level operator such as `equal`, `abs` is missing. Furthermore, we can not cover all the user's score operator, e.g., a bunch of variant `ndcg` operator, so we need a better low-level math op library to cover them.
 

We need to rush a math_ops library and provide a wrapper on python side.

**Comment by typhoonzero** [comment]
Implement evaluators using math ops is flexible, but hard to understand and less efficient (because ops' input and output will need more memory than directly calculate it using one). TF use math ops and Caffe2 simple use ops.

I think is we are going to accumulate the values, simply add an interface in the op to update the accumulated value is more simple, and no need to rush a math_ops lib. We can do that later if it's needed.
