### ISSUE TITLE
The GPU architecture in your current machine is Pascal, which is not compatible with Paddle installation with arch: 70 75 80 86 

### ISSUE THREAD

**Issue by jiangzhangze** [PaddlePaddle/Paddle#54713]
### 请提出你的问题 Please ask your question

I met with this problem after Installing paddle-gpu, will it affect my use?
```W0616 17:16:24.460505  2840 gpu_resources.cc:96] The GPU architecture in your current machine is Pascal, which is not compatible with Paddle installation with arch: 70 75 80 86 , it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.```

**Comment by kuizhiqing** [comment]
You can run the following command to check if paddle is installed properly,
```
python -c "import paddle; paddle.utils.run_check()"
```

**Comment by jiangzhangze** [comment]
Hi @kuizhiqing ，here are the output,do you have any advices?
```Running verify PaddlePaddle program ...
I0616 17:16:24.452527  2840 interpretercore.cc:237] New Executor is Running.
W0616 17:16:24.460505  2840 gpu_resources.cc:96] The GPU architecture in your current machine is Pascal, which is not compatible with Paddle installation with arch: 70 75 80 86 , it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W0616 17:16:24.460505  2840 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 12.1, Runtime API Version: 11.7
W0616 17:16:24.463497  2840 gpu_resources.cc:149] device: 0, cuDNN Version: 8.4.
I0616 17:16:24.930249  2840 interpreter_util.cc:518] Standalone Executor is Used.
PaddlePaddle works well on 1 GPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.```

**Comment by kuizhiqing** [comment]
It looks good for you installation.
You can continue to use paddlepaddle with your project and give feedbacks if you have any problem.

**Comment by xReniar** [comment]
I'm having the same issue: this is the output for `paddle.utils.run_check()`:

W1015 15:39:09.441613 65444 gpu_resources.cc:96] The GPU architecture in your current machine is Pascal, which is not compatible with Paddle installation with arch: 70 75 80 86 , it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W1015 15:39:09.441648 65444 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 11.2, Runtime API Version: 11.3
W1015 15:39:09.444262 65444 gpu_resources.cc:149] device: 0, cuDNN Version: 8.2.
W1015 15:39:09.485244 65450 gpu_resources.cc:96] The GPU architecture in your current machine is Pascal, which is not compatible with Paddle installation with arch: 70 75 80 86 , it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W1015 15:39:09.485272 65450 gpu_resources.cc:119] Please NOTE: device: 3, GPU Compute Capability: 6.0, Driver API Version: 11.2, Runtime API Version: 11.3
W1015 15:39:09.485355 65446 gpu_resources.cc:96] The GPU architecture in your current machine is Pascal, which is not compatible with Paddle installation with arch: 70 75 80 86 , it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W1015 15:39:09.485385 65446 gpu_resources.cc:119] Please NOTE: device: 1, GPU Compute Capability: 6.0, Driver API Version: 11.2, Runtime API Version: 11.3
W1015 15:39:09.485540 65448 gpu_resources.cc:96] The GPU architecture in your current machine is Pascal, which is not compatible with Paddle installation with arch: 70 75 80 86 , it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W1015 15:39:09.485646 65448 gpu_resources.cc:119] Please NOTE: device: 2, GPU Compute Capability: 6.0, Driver API Version: 11.2, Runtime API Version: 11.3
W1015 15:39:09.489851 65446 gpu_resources.cc:149] device: 1, cuDNN Version: 8.2.
W1015 15:39:09.490088 65450 gpu_resources.cc:149] device: 3, cuDNN Version: 8.2.
W1015 15:39:09.493158 65448 gpu_resources.cc:149] device: 2, cuDNN Version: 8.2.
Failed, NCCL error ../paddle/fluid/distributed/collective/process_group_nccl.cc:200 'unhandled cuda error'
Failed, NCCL error ../paddle/fluid/distributed/collective/process_group_nccl.cc:200 'unhandled cuda error'
Failed, NCCL error ../paddle/fluid/distributed/collective/process_group_nccl.cc:200 'unhandled cuda error'
Failed, NCCL error ../paddle/fluid/distributed/collective/process_group_nccl.cc:200 'unhandled cuda error'
WARNING:root:PaddlePaddle meets some problem with 4 GPUs. This may be caused by:
 1. There is not enough GPUs visible on your system
 2. Some GPUs are occupied by other process now
 3. NVIDIA-NCCL2 is not installed correctly on your system. Please follow instruction on https://github.com/NVIDIA/nccl-tests 
 to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html
WARNING:root:
 Original Error is: Process 3 terminated with exit code 1.
PaddlePaddle is installed successfully ONLY for single GPU! Let's start deep learning with PaddlePaddle now.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nvidia/anaconda3/envs/rainer/lib/python3.8/site-packages/paddle/utils/install_check.py", line 282, in run_check
    raise e
  File "/home/nvidia/anaconda3/envs/rainer/lib/python3.8/site-packages/paddle/utils/install_check.py", line 255, in run_check
    _run_parallel(device_list)
  File "/home/nvidia/anaconda3/envs/rainer/lib/python3.8/site-packages/paddle/utils/install_check.py", line 206, in _run_parallel
    paddle.distributed.spawn(train_for_run_parallel, nprocs=len(device_list))
  File "/home/nvidia/anaconda3/envs/rainer/lib/python3.8/site-packages/paddle/distributed/spawn.py", line 595, in spawn
    while not context.join():
  File "/home/nvidia/anaconda3/envs/rainer/lib/python3.8/site-packages/paddle/distributed/spawn.py", line 399, in join
    self._throw_exception(error_index)
  File "/home/nvidia/anaconda3/envs/rainer/lib/python3.8/site-packages/paddle/distributed/spawn.py", line 411, in _throw_exception
    raise Exception(
Exception: Process 3 terminated with exit code 1.

**Comment by renoyuan** [comment]
同样问题 +1 
gpu p100 Driver 535.129.03 cuda 11.6

且执行paddle.utils.run_check() 会抛出下面异常
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Access to an undefined portion of a memory object` is detected by the operating system.
  [TimeInfo: *** Aborted at 1703493808 (unix time) try "date -d @1703493808" if you are using GNU date ***]
  [SignalInfo: *** SIGBUS (@0x7f311a12d000) received by PID 2232 (TID 0x7f3181c34700) from PID 437440512 ***]

**Comment by HeedoKang** [comment]
I have the same issue.

W0909 09:52:47.539053   455 gpu_resources.cc:96] The GPU architecture in your current machine is Pascal, which is not compatible with Paddle installation with arch: 61 70 75 80 86 , it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W0909 09:52:47.539069   455 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 11.8, Runtime API Version: 11.8
W0909 09:52:47.539959   455 gpu_resources.cc:164] device: 0, cuDNN Version: 8.7.
CUDA error 98 [/usr/local/cuda/targets/x86_64-linux/include/cub/block/../iterator/../util_device.cuh, 375]: invalid device function
CUDA error 98 [/usr/local/cuda/targets/x86_64-linux/include/cub/block/../iterator/../util_device.cuh, 469]: invalid device function
CUDA error 98 [/usr/local/cuda/targets/x86_64-linux/include/cub/device/dispatch/dispatch_reduce.cuh, 612]: invalid device function
CUDA error 98 [/usr/local/cuda/targets/x86_64-linux/include/cub/block/../iterator/../util_device.cuh, 469]: invalid device function
CUDA error 98 [/usr/local/cuda/targets/x86_64-linux/include/cub/device/dispatch/dispatch_reduce.cuh, 612]: invalid device function
I0909 09:52:47.993520   455 interpreter_util.cc:648] Standalone Executor is Used.
CUDA error 98 [/usr/local/cuda/targets/x86_64-linux/include/cub/block/../iterator/../util_device.cuh, 469]: invalid device function
CUDA error 98 [/usr/local/cuda/targets/x86_64-linux/include/cub/device/dispatch/dispatch_reduce.cuh, 612]: invalid device function
CUDA error 98 [/usr/local/cuda/targets/x86_64-linux/include/cub/block/../iterator/../util_device.cuh, 469]: invalid device function
CUDA error 98 [/usr/local/cuda/targets/x86_64-linux/include/cub/device/dispatch/dispatch_reduce.cuh, 612]: invalid device function
PaddlePaddle works well on 1 GPU.
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script



+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:04:00.0 Off |                    0 |
| N/A   44C    P0    34W / 250W |    954MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
