### ISSUE TITLE
An build error in Mac os 10.12

### ISSUE THREAD

**Issue by burness** [PaddlePaddle/Paddle#551]
I  build the Paddle with MKL in Mac os 10.12, it get an error like that, Anyone could help me to solve it ?
```
/Users/burness/git_repository/dl_opensource/Paddle/paddle/utils/ThreadLocal.h:160:17: error: 'syscall' is deprecated: first deprecated in macOS 10.12 - syscall(2) is unsupported; please switch to a
      supported interface. For SYS_kdebug_trace use kdebug_signpost(). [-Werror,-Wdeprecated-declarations]
    pid_t tid = syscall(SYS_thread_selfid);
                ^
/usr/include/unistd.h:733:6: note: 'syscall' has been explicitly marked deprecated here
int      syscall(int, ...);
         ^
1 error generated.
make[2]: *** [paddle/utils/CMakeFiles/paddle_utils.dir/BarrierStat.cpp.o] Error 1
make[1]: *** [paddle/utils/CMakeFiles/paddle_utils.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by gangliao** [comment]
Hi, @burness

It's quite strange about your situation. I guess you use old release v0.8.x since we did not merge our latest [release v0.9.0](https://github.com/PaddlePaddle/Paddle/pull/484), which include the feature of supporting Mac OS X Sierra. 

I will let our colleagues speed up release schedule, thanks.

**Comment by burness** [comment]
I have search for it. It just because the osx sdk, I change the branch 'master' to 'develop'. It seem to be all right now
