### ISSUE TITLE
paddle.divide return wrong value value for int dtype 

### ISSUE THREAD

**Issue by samthakur587** [PaddlePaddle/Paddle#61635]
### bug描述 Describe the Bug

```python
import paddle 
import tensorflow as tf
a1 = paddle.to_tensor([1, 2, 3],dtype='int32')
a2 = paddle.to_tensor([3, 5, 2],dtype='int32')
b1 = tf.constant([1, 2, 3],dtype='int32')
b2 = tf.constant([3, 5, 2],dtype='int32')
print(a1)
print(b1)
# Expected Output:
result1 = paddle.divide(a1, a2)
result2 = tf.math.divide(b1, b2)
print(result1)
# Tensor(shape=[3], dtype=int32, place=Place(cpu), stop_gradient=True,
#        [0, 0, 1])
print(result2)
#tf.Tensor([0.33333333 0.4        1.5       ], shape=(3,), dtype=float64)
```

### 其他补充信息 Additional Supplementary Information

it's happening because the paddle returning the dtype as it has in input but what if we as input int like 1 and we divide this with int 2. then according to now it returning the int dtype in output which is 0. but it should be float and 0.5.

**Comment by liaoxin2** [comment]
根据已知信息，paddle.divide函数对于整数类型的输入返回错误的值，应该返回浮点数类型的值。这可能是因为函数的实现中存在取整或者四舍五入的操作，导致输出结果不符合预期。为了解决这个问题，您可以使用强制类型转换将整数类型的输入转换为浮点数类型，然后再进行除法运算。例如，可以使用`paddle.to_tensor`函数将整数类型的输入转换为浮点数类型的张量，然后再进行除法运算。

**Comment by liaoxin2** [comment]
Based on the provided information, the paddle.divide function returns incorrect values for integer inputs when it should return floating-point values. This might be due to the implementation of the function involving rounding or truncation operations, leading to output results that don't meet expectations. To address this issue, you can use type coercion to convert integer inputs into floating-point types before performing the division operation. For instance, you can use the paddle.to_tensor function to convert integer inputs into floating-point tensors and then perform the division operation.
