### ISSUE TITLE
Executor: need multiple thread support

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#6319]
Currently our `Executor` implementation is single threaded: it runs the `ProgramDesc` (actually `ProgramDescBind`, unrelated detail) sequentially.

It will have severe performance problem with the `ProgramDesc` that contains OPs that load data from disk or send/recv OPs that reads data from the network. The I/O will block the computation that could run in parallel.

The `Executor` needs to be able to analyze the dependency according to `ProgramDesc` (or `ExecutionPlan` in future if this [PR](https://github.com/PaddlePaddle/Paddle/pull/6078) passes), and schedule the OPs whose dependencies are finished to the thread-pool for parallel execution.

This issue is **blocked** by https://github.com/PaddlePaddle/Paddle/issues/6317 , since the `Executor` needs a reliable data structure (`ProgramDesc`, not `ProgramDescBind`) to do dependency analysis.

**Comment by QiJune** [comment]
I think that we will have a pool of DeviceContext. What Executor do is to take a DeviceContext from the pool to run the operator under the guide of device in operator. The Executor have to handle the dependency between operators. And all operators are launched asynchronized.

**Comment by Yancey1989** [comment]
As discuess at #6223 , we will convert the graph which user defined to a multi-thread graph as(omit the vars):
![multi-threads](https://user-images.githubusercontent.com/1426912/33649890-a722e3b2-da9a-11e7-9010-fb8af7e1e693.png)

Note that not all the operators will be run with mutli-threads, and the problem is **how the executor know which Op will be execute as multi-threads**. Maybe there is two ways to implement this(or more better ways):
1. We descirbe an Op a as node, If a node has two or more child-nodes(Split->Mul*2), we push the Ops into a ThreadPool to execut these Op.
Current. Currently, the Ops are described as a sequence in block, we need to modifty this to a tree struct.
1. Add different Block type, single-thread/multi-htread/..., and the Executor will push the multi-thread Block  into the ThreadPool.

**Comment by helinwang** [comment]
@Yancey1989 I think the executor execute all OP in the thread pool, so all of them are executed with multi-threads.

**Comment by helinwang** [comment]
@QiJune 

> all operators are launched asynchronizedly.

I think at least some OP can not run asynchronous, for example: OP that loads data from disk can not run asynchronous with the next OP that uses the data.

Maybe asynchronous is just a special case for GPU OP, because GPU stream handles the synchronization?

**Comment by helinwang** [comment]
Thread pool concept, IO thread, computation thread.

**Comment by helinwang** [comment]
We are already discussing concurrency design. This issue is out-of-date, closing.
