### ISSUE TITLE
How to set the learning rate scheduling strategy in Fluid?

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#6413]
How to set the learning rate scheduling strategy in the Python API of Fluid?

**Comment by luotao1** [comment]
related #6391

**Comment by qingqing01** [comment]
@luotao1 #6391 is how to set learning rate. That issue does not tell users how to set scheduling strategy, such as the strategy mentioned in http://doc.paddlepaddle.org/develop/doc_cn/faq/parameter/index_cn.html#learning-rate-annealing

**Comment by moting9** [comment]
Some learning rate questions in refactored Fluid:

 1. Will SGD be implemented as  OP(paddle/operators/sgd_op.cc) or optimizer (paddle/optimizer/sgd_optimizer.cc) in Fluid?  What's the difference between SGD OP and SGD Optimizer?
2.  If OP is used, how to control the LR policy? Is LR policy still wrapped as one OP?
3.  How to pass learning rate config parameters such as initial rate,  policy, local rate coefficient, locate rate on/off flag from python to OP or Optimizer? Is there any API defined?

**Comment by typhoonzero** [comment]
1. `paddle/optimizer/sgd_optimizer.cc` is a legacy version, you should only care about codes under `paddle/operators`. For better understanding, please refer to https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/optimizer.md
1. I think this is what this issue is going to talk about (also for 3.).
