### ISSUE TITLE
gcc 6 ? (for archlinux + python2)

### ISSUE THREAD

**Issue by fcellier** [PaddlePaddle/Paddle#67]
Hello,

In order to compare pyspark/tensorflow(+dask)/paddle, I created a package for Archlinux. There are small differences but, IMHO, one could be add to upstream ( [here](https://gist.github.com/fcellier/218d31d17d1af5eb44c49f35053208fa#file-gcc6-patch)  ). What do you think about it?

No regression observed.

Regards

**Comment by reyoung** [comment]
There are some fixes we will merge, such as `#include <cmath>`, `pip => pip2`.

[This line](https://gist.github.com/fcellier/218d31d17d1af5eb44c49f35053208fa#file-arch_python2-patch-L72) will not be merged, because user may want to install paddle in different directory.

The `PKGBUILD` we will test on a docker container, then may change something. Such as we will not [remove python wheels](https://gist.github.com/fcellier/218d31d17d1af5eb44c49f35053208fa#file-pkgbuild-L46), because user may use PaddlePaddle in `virtualenv` and these wheels will be installed again.

**Comment by fcellier** [comment]
Oh, I missed the use case with virtualenv...

For the $MYDIR lines, I do not have a good solution yet. In Archlinux, the binary needs to be in [/usr/bin instead of /bin](https://wiki.archlinux.org/index.php/Frequently_asked_questions#Does_Arch_follow_the_FHS.3F). 

Do not hesitate to tell me how I can help.

**Comment by hedaoyuan** [comment]
Closed due to inactivity, please feel free to reopen.
