### ISSUE TITLE
The size of libmkldnn.so.0 is 0B in capi

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#7181]
Users encounter that lack of libmkldnn.so.0, and they `mv libmkldnn.so libmkldnn.so.0` currently to solve this problem. The reason is that libmkldnn.so.0 is a soft connection.
![image](https://user-images.githubusercontent.com/6836917/34548607-feb5985e-f13d-11e7-9fe1-f73b9b0e84fe.png)
The download address of paddle.tgz is [here](https://guest@paddleci.ngrok.io/repository/download/Manylinux1_CpuAvxCp27cp27mu/.lastSuccessful/paddle.tgz).

**Comment by tensor-tang** [comment]
1. Could u give some details about the "Users encounter that lack of libmkldnn.so.0".

2. And could u give some details description what does the paddle.tgz mean?
Since actually we did not use `libmklml_gnu.so` at all, but it was contained in this pkg.

It seems this tgz  just contains all thirty party into the `lib` dir. 
Then the `libmkldnn.so` and `libmkldnn.so.0` would be contained as well, and both of them are just soft link and generated by mkldnn itself.

BTW, some background:
Paddle just use libmkldnn.so as [MKLDNN_LIB ](https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/external/mkldnn.cmake#L34).

The `${MKLDNN_LIB}.0` would only be contained when generating python whl.

**Comment by tensor-tang** [comment]
The numbers in the shared libraries are convention used in Linux to identify the API of a library. Quoted [here](https://unix.stackexchange.com/questions/475/how-do-so-shared-object-numbers-work).
 
like :
```
 ldd /usr/local/lib/libpaddle_capi_shared.so
        linux-vdso.so.1 =>  (0x00007ffe4a9d2000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1739d0c000)
    ...
```

So the reason maybe that capi did not contain the *.so.0, which must be linked by another shared lib, like `libpaddle_capi_shared.so`.

Just find how capi packages the dependent libs and add the right so would be fine.

**Comment by luotao1** [comment]
> Could u give some details about the "Users encounter that lack of libmkldnn.so.0

"请教一下，用capi进行预测，使用libpaddle_capi_shared.so等动态库，运行时报错还差一个libmkldnn.so.0，但是在TC上，最近编译成功的版本中这个文件大小为0，请问该怎么找到这个文件？"

> And could u give some details description what does the paddle.tgz mean

@Yancey1989 Could u help tell us how `paddle.tgz` come from?

**Comment by Yancey1989** [comment]
The source code of `build && package` package.tgz on TC, I will merge it into `docker/build.sh`.
