### ISSUE TITLE
怎样获取一个向量的多个dotmul_projection

### ISSUE THREAD

**Issue by rulai-huiyingl** [PaddlePaddle/Paddle#7265]
希望得到一个vector(e.g.last_seq of lstm)的多个perspective，每个perspective是这个vector和一个weight做element wise multiplication，也就是dotmul_projection.
有没有简单的接口可以直接获得多个dotmul_projection？ 输入是一个d维的dense vector, 输出是n个d维的vector (sequence of dense vector).
感觉用conv类的接口应该可以，但是没有找到合适的。。。谢谢！

**Comment by emailweixu** [comment]
layer.linear_comb() might be what you need

**Comment by emailweixu** [comment]
you can first use layer.repeat then use layer.dotmul_projection

**Comment by huiyingl** [comment]
@emailweixu 
Thank you very much for answering!
May I also ask, what does layer.repeat turn the original vector into?  A simple (orig_len x num_repeats, 1) shaped vector or a sequence of vectors? Intuitively I would think it is the same as numpy.concat where I get a orig_len x num_repeats lengthed vector. But layer.concat is also used in recurrent_group to concat output so that should be sequence/original shape is remained...

What I want to achieve:
If I have a sequence of dense_vectors, and then repeat each of the dense_vector N times (assume this is done through step func of a recurrent_group). Then I want to max pool this step-repeated sequence in the fashion that, each step's i th vector is pooled with other step's i th vector. (This pooling procedure is meaningless.. just to understand the process.) Would pooling.Max() with AggregateLevel.EACH_TIMESTEP produce the result?

An example of input, output:
```
input: each step is layer.repeat(num_repeat=4)
[[[0,1,2,3],
 [0,1,2,3],  #does layer.repeat return a sequence like I draw here?
 [0,1,2,3]],
 [[4,5,6,7], 
  [4,5,6,7],
  [4,5,6,7]]
]
desired output:
[[[4,5,6,7], 
 [4,5,6,7],
 [4,5,6,7]]
]
```
If layer.repeat returns a single vector/something that will be treated as non-splittable, then each element should be compared with the corresponding element of repeated vectors in other steps, and it should work for my purpose.
But if layer.repeat returns a sequence, then I'm not sure how pooling.Max() will treat the sequence/subsequence...
The CN documentation (进阶-支持双层序列作为输入的Layer) is a bit vague to me. 
Thank you very much!

**Comment by emailweixu** [comment]
If the input of repeat is a sequence of vector,it's result is still a sequence vector with same sequence length. The dim of each vector is four times of the original one

**Comment by emailweixu** [comment]
You can use layer.printer to show the content of a layer

**Comment by huiyingl** [comment]
@emailweixu Thanks for your answer, this is very useful to know.
If I maxpool over a sequence of repeated sequences, would the repeated (sub)sequence considered as a whole (i.e. wont be pooled with each other) to maxpool? 
Thanks!

**Comment by huiyingl** [comment]
@emailweixu I found printer_layer and print_layer in trainer_config_helpers.. Did not find layer.print in v2 API. I will use that to try. Thank you very much!
