### ISSUE TITLE
Whether Fluid distributed training should do cost merging in parameter server?

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#7671]
From Paddle v1 implementation, I see https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/pserver/ParameterServer2.cpp#L1228
 here have operations to merge the cost sent from every trainer, but not sure why we need this and do we also have to implement this in current fluid distributed training framework?

**Comment by helinwang** [comment]
Interesting, `op_cost` is a remote function registered on [`PSERVER_OP_COST`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/pserver/ParameterServer2.cpp#L1262)
But I don't see `PSERVER_OP_COST` used anywhere.

**Comment by abhinavarora** [comment]
I spoke with Xu Wei about why this was done in the old code. The code that references this has been removed. It was implemented in order to support the [line search](https://en.wikipedia.org/wiki/Line_search) that is required for [limited memory BFGS algorithm](https://en.wikipedia.org/wiki/Limited-memory_BFGS). 

I think we can skip this for now and focus on it later when it is needed.
