### ISSUE TITLE
Please adjust the structure of documentation

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/Paddle#8037]
In order to enhance V2 website and docs structure, we have adjusted the structure of docs.

This is a [Chinese Version mind map](https://shimo.im/docs/nmHJeHAqOEkHqorN), English Version please see #8230

Please refer to the structure in this mind map and adjust 【ducumentation】（使用文档）,including: structure and name. 
Note: this issue mainly focus on 【documentation】, Others，Like【API】，have been written in other issues.

------------------------------------------------------------------------------------------
**Project Background**
Polish documentation of PaddlePaddle, enhancing user experience
-----Enhancement Plan: 
Stage 1: https://note.youdao.com/share/?token=83F0AB634A7749E6B4676F823D6EC343&gid=69922175#/
-----Enhancement Schedule: 
https://shimo.im/sheet/VnyT2IKRHjoU1a6i/6HGyl// 

Thank you very much!

**Comment by luotao1** [comment]
We could remove [mobile section](http://www.paddlepaddle.org/docs/develop/documentation/zh/mobile/index_cn.html) in the left navigation bar, since we have the same context in the [top navigation bar](http://www.paddlepaddle.org/docs/develop/mobile/README.cn.html).
![image](https://user-images.githubusercontent.com/6836917/35787345-5a8d1a9c-0a68-11e8-81f1-2dc025a7577b.png)
