### ISSUE TITLE
Please add an introduction of API

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/Paddle#8042]
After the website enhancement, there will be an API main-page.
![image](https://user-images.githubusercontent.com/35982308/35672889-e11cef74-077a-11e8-87ed-765fde8984a3.png)

We have to add an introduction on this page to tell users, for example, the features of PaddlePaddle API, and help them have a better grasp of our API documentation.
The introduction may be from design doc, etc. 

Thank you very much!

------------------------------------------------------------------------------------------
**Project Background**
Optimize documentation of PaddlePaddle, enhancing user experience
-----Optimization Plan: 
[Stage 1 MRD](https://note.youdao.com/share/?token=83F0AB634A7749E6B4676F823D6EC343&gid=69922175#/) 
-----[Optimization Schedule（Update everyday）](https://shimo.im/sheet/VnyT2IKRHjoU1a6i/6HGyl// )

**Comment by cs2be** [comment]
I think this can be achieved in Sphinx now if we add a top level API section as the first document and call it something like “Introduction” that has no child links under.  Since this left navigation is auto generated from Sphinx TOC, to make sure that Paddle developer can easily control structure without having to update PPO, we recommend not adding custom rules (like showing a API homepage that doesn’t have a link on left navigation).  Please let me know what you guys think.

**Comment by shanyi15** [comment]
got it, your recommendation makes sense. i'll discussed with luotao1 and give you our thought

**Comment by luotao1** [comment]
@cs2be I agree with you, I will solve it ASAP.

**Comment by shanyi15** [comment]
overview documentation needs to be written.

**Comment by shanyi15** [comment]
website: http://www.paddlepaddle.org/docs/develop/api/en/overview.html
