### ISSUE TITLE
Make select.case a little more readable 

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#8165]
It looks to me that 

```python
sel = fluid.select()
with sel.read_case(ch, x):
  do_something_with(x)
```

is a little more readable than

```python
sel = fluid.select()
with sel.case(ch, X, 'r'):
  do_something_with(x)
```

What do you think?

**Comment by helinwang** [comment]
How about:
```Python
sel = fluid.select()
with sel.case(ch.read(), x):
  do_something_with(x)
```

**Comment by kavyasrinet** [comment]
I agree with both proposals. 
For proposal, we will have `sel.read_case` and `sel.write_case` as methods of `select`.
For second proposal, we can have more consistency and can reuse concepts from `channel` implementation. Since in the PR: https://github.com/PaddlePaddle/Paddle/pull/8164 , the proposal is to make `send` and `recv` as functions of `fluid` instead of `channel`. So it will be more like:
```
sel = fluid.select()
with sel.case(fluid.read(ch), x):
  do_something_with(x)
```

**Comment by abhinavarora** [comment]
I agree with @wangkuiyi first proposal of using 
```
sel = fluid.select()
with sel.read_case(ch, x):
  do_something_with(x)
```

@helinwang , I like your suggestion too. I am just a little skeptic that since we will have to implement it for both the cases, i.e. the standalone channel and select, we might run into complications. I think we can start off with Yi's first suggestion and then later see  if we can support your design. What do you think?
