### ISSUE TITLE
Big size of repo after build.

### ISSUE THREAD

**Issue by pawelszewc** [PaddlePaddle/Paddle#8468]
Building Paddle from source generates large amount of data.
With setting flag WITH_TESTING to OFF repo size is 12GB.
With setting flag WITH_TESTING to ON repo size is 25GB.
Is that correct behavior? 
For example Tensorflow repo size after build is around 400 MB

**Comment by luotao1** [comment]
Yes, our building repo size is large now. If you use Linux + Docker, you can set `DCMAKE_BUILD_TYPE=Release` to further decrease the repo size. (related https://github.com/PaddlePaddle/Paddle/issues/7969#issuecomment-361514360) 

And since our repo contains old PaddlePaddle + fluid, after we complete `with_fluid` compile option (#6346) , the building repo size will further decrease.

**Comment by pawelszewc** [comment]
Thanks for explanation @luotao1

**Comment by luotao1** [comment]
@pawelszewc `with_fluid` compile option is finished by #9067. Feel free to contact us if any questions when using this option.
