### ISSUE TITLE
C++接口使用capi，编译重构，demo执行失败

### ISSUE THREAD

**Issue by nuoline** [PaddlePaddle/Paddle#8605]
使用C++接口调用paddle训练的模型，编译成功，写了一个demo执行识别。
提示如下：
I0227 15:37:09.523689 17971 Util.cpp:161] commandline:  --use_gpu=False 
W0227 15:37:09.523816 17971 CpuId.h:110] PaddlePaddle wasn't compiled to use avx instructions, but these are available on your machine and could speed up CPU computations via CMAKE .. -DWITH_AVX=ON
libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "paddle.ModelConfig" because it is missing required fields: type
Invoke paddle error 3 in paddle_gradient_machine_create_for_inference(&_machine, _config_buf, (int)_config_size)

**Comment by Yancey1989** [comment]
请问是 https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/capi/examples/model_inference 这里的Demo么？ train和inference使用的Paddle是否同一版本呢？

**Comment by nuoline** [comment]
是我自己训练的序列标注模型，自测的demo，不是paddle里面的DEMO。
 train和inference使用的Paddle版本如何判断是否一致？

**Comment by Yancey1989** [comment]
> train和inference使用的Paddle版本如何判断是否一致？

可以使用`paddle version` 看下大版本是否一致，另外可以尝试都使用最新版本的paddle。

**Comment by nuoline** [comment]
训练的版本是PaddlePaddle 0.10.0， inference的版本别人编译的，如何看？

**Comment by lcy-seso** [comment]
请问文档中 http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/capi/workflow_of_capi_cn.html  准备预测模型中的`序列化神经网络模型配置`这一步是如何做的？上面的错误可能是因为这一步在序列化过程中调用的相关Python脚本版本和inference的bin版本不匹配引起的。

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
