### ISSUE TITLE
曲线拟合无法快速收敛的原因

### ISSUE THREAD

**Issue by kongdeyu** [PaddlePaddle/Paddle#8825]
通过paddlepaddle处理一个曲线拟合问题，拟合的结果是类似阶跃函数的一条曲线，如下图：
![image](https://user-images.githubusercontent.com/8944884/37072011-557cc83c-21fa-11e8-8f52-75c31218ca65.png)
输入数据只有x（feature）和y（label）两列，但是在训练的过程中，发现不能很好的收敛。
后面，我这边对y值做了一个预处理，对y列的每一个值，y = y - min(所有的y)，通过这种方式将y列调整为最小值是0，实际上相当于把最终的曲线整体下移，使的最小值是0，然后就能很快的收敛，请问是为什么了？

**Comment by lcy-seso** [comment]
y的取值范围是什么？plot一下y值分布。
最后一层的激活函数是什么？

**Comment by kongdeyu** [comment]
1360<=y<=1428，总共5000条记录，分布图如下：
![image](https://user-images.githubusercontent.com/8944884/37088382-1eb19312-2238-11e8-9067-0324ebb6ebfd.png)
最后一层的激活函数是relu：
![image](https://user-images.githubusercontent.com/8944884/37088683-235cca52-2239-11e8-9ee2-05204aa9b991.png)

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
