### ISSUE TITLE
timeline工具解析profile文件时报错:Tag had invalid wire type

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/Paddle#8881]
按照https://groups.google.com/forum/#!topic/caffe-users/WwvC_N4KpuI的方式可以正常使用

**Comment by kolinwei** [comment]
建议按照这样在timeline中解析profile文件：https://groups.google.com/forum/#!topic/caffe-users/WwvC_N4KpuI

**Comment by wangkuiyi** [comment]
"tag had invalid wire type"  这个错误应该是因为PaddlePaddle的 framework.proto 里定义的 protobuf messages 的 field id 被修改了，并且这个修改不符合 protobuf 兼容性要求。

@kolinwei 是想建议 timeline 工具在 PaddlePaddle 程序运行是输出 prototxt 格式？这样确认人眼可读，方便debug？我觉得是个好思路。请 timeline 的作者 @panyx0718 和合作者 @jacquesqiao 看看吧。

**Comment by kolinwei** [comment]
@ranqiu92 就是在用timeline.py工具解析生成的profile文件时出错了，

**Comment by kolinwei** [comment]
@wangkuiyi 恩，当前timeline是个比较独立的工具，可以放入fluid的 api中集成下，类似tf那样，paddle程序运行时就可以输出prototxt或者chrome:trace格式的profile文件了。

**Comment by panyx0718** [comment]
是的，timeline目前只是一个原型版本，服务与近期一些紧急的性能测试，将来还会逐渐改善。你的问题有可能是因为profiler.proto文件格式改了，所以原来生成的profiler文件无效了。可以再生成一次。

将来稳定后profiler.proto不会随意更改。最新版本生成的是binary proto，这样比较节省空间

**Comment by wangkuiyi** [comment]
@panyx0718 考虑过 @kolinwei 建议的 https://aras-p.info/blog/2017/01/23/Chrome-Tracing-as-Profiler-Frontend/ 格式吗？

**Comment by panyx0718** [comment]
@wangkuiyi 我理解那篇blog就是说的chrome tracing的格式。目前我们先生成一个profiler.proto的proto文件，然后用timeline.py转成chrome tracing的格式，就可以在chrome里用了。

chrome tracing也有很多局限性，比如他时间精度貌似只有毫秒。而且memory不好表达。中长期，我希望有Paddle定制化的UI。可以考虑集成到VisualDL里，然后定义一个类似chrome tracing的深度学习模型profile格式，支持Paddle和其他一些框架

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
