### ISSUE TITLE
API doc problems of conv2d, pool2d, conv2d_transpose

### ISSUE THREAD

**Issue by ranqiu92** [PaddlePaddle/Paddle#9097]
#### 单词拼写、遗漏和语法等问题未列出，修改时请注意
*请参考[API注释标准](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/dev/api_doc_std_cn.md)！*
------
源文件：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py

- conv2d
http://www.paddlepaddle.org/docs/develop/api/en/fluid/layers.html#conv2d
  - 默认值问题（缺失或位置错误）
  - 数据类型问题（None不作为返回值）
  - 参考文献问题（位置错误）
  - 格式问题（Returns， 尽量不要新增模块或复用模块名）
  - 介绍欠佳，请重新组织语言（如 param_attr、bias_attr等）
  - 显示问题
![image](https://user-images.githubusercontent.com/31875089/37441774-f854af54-283d-11e8-9288-e4521690781a.png)

- pool2d
http://www.paddlepaddle.org/docs/develop/api/en/fluid/layers.html#pool2d
  - 内容不完整

- conv2d_transpose
http://www.paddlepaddle.org/docs/develop/api/en/fluid/layers.html#conv2d-transpose
  - 默认值问题（缺失或位置错误）
  - 数据类型问题（None不作为返回值）
  - 参考文献问题（位置错误）
  - 格式问题（Returns， 尽量不要新增模块或复用模块名）
  - 介绍欠佳，请重新组织语言（如 param_attr、bias_attr等）
  - 显示问题
![image](https://user-images.githubusercontent.com/31875089/37448283-ad2c309c-2860-11e8-9d97-467a8ed17d25.png)

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
