### ISSUE TITLE
The CI hangs over 12 hours and not started.

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#9514]
https://github.com/PaddlePaddle/Paddle/pull/9489
![image](https://user-images.githubusercontent.com/10721757/38121494-30234592-3402-11e8-8c87-35e54d0a9007.png)

**Comment by helinwang** [comment]
I have noticed this problem as well, it seems that TeamCity failed to be notified by the Github webhook. The current solution is to do a push again to trigger the CI.

**Comment by putcn** [comment]
me and @helinwang  investigated a bit in this case. there might be 2 possibilities,
1. teamcity failed to pull changes from github and no build started
2. teamcity failed to report build status to github after picked up the changes and started the build
but currently we have no way to investigate further since this commit has been merged and status are all normal. 
let's keep an eye on this kind of situation and investigate it when it happens again
