### ISSUE TITLE
Three modules in paddle/fluid/memory/detail are highly coupled

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#9700]
In `paddle/fluid/memory/detail/`, the three modules

- memory_block.{h,cc}
- meta_data.{h,cc}
- meta_cache.{h,cc}

are highly correlated:
   
1. memory_block.h depends on meta_cache.h

   https://github.com/PaddlePaddle/Paddle/blob/bcb46f554986a07330afc2bbf34356322d4b833d/paddle/fluid/memory/detail/memory_block.h#L36-L45

1. meta_cache.h depends on meta_data.h

   https://github.com/PaddlePaddle/Paddle/blob/bcb46f554986a07330afc2bbf34356322d4b833d/paddle/fluid/memory/detail/meta_cache.h#L40

1. meta_data.h depends on memory_block.h

   https://github.com/PaddlePaddle/Paddle/blob/bcb46f554986a07330afc2bbf34356322d4b833d/paddle/fluid/memory/detail/meta_data.h#L46-L47

Should we merge these three modules into one, or at least change the following CMakeLists.txt rules:

https://github.com/PaddlePaddle/Paddle/blob/bcb46f554986a07330afc2bbf34356322d4b833d/paddle/fluid/memory/detail/CMakeLists.txt#L9-L13

into one

```cmake
cc_library(meta_data_cache SRCS meta_data.cc meta_cache.cc memory_block.cc)
```

**Comment by gangliao** [comment]
@wangkuiyi 

1. In order to make sure that GPU allocation is processed very quickly, `meta_cache.h` is used to cache the metadata of GPU memory block on CPU memory.

https://github.com/PaddlePaddle/Paddle/blob/bcb46f554986a07330afc2bbf34356322d4b833d/paddle/fluid/memory/detail/meta_cache.cc#L45-L50

2. `memory_block` is just an abstraction which doesn't include any members. 
When we allocate memory blocks from the large memory chunk,  all of them are the continuous memory.  `meta_data` and `memory_block` have the same starting memory address (`meta_data` is the first part of the memory block) so that they can be efficiently cast to each other to quickly response the allocation requirement.  If you integrate all members from`meta_data` into `memory_block`, I think it's feasible. But it's non-trivial work.


The 2nd option is much better:

```cmake
cc_library(meta_data_cache SRCS meta_data.cc meta_cache.cc memory_block.cc)
```

**Comment by wangkuiyi** [comment]
I see. Thanks for the detailed explanation. That is very helpful!

Is it a good idea that we add a data member in MemoryBlock

```c++
class MemoryBlock {
...
 private:
  MetadataCache* cache_;
}
```

so that we can remove the first parameter (`MetadataCache& cache`) from all accessors of MemoryBlock. For example:

```c++
Type MemoryBlock::type(MetadataCache& cache) const { ... }
```

could be

```c++
Type MemoryBlock::type() const { ... }
```

**Comment by wangkuiyi** [comment]
Thanks for the detailed explanation. Is that when `MetadataCache` is used to manage GPU memory, `Metadata` resides at the beginning of each `MemoryBlock`, whereas for GPU memory, `Metadata` resides in CPU memory, but not in the GPU `MemoryBlock`?
