### ISSUE TITLE
Move reduceSum from fluid/platform/cuda_helper.h to fluid/operator

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#9770]
From https://github.com/PaddlePaddle/Paddle/search?utf8=%E2%9C%93&q=reduceSum&type=,

it seems that the only use of function template `reduceSum`

https://github.com/PaddlePaddle/Paddle/blob/5469c08188eec67d84ae4ea3df28e02ae775bee9/paddle/fluid/platform/cuda_helper.h#L78-L85

is at

https://github.com/PaddlePaddle/Paddle/blob/c43995ed36ae2aefa628c5c2b38e35ca570052e8/paddle/fluid/operators/elementwise_op_function.h#L358

This template should be moved to where it is used.

**Comment by wangkuiyi** [comment]
After moving `reduceSum`, we should rename `cuda_helper.h` into `cuda_atomic.h`, because the left content is all about atomic operations with CUDA.

The point here is **to use accurate and precise names**, other than "util", "helper", etc.

**Comment by chengduoZH** [comment]
> After moving reduceSum, we should rename cuda_helper.h into cuda_atomic.h

I agreed with you, but I think `reduceSum` can be placed is `cuda_device_functions.h` but not `elementwise_op_function`. The reason is this `reduceSum` is faster than other implementations because it uses Warp-Level Parallelism. Though currently, it is only used by elementwise_add, it is a common function, when we add new operations, we can call this directly if we need use Reduce. 
So I prefer to put this function in `cuda_device_functions.h`.

**Comment by wangkuiyi** [comment]
软件开发和其他组织工作一样需要有原则 —— 一个事儿说了之后大家都知道类似情况应该怎么办。

这个事情有两个备选原则：

1、如果一个函数（比如sumReduce）只在一个地方用了，那就定义在用的地方（附近）。或者说，
2、如果一个函数虽然只在一个地方用了，但是**可能**被在别处使用，那么应该放在一个独立的地方。

原则1、是说得明白也很容易照着做的。你再说给别人听，“别人”也容易明白并且照做。

原则2、里有很多模棱两可的地方：

- 怎么评价“可能”在别的地方用？几乎每个函数都可以被估计为“可能”在别处用。那么一个团队里不同的人的评估结果可能不一样，这就造成分歧了。

指定组织原则的基本目标是 —— 帮助大家达成一致，所以不容模棱两可的原则。

**Comment by chengduoZH** [comment]
@wangkuiyi 好的，明白了，谢谢！
