### ISSUE TITLE
int64 instead long long int in cuda_helper.h

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#9801]
In `paddle/fluid/platform/cuda_helper.h` we have 

https://github.com/PaddlePaddle/Paddle/blob/add367c3f4b77103cda50b9359492f34a366477c/paddle/fluid/platform/cuda_helper.h#L32-L36

cpplint suggests that we use int16/int64/etc instead of `long long int` etc:

```
cuda_helper.h:36:  Use int16/int64/etc, rather than the C type long  [runtime/int] [4]
cuda_helper.h:39:  Use int16/int64/etc, rather than the C type long  [runtime/int] [4]
cuda_helper.h:41:  Use int16/int64/etc, rather than the C type long  [runtime/int] [4]
cuda_helper.h:42:  Use int16/int64/etc, rather than the C type long  [runtime/int] [4]
cuda_helper.h:49:  Use int16/int64/etc, rather than the C type long  [runtime/int] [4]
cuda_helper.h:50:  Use int16/int64/etc, rather than the C type long  [runtime/int] [4]
cuda_helper.h:51:  Use int16/int64/etc, rather than the C type long  [runtime/int] [4]
```

Is there any reason we chose to use `long long int` instead of `int64` that prevents us from following cpplint's suggestion? If not, let us correct them.

**Comment by reyoung** [comment]
Opps... Actually, we cannot use `uint64_t` here. CUDA API uses `unsigned long long int`, `unsigned long long int` is not necessarily as same as `uint64_t`. (However, in this file, we actually check size_of(`long long int`) == 64 bit, by `static_assert`. So, the int length is also fixed in this API.).

I just add `NOLINT` comments to this file.
