### ISSUE TITLE
请问梯度量化的实现开源了吗？没有找到具体的实现。

### ISSUE THREAD

**Issue by hbsun2113** [PaddlePaddle/Paddle#9832]
如题。麻烦给出具体的实现位置。

**Comment by pkuyym** [comment]
`梯度量化`能详细解释一下吗？是指分布式训练时，对梯度压缩提高传输效率吗？

**Comment by hbsun2113** [comment]
是的。除了梯度量化之外，在网络传输方面，还做了其他优化吗？

**Comment by hbsun2113** [comment]
这方面除了代码之外，不知道还有没有相关文档和paper？

**Comment by pkuyym** [comment]
@hbsun2113 很抱歉，目前paddle分布式暂不支持梯度量化，有这方面的计划，暂无法给出具体排期。

**Comment by wanghaoshuang** [comment]
@hbsun2113 抱歉，这篇文章讲的是【为什么paddle没有实现】。

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
